WizardFactory/TodayWeather

server/controllers/controllerPush.js
server/controllers/lifeIndexKmaController.js

#1450
string 변환시에 i18n instance 전달.

한글 push message에서 uv grade가 영어로 표시되는 문제

---

client/scss/ionic.app.scss
client/www/templates/tabs-android.html

active 된 tab만 title 를 보여주자

---

server/lib/AW/awRequester.js
server/test/testAW/testAwRequester.js

#1452 Added AccuWeather requester

---

server/controllers/worldWeather/controllerCollector.js

#1457
0시가 아니라 1시 기준으로 날씨를 가지고 와서 day light saving이 변경될때 이전날로 넘어가지 않게 수정

day light saving으로 offset 변경시 오류

---

client/www/js/app.js

#1455 #1043
opacity는  actived tab이 1, 나머지는 0.7로 유지

opacity 유지

---

client/www/js/controllers.js
client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json

#1460
android only
isLocationAuthorized 값은 gIsLocationAuthorized 으로 빼서 사용.

앱 권한이 없는 경우 설정으로 유도.

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/package.json
client/www/locales/de.json
client/www/locales/ja.json

de, ja에서 모레 제거.
Opens the "App Info" page in the Settings app when app permission was disabled.

release 0.9.35

---

client/www/js/controllers.js
client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json
server/controllers/controllerKmaStnWeather.js
server/controllers/worldWeather/controllerWorldWeather.js
server/locales/de.json
server/locales/en.json
server/locales/ja.json
server/locales/ko.json
server/locales/zh-CN.json
server/locales/zh-TW.json

#1459
dry, dangerously windy, sleet

new weather type dry, dangerously windy, sleet

---

client/www/js/app.js
client/www/js/controller.guidectrl.js
client/www/js/controller.searchctrl.js

#1476
angular error 발생시에 reporting
guide에서 location enabled 체크하여 시작방법 제안
search에서 keyboard event 추적

angular error, start popup, keyboard show/hide event

---

client/www/js/controller.searchctrl.js
client/www/templates/tab-search.html

set focus on input when enabled city count is zero

---

client/www/js/controller.searchctrl.js
client/www/js/service.weatherutil.js

#1463
country가 KR인경우 address에 daum address(한글)을 추가하고 google에서 받은 address는 googleAddress에 추가하여 searchTab에서 보여줄수 있게 변경.

search tab에서 현재위치로 검색시에 한글로만 나오는 문제

---

client/www/js/controller.tabctrl.js

외국 날씨 공유시에 지역명 오류

---

client/www/js/controller.searchctrl.js
client/www/js/controller.tabctrl.js

#1456
한국어로 국내날씨 검색시에 location 정보 잘못 들어가서 공유가 안됨
공유시 최고온도,최저온도 문구 오류 수정.

날씨 공유시에 에러 발생

---

server/controllers/worldWeather/controllerWorldWeather.js

- changed unit of timeoffset from hour to minute when it is calculated.

#1470 calculating timeoffset

---

server/lib/DSF/dsfRequester.js
server/test/testDSF/testDsfRequester.js

#1485 Error handler for ETIMEDOUT

---

server/lib/FC/fcRequester.js
server/test/testFC/testFcRequester.js

#1488 Added Foreca lib

---

client/www/js/controller.forecastctrl.js
client/www/js/controller.searchctrl.js
client/www/js/controller.tabctrl.js
client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json
client/www/templates/tabs-android.html
client/www/templates/tabs.html

#1472 #1476
사용자에게 추가 팝업으로 검색과 재시도 제공
완전 거부한 경우 검색과 설정 유도
focus 설정을 tabCtrl에서도 사용할 수 있게 event방식으로 변경

사용자가 위치권한 요청을 거부한 경우 시나리오 개선 

---

server/controllers/controllerTown.js

fixed wsd grade

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml

사용자가 위치권한 요청을 거부한 경우 시나리오 개선
날씨 공유시에 에러 발생 수정
외국 날씨 공유시에 지역명 오류 수정
search tab에서 현재위치로 검색시에 한글로만 나오는 문제 수정

release 0.9.36

---

ios/widget/Base.lproj/Info.plist
ios/widget/Base.lproj/MainInterface.storyboard
ios/widget/TodayViewController.h
ios/widget/TodayViewController.m
ios/widget/TodayWeatherShowMore.h
ios/widget/TodayWeatherShowMore.m
ios/widget/TodayWeatherUtil.h
ios/widget/TodayWeatherUtil.m
ios/widget/WidgetConfig.h
ios/widget/de.lproj/Info.plist
ios/widget/ja.lproj/Info.plist
ios/widget/zh-Hans.lproj/Info.plist
ios/widget/zh-Hant.lproj/Info.plist

#1332, #1334, #1491
- iOS Native 부분 다국어 지원 
- iOS Native 부분 world weather parser
- [iOS] mainapp과 widget의 현재위치가 상이하게 나오는 이슈

* iOS 다국어 지원 및 현재위치 이슈 수정

---

ios/widget/Base.lproj/MainInterface.storyboard
ios/widget/zh-Hans.lproj/Info.plist

#1268, #1332
[iOS] Today Extension(Widget) 더 보기 기능 추가
- gray->black 일부 레이블 수정
iOS Native 부분 다국어 지원
- 중국어 간체 Localized resources can be mixed : true 추가

* text color 변경 및 중국어 간체 Key 추가

---

client/www/js/app.js
client/www/js/controller.settingctrl.js
client/www/js/service.push.js

#1477
angular error 시 표시 수정
trackEvent, trackException 호출시 ga 빠진 부분 수정

Fixed error object name

---

client/www/js/controller.forecastctrl.js

check plugin loaded

---

client/www/js/service.weatherutil.js

remove ready function

---

server/controllers/controllerTown.js

#1509
areaNo와 results 값에 대한 valid check

areaNo가 없는 경우 죽는 문제

---

ios/widget/Base.lproj/Localizable.strings
ios/widget/LocalizationDefine.h
ios/widget/de.lproj/Localizable.strings
ios/widget/en.lproj/Localizable.strings
ios/widget/ja.lproj/Localizable.strings
ios/widget/ko.lproj/Localizable.strings
ios/widget/zh-Hans.lproj/Localizable.strings
ios/widget/zh-Hant.lproj/Localizable.strings

#1332
iOS Native 부분 다국어 지원
- Localizable.strings 및 define header 추가

* Localizable.strings 및 define header 추가

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/package.json

Improve use of location service

release 0.9.37

---

client/www/js/controller.forecastctrl.js
client/www/js/controller.searchctrl.js
client/www/js/service.weatherutil.js

#1474 #1515
cache geoInfo
remove _nativeRetryGetCurrentPosition
add watchPosition
custom retry options of getCurrentPosition

custom getCurrentPosition and cache geoInfo

---

client/www/js/controller.forecastctrl.js
client/www/js/controller.tabctrl.js

#1507 #1085
data 못가지고 오는 경우 분리

Fix error when weather data acquisition fails

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/package.json

Fix error when weather data acquisition fails

release 0.9.38

---

server/lib/kecoRequester.js

#1532
parseInt, parseFloat를 사용하여 변환후 NaN check하게 수정.

pm2Grade is not number like '*'

---

server/controllers/controllerShortRss.js

'fail to save'

---

client/bower.json
client/gulpfile.js
client/package.json
client/www/index.html

#1349
update cordova-plugin-inapppurchase
add ec6-promise

add ec6-promise for in app purchase on android 4.4.x

---

client/www/index.html
client/www/js/app.js
client/www/js/controller.guidectrl.js
client/www/js/controller.searchctrl.js
client/www/js/controller.start.js
client/www/js/service.twads.js
client/www/js/service.util.js
client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json
client/www/templates/start.html
client/www/templates/tab-search.html

#1476
starting page 생성
searchWord -> search.word on tab-search.html
guideVersion -> startVersion
remove guideVersion in controller.guidectrl
modify adsbanner color

starting page

---

client/www/js/app.js
client/www/js/controller.tabctrl.js

fixed height of tab on iOS

---

client/www/js/controller.forecastctrl.js

fixed error when variable undefined

---

server/lib/lifeIndexKmaRequester.js

#1440 #1439
provider 쪽에서 대소문자 변경이나, 문자 & 숫자 타입 변경에 러프하기 때문에 비교도 러프하게 변경.

returnCode check시에 type안봄.

---

server/lib/kmaScraper.js

#1317 #1315
데이터가 변경되기 때문에 동일한 시간 데이터를 반복 업데이트함.

remove checking pubdate of stn hourly weather

---

server/controllers/controllerManager.js

#678
change update time of short
direct get data of keco, current

change update time of short

---

client/www/templates/tab-search.html

change location icon on search tab

---

client/www/js/controller.forecastctrl.js
client/www/templates/tab-dailyforecast.html
client/www/templates/tab-forecast.html
client/www/templates/tab-search.html

change icon name to icon code

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/gulpfile.js
client/package.json

show location off icon when location is disabled
fix some errors
starting page for new users

release 0.9.40

---

server/app.js
server/lib/kecoRequester.js
server/routes/v000001/routeGather.js

#937 #935
etc
fixed some error messages

fixed wrong name of log function

---

server/controllers/controllerPush.js

call wrong property name

---

android/res/values/strings.xml
client/gulpfile.js
client/package.json
client/resources/PushHandlerActivity.java

#1552
targetSDKVersion을 24이상으로 변경하기전까지 PushHandlerActivity.java를 복사해넣어야 함.
strings.xml에서 google_app_id 제거

fix push error

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/package.json

fix push lib
update plugin version

release 0.9.41

---

client/package.json
client/www/js/app.js
client/www/js/controller.tabctrl.js
client/www/js/service.push.js
client/www/js/service.util.js

add fabric

---

client/www/js/controller.forecastctrl.js
client/www/js/controller.purchase.js
client/www/js/controller.searchctrl.js
client/www/js/controller.settingctrl.js
client/www/js/service.push.js
client/www/js/service.twads.js
client/www/js/service.weatherutil.js
client/www/templates/tab-dailyforecast.html
client/www/templates/tab-forecast.html

http 관련 에러 처리 통일
purchase, twads 등 log 수정
fix warning

purchase, push 등 log 개선

---

android/res/values-de/apppreferences.xml
android/res/values-en/apppreferences.xml
android/res/values-ja/apppreferences.xml
android/res/values-zh-rCN/apppreferences.xml
android/res/values-zh-rTW/apppreferences.xml
android/res/values/apppreferences.xml
android/res/xml/apppreferences.xml

#1205 위젯 설정 기능을 앱 대신 위젯에서 제공하기
* 속성 설정 시 위젯 마다 처리되도록 AppPreference에 저장
- 추가된 파일 적용

#1205 위젯 설정 기능을 앱 대신 위젯에서 제공하기

---

client/www/js/service.weatherutil.js

#1568
length 길이 확인
country_name이 없는 경우 tracking

국내 위치인데 해외 날씨 요청되는 경우

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/package.json

(hot fix) fail to get country short name

release 0.9.42

---

server/controllers/controllerManager.js

#1541 #678
life index 잘못 주석 처리된 부분 수정

life index 잘 못 주석 처리됨

---

server/controllers/controllerShortRss.js
server/controllers/controllerTown.js
server/models/town.js

- Fail to save when the same coordinate is in the array of mCoord.
: compare and remove same mx, my from array before requesting ShortRss.
: fixed list index, only use list[0] data.

#738 fixed fail to save

---

ios/TodayWeather.xcodeproj/project.pbxproj
ios/TodayWeather/TodayWeather-Info.plist
ios/TodayWeather/config.xml
ios/frameworks.json
ios/ios.json
ios/watch Extension/Assets.xcassets/Complication.complicationset/Circular.imageset/Contents.json
ios/watch Extension/Assets.xcassets/Complication.complicationset/Contents.json
ios/watch Extension/Assets.xcassets/Complication.complicationset/Extra Large.imageset/Contents.json
ios/watch Extension/Assets.xcassets/Complication.complicationset/Modular.imageset/Contents.json
ios/watch Extension/Assets.xcassets/Complication.complicationset/Utilitarian.imageset/Contents.json
ios/watch Extension/ExtensionDelegate.swift
ios/watch Extension/Info.plist
ios/watch Extension/InterfaceController.swift
ios/watch/Assets.xcassets/AppIcon.appiconset/Contents.json
ios/watch/Base.lproj/Interface.storyboard
ios/watch/Info.plist
ios/widget/TodayViewController.m
ios/widget/TodayWeatherShowMore.h
ios/widget/TodayWeatherShowMore.m
ios/widget/WidgetConfig.h

* [iOS][widget] 미세먼지 수치 및 지수 색 추가 #1536
* 미세먼지 지수 색 변경, 네이버 색 차용
* 미세먼지 수치 추가
* [iOS][widget] 통합대기부분이 영어로 뜨는 이슈 #1570
* 통합대기 지수 영어로 나오는 이슈 fix
* apple watch app2 제작 #1196
* watch target 추가
* 글로벌에서 강수확률 0일때 예외사항 추가 처리

미세먼지 수치 및 지수 색 추가, 통합대기부분이 영어로 뜨는 이슈, watch target 추가

---

client/www/js/controller.start.js

log event 수정

---

client/www/js/controller.purchase.js
client/www/js/service.push.js

#1582 #1245 #1254 #1561
set account level when in-app-purchase is unplugined
fix param of http success #1561

not set account level when in-app-purchase is unused

---

ios/TodayWeather.xcodeproj/project.pbxproj

#1545 #1322
update project.pbxproj

fix ios build failed by project.pbxproj

---

client/gulpfile.js

#1573 #1560
remove prepare only for android
etc
add build_ios

fix build fail when it builds iOS

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/gulpfile.js
client/package.json

new widget setting
etc
fix version of phonegap-plugin-push, cordova-ios, cordova-android
remove targetSdkVersion

release 0.9.25

---

server/lib/kecoRequester.js

#1601
retry get when it fail to get all ctprvn

Fail to get all ctprvn

---

client/gulpfile.js
client/package.json

#1598
downgrade push plugin for iOS
remove fabric in package.json

iOS build error

---

client/www/js/controller.tabctrl.js

#1594
check isAndroid when fail get address info

show wrong popup when fail get address info

---

client/www/js/app.js
client/www/js/service.util.js
client/www/js/service.weatherutil.js
client/www/tw.client.config.js

#1587
support multi key
save key list for native widgets

geo -> address query limit over

---

client/config-androidsdk19.xml
client/config.xml

for the larger aspect ratio

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/package.json

#1508 #1612
remove cordova-config-utils
new cordova-plugin-todayweather-config

config.xml에 ratio 관련 값 넣으니 빌드에러 발생

---

server/controllers/controllerTown.js
server/controllers/lifeIndexKmaController.js

간헐적으로 다른 언어로 데이터 전송되는 문제

---

server/bin/www
server/package.json

upgrade APM

---

server/controllers/worldWeather/controllerWorldWeather.js

#1622
finish when receive get invalid geocode

ww/010000/current/2 에러

---

server/package.json

4.6.8에서 연결이 끊어지는 문제 있음.

---

server/bin/www
server/package.json

remove whatap

---

server/controllers/controllerTown.js

#1621
pubDate는 이전날 18시가 최종으므로, 오늘부터 하면 안되고 pubdate 기준으로 해야함.
land와 temp의 pubDate가 다른 경우(gathering failed) 대비 적용
과거 데이터가 있는 경우에만 과거 데이터 채움.

start date of item from pubDate

---

client/package.json

#1617
set platform-android to 5.1.1

version code error

---

client/www/js/controller.forecastctrl.js

#1508
support aspect ratio 2:1

S8,.. aspect ratio 2:1

---

ios/TodayWeather/TodayWeather-Info.plist
ios/widget/Base.lproj/Info.plist
ios/widget/TodayViewController.h
ios/widget/TodayViewController.m
ios/widget/TodayWeatherUtil.h
ios/widget/TodayWeatherUtil.m

* [iOS][widget] multi service key for daum #1611
* 다음키를 멀티키로 사용하게 로직 추가, retry 로직 추가
* [0.9.48][iOS][widget] 업데이트 타임 오류 #1614
* Livetime 이 우선되게 수정

multi service key for daum and update time issue

---

server/lib/AQI/aqiRequester.js
server/lib/DSF/dsfRequester.js
server/test/testAQI/testAqiRequester.js

- added AQI lib
- fixed typo from self to req.

#1632 AQI lib API

---

server/routes/v000705/receiptValidation.js

#1210
j3k0에서 들어오는 POST도 사용할 수 있게 data mapping code 추가

support receipt of j3k0 plugin

---

client/www/js/app.js
client/www/js/controller.j3k0.purchase.js

#1210
기존이랑 file link를 교체하는 방식으로 두개의 purchase를 ios, android로 분리해서 사용할 예정임

new j3k0 purchase for android

---

server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerRequester.js
server/controllers/worldWeather/controllerWorldWeather.js

- router uses response data comes from requester.
: Before applying this issue, router uses data which is read from DB.

#1290 requester send back result data.  

---

server/controllers/controllerTown24h.js

set max length of dailyData

---

server/controllers/controllerKmaStnWeather.js
server/controllers/controllerManager.js
server/controllers/controllerTown.js
server/lib/kmaScraper.js
server/lib/kmaTimeLib.js
server/models/modelHealthDay.js
server/models/modelKmaStnHourly2.js
server/models/modelKmaStnInfo.js
server/models/modelKmaStnMinute2.js
server/models/modelMinuDustFrcst.js
server/test/testKmaStnHourlies2KmaStnHourly2.js
server/utils/kmaStnHourlies2kmaStnHourly2.js

#1480
new convertDateToYYYYoMMoDDoHHoMM
task-based scraping
etc
update comment in modelMinuDustFrcst.js
update indexing info in modelKmaStnInfo.js
fixed indexing info in modelHealthDay.js

new modelKmaStnHourly2, modelKmaStnMinute2

---

ios/TodayWeather.xcodeproj/project.pbxproj
ios/widget/TodayViewController.m
ios/widget/TodayWeatherShowMore.m
ios/widget/TodayWeatherUtil.m

* JSONObjectWithData:options:error 에러 fix
* substringToIndex 이슈 fix

* [0.9.49][iOS] 충돌 #1637

---

server/controllers/worldWeather/controllerWorldWeather.js

set status to 400 when invalid parameters

---

server/controllers/worldWeather/controllerAqi.js
server/controllers/worldWeather/controllerKeys.js
server/controllers/worldWeather/controllerRequester.js
server/lib/AQI/aqiRequester.js
server/models/worldWeather/modelAqi.js

- Added AQI controller.
- fixed simple bugs.
NOTE : AQI module, it doesn’t run yet.

#1632 Aqi controller

---

server/controllers/controllerManager.js
server/lib/kmaScraper.js
server/routes/v000001/routeGather.js

#1480
etc - fix missed param in save

get stn hourly weather in scrape mode

---

server/controllers/controllerPush.js

remove requestKeepMessage

---

server/controllers/controllerKmaStnWeather.js

#1640 #1480
use  stnHourly2, stnMinute2

fix stnHourly

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/package.json

fix iOS widget
fix save service keys

release 0.9.51

---

client/www/locales/de.json
client/www/locales/ja.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json

update de, ja, zh-CN, zh-TW

---

client/www/js/service.util.js

좌표-주소 변환 키 저장 오류

---

server/controllers/controllerKmaStnWeather.js
server/controllers/controllerTown.js
server/controllers/route.test.controller.js
server/routes/v000803/index.js
server/routes/v000803/route.test.js

#1480
sort after find of new model2
new getStnHourlyAndMinRns instead of getStnCheckedMinute
new route.test.js

stnHourly2 and stnMinute2 결과 검토 및 오류 수정

---

server/controllers/controllerManager.js
server/lib/kmaScraper.js
server/lib/kmaTimeLib.js
server/models/modelKmaSpecialWeatherSituation.js
server/test/testKmaScraper.js

#100
get, parse, save Special weather report KMA

scrape Special weather report KMA

---

server/controllers/controllerTown.js

- Even though there is no areaNo from Town list, it would find health
data by using geocode.
- Modified log level.

#1512 fixed bug and log level

---

ios/widget/TodayViewController.m
ios/widget/TodayWeatherShowMore.h
ios/widget/TodayWeatherShowMore.m
ios/widget/TodayWeatherUtil.h
ios/widget/TodayWeatherUtil.m

* [0.9.50] iOS Widget image 깨져보이는 이슈 #1654
* 이미지 깨지는 이슈를 수정함
* [iOS][widget] 미세먼지 보통 색 잘 안보임 #1659
* 녹색의 명암을 어둡게 하여 시인성이 좋게 RGB 값 수정

Changed green color value for air condition, fixed image anti-aliasing issue

---

server/lib/kmaScraper.js

#100
check preliminary special is empty
check to valid weather information

fail to parse when weather information is empty

---

server/config/config.js
server/controllers/controllerPush.js

use serviceServer

---

server/routes/v000803/index.js
server/routes/v000803/route.nation.js

new endpoint nation/SouthKorea

---

server/lib/kmaScraper.js

발표 시간 기준으로 변경

---

server/lib/unitConverter.js

log level 수정

---

server/controllers/worldWeather/controllerAqi.js
server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerRequester.js
server/controllers/worldWeather/controllerWorldWeather.js
server/models/worldWeather/modelAqi.js
server/routes/worldweather/routeWeather.js

- Added AQI data sending to client
: aqi would be added to ‘ThisTime’
- Changed geo format on model AQI

#1632 Added AQI

---

server/controllers/controllerKmaStnWeather.js

#1480
new _checkPrecipFromStnMinuteList

new checkPrecipFromStnMinuteList

---

server/lib/kmaScraper.js
server/models/modelKmaSpecialWeatherSituation.js

#1671 #100
getAWSWeather 시에 에러 발생하는 경우 1000ms 간격 10회 시도
1개의 예비특보, 특보에 여러개 시간, 지역이 가능하게 수정

kma scraping에 관해 몇가지 수정

---

server/controllers/controllerPush.js

#819 #181
tw-service의 부하를 줄이기 위해 mapSeries로 변경.

push 를 순차 실행으로 변경.

---

server/controllers/controllerTown.js
server/controllers/kecoController.js

#1679
update getDustFrcst to or query
fixed wrong date

too late minudustfrcsts toArray

---

client/www/js/controller.start.js

wrong action when fail to get current position on start page

---

client/www/js/controller.purchase.js
client/www/js/service.push.js
client/www/js/service.run.js
client/www/js/service.util.js
client/www/js/service.weatherutil.js
server/routes/v000705/index.js
server/routes/v000803/index.js
server/routes/worldweather/routeRequester.js

1672 add uuid on http headers

---

server/lib/kmaScraper.js
server/package.json

update async version

---

server/controllers/controllerManager.js
server/controllers/controllerTown.js
server/controllers/kasi.riseset.controller.js
server/controllers/kecoController.js
server/lib/kmaTimeLib.js
server/models/modelKasiRiseSet.js
server/routes/v000001/routeGather.js
server/routes/v000803/route.test.js
server/routes/v000803/routeTownForecast.js
server/test/testKasiRiseSetController.js

#482
new gatherAreaRiseSetFromApi
new getRiseSetInfo
etc
fixed wrong check dust forecast list
fixed error when data invalid
check error about dust forecast

gather sunrise, sunset and moonrise, moongset for kasi

---

server/controllers/controllerTown.js
server/routes/v000705/index.js
server/routes/v000803/index.js

#1678
logging user-agent
reordering when town's order was incorrect

지역 정보가 뒤집어져 있을 경우 재조정

---

server/controllers/worldWeather/controllerAqi.js
server/controllers/worldWeather/controllerWorldWeather.js
server/lib/AQI/aqiRequester.js

#1632 
- fixed hang-up issue
: When it can’t receive AQI data from provider, it would be hang-up.

#1632 fixed bug - hangup

---

server/lib/kmaScraper.js

recall callback

---

server/config/config.js
server/controllers/worldWeather/controllerCollector.js

#1689
catch error at parsing dsf

add key array in config.js

---

server/controllers/worldWeather/controllerAqi.js
server/controllers/worldWeather/controllerWorldWeather.js
server/models/worldWeather/modelAqi.js

#1632 
- Added iaqi data to db and response it to client

#1632 Added iaqi data

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/package.json

Improve search current location
Improve error of widget update

release 0.9.52

---

ios/widget/TodayViewController.m
ios/widget/TodayWeatherShowMore.m

* [iOS][native][widget] build error #1702

---

server/controllers/worldWeather/controllerWorldWeather.js

#1632 
- Added string of air level

#1632 added string of air level

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/package.json

android only
Fixed crash when network is invalid.
Fixed crash when weather data is wrong.

release 0.9.53

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/package.json

iOS only
위젯 이미지 개선
위젯 대기정보 폰트 컬러 조정

release 0.9.54

---

server/controllers/kecoController.js

- added who unit
: client can query with “?aqi=airkorea_who” when client needs WHO unit.

#1699 added who unit

---

server/controllers/kecoController.js
server/controllers/worldWeather/controllerWorldWeather.js

- prevent server killed by no timezone return from google.

#1710 prevent server killed.

---

server/controllers/controllerTown.js
server/controllers/worldWeather/controllerWorldWeather.js

fix js error

---

server/controllers/controllerManager.js
server/lib/kmaScraper.js

remove saving kmaStnHourly and kmaStnMinute

---

server/controllers/controllerTown.js

#1725 #1727 
현시간 기준 다가올 3,6,9,..시간이나 다음 3시간 시간대 데이터를 업데이트 하기 위해서 2시간전 shortest data를 사용함.

shortest merge error

---

server/controllers/controllerTown.js
server/controllers/kecoController.js
server/controllers/worldWeather/controllerWorldWeather.js
server/test/testKecoController.js

- support all kinds of aqi unit on the both korea query and world query

#1710 support all aqi unit

---

server/controllers/controllerTown.js
server/controllers/kecoController.js
server/controllers/worldWeather/controllerAqi.js
server/controllers/worldWeather/controllerRequester.js
server/controllers/worldWeather/controllerWorldWeather.js
server/test/testKecoController.js

- If it’s failed to get timezone by geocode directly, it would get
address and then get timezone by using address.

#1710 getting timezone by using address

---

ios/TodayWeather.xcodeproj/project.pbxproj
ios/widget/Base.lproj/Info.plist
ios/widget/Base.lproj/InfoPlist.strings
ios/widget/Base.lproj/Localizable.strings
ios/widget/Base.lproj/MainInterface.storyboard
ios/widget/TodayViewController.m
ios/widget/TodayWeatherShowMore.m
ios/widget/de.lproj/InfoPlist.strings
ios/widget/ja.lproj/InfoPlist.strings
ios/widget/ko.lproj/InfoPlist.strings
ios/widget/zh-Hans.lproj/InfoPlist.strings
ios/widget/zh-Hant.lproj/InfoPlist.strings

* [iOS][widget] 지역명 / 위젯타이틀 다국어 에러 #1636

---

server/controllers/controllerManager.js

#1731 #1728
overwrite all shortest data
adjust gather time of current, shortest, short

overwrite all shortest data

---

client/scss/ionic.app.scss
client/www/index.html
client/www/js/app.js
client/www/templates/tab-search.html

#1718 즐겨찾기 배경색 제거
* HeaderBar, Tabs 색상 변경
* 즐겨찾기 페이지의 배경색 제거 및 텍스트, 이미지 색상 변경

#1718 즐겨찾기 배경색 제거

---

server/controllers/controllerKmaStnWeather.js

#653 #1677
true if more then one station detects within 10 mins

Update precip method

---

server/controllers/controllerTown.js

check length of filterdList

---

client/config-androidsdk14.xml
client/config-androidsdk16.xml
client/config-androidsdk19.xml
client/package.json

add settings, refresh buttons on widget

release 0.9.56

---

client/www/templates/tab-forecast.html

#1721 대기정보 단위 오류
* 시간별 날씨의 오존, 이산화질소, 일산화탄도, 아황산가스의 단위를 ppm으로 변경

#1721 대기정보 단위 오류

---

server/controllers/controllerManager.js
server/lib/DSF/dsfRequester.js
server/test/testDSF/testDsfRequester.js
server/test/testInvalidt1h/testInvalidt1h.js

- If there is invalid t1h on the previous current data in the DB, it
would be re-request to update it.
- DSF request will retry if it receives wrong format of JSON.
#1748 #1751

#1748 invalid t1h

---

client/www/index.html
client/www/js/controller.settingctrl.js
client/www/js/service.run.js

* SettingCtrl에서 Util.version을 $scope.version에 설정하지 않고 getVersionNumber()로 버전 정보를 가져오면 $rootScope.version에 설정하도록 변경
*  Version의 TextColor를 검은색으로 변경
#1754

#1754 좌측 메뉴에서 버전이 표시되지 않는 문제

---

client/www/js/controller.searchctrl.js
client/www/js/service.push.js

#1580
check validation of location info

prevent to upload wrong alarm

---

client/www/js/app.js

* 어제의 현재온도 경우에만 반올림한 온도로 원을 표시하는 문제 수정
- 텍스트만 반올림하여 표시하고 원은 실제 온도 기준으로 표시되어야 함

#1729 어제온도 표기 오류

---

ios/TodayWeather.xcodeproj/project.pbxproj
ios/en.lproj/InfoPlist.strings
ios/widget/en.lproj/Info.plist
ios/widget/en.lproj/InfoPlist.strings
ios/widget/en.lproj/Localizable.strings

- main 앱과 widget에 base와 동일한 english 추가

* [iOS] app store에서 지원언어에서 영어 표시 안됨. #1723

---

client/gulpfile.js
client/package.json

#1763 #1760
move app-preferences to gulpfile.js for building ios

fixed play-services in plugins

---

server/controllers/controllerManager.js
server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerWorldWeather.js
server/package.json
server/routes/v000001/routeGather.js
server/test/testInvalidt1h/testInvalidt1h.js

#1752 changed log level

---

server/config/config.js
server/controllers/controllerManager.js
server/controllers/controllerTown.js
server/controllers/kma/kma.town.current.controller.js
server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerWorldWeather.js
server/models/kma/kma.town.current.model.js
server/package.json
server/routes/v000001/routeGather.js
server/test/testInvalidt1h/testInvalidt1h.js
server/utils/convertDbForm.js

- improve town current DB struct
#1768

#1768 improve DB struct

---

client/www/js/app.js

#1720 정각에서 표시 오류
* 3시간 단위의 정각인 경우에는 Data에 CurrentWeather를 추가하지 않도록 해서 정각에만 표시되도록 함
- 서버에서 t1h와 정각의 온도를 동일하게 보정해줘야 함

#1720 정각에서 표시 오류

---

client/www/index.html

#1773
adding viewport-fit=cover to viewport meta tag

fix iOS 11 statusbar issue

---

ios/widget/TodayViewController.m

- 시작시에는 기존 상태(더 보기 or 간략히 보기) 상태를 유지하기 위해 init시 setContentSize 제거
- showMoreView 를 Compact/Expanded에 따라 hidden YES/ NO로 수정함
#1758

* [app][iOS][widget] iOS 11에서 오류가 발생하는 경우가 있음. #1758

---

server/config/config.js

fix error of parsing config.js

---

server/controllers/controllerManager.js

update log message in _checkInvalidt1h

---

server/lib/DSF/dsfRequester.js

prevent-duplicate-call-callback

---

server/lib/lifeIndexKmaRequester.js

parse legacy api response

---

server/controllers/kasi.riseset.controller.js

set official service key

---

client/scss/ionic.app.scss

fix align of search-header input

---

.travis.yml
server/controllers/controllerTown.js
server/lib/collectTownForecast.js

#1789
etc
version up of node on travis

check valid of midTemp

---

client/scss/ionic.app.scss
client/www/js/controller.start.js
client/www/templates/start.html

#1578 검색 취소 기능
* Start Page의 검색 Input에 텍스트가 입력되면 우측에 취소 버튼 보이도록 추가
* 취소 버튼 누르면 검색어 삭제되고 검색 결과도 지움

#1578 검색 취소 기능

---

client/scss/ionic.app.scss
server/controllers/controllerManager.js
server/controllers/controllerTown.js
server/controllers/kma/kma.town.short.rss.controller.js
server/controllers/kma/kma.town.shortest.controller.js
server/lib/kmaTimeLib.js
server/models/kma/kma.town.current.model.js
server/models/kma/kma.town.short.model.js
server/models/kma/kma.town.short.rss.model.js
server/models/kma/kma.town.shortest.model.js
server/test/kma.town.db2.0/kma.town.db2.0.js
server/test/testShortRss.js
server/utils/convertDbForm.js

- Added new format of town.short.rss, town.shortest

#1768 Added new format of town.short.rss, town.shortest

---

server/controllers/controllerTown.js
server/controllers/lifeIndexKmaController.js

#1795
add translate param for converting string
new grade of decomposition index, heat index, frost, freeze

modify grade of discomfort index

---

client/www/js/service.weatherutil.js

error handling for getGeoCodeFromGoogle in getGeoInfoFromGeolocation

---

client/scss/ionic.app.scss
client/www/index.html
client/www/js/controller.forecastctrl.js
client/www/js/controller.settingctrl.js

#1788 특정 시간 마다 자동으로 날씨 업데이트 기능 추가
* 설정 메뉴에 "업데이트 주기" 항목 추가
- 수동, 30분, 1시간, 3시간, 6시간, 12시간 설정 가능
- localStorage에 설정 값 저장
* 업데이트 주기 설정 값이 변경되거나 시간별날씨/일별날씨 화면으로 이동 시 Timer 설정
* 시간별날씨/일별날씨 화면에서 나가는 경우 Timer 중지

#1788 특정 시간 마다 자동으로 날씨 업데이트 기능 추가

---

server/config/config.js
server/package.json
server/routes/v000705/receiptValidation.js
server/test/e2e/test.receipt.validation.js

use Google Play Store API to check the state of a subscription

---

client/www/js/controller.forecastctrl.js

#1777
delay when indicator is hiding

Fail to redraw when app is starting

---

client/www/locales/de.json

update "LOC_ENTER_CITY" on de.json

---

server/controllers/controllerManager.js
server/controllers/kasi.riseset.controller.js

gather 18days sun set/raise from kasi

---

server/lib/kecoRequester.js

warn in case of 503

---

server/routes/v000705/receiptValidation.js
server/test/testConvertAddress.js

check expire-date

---

server/controllers/worldWeather/controllerWorldWeather.js

try catch when it failed to get info

---

server/lib/kecoRequester.js
server/lib/kmaScraper.js
server/lib/kmaTimeLib.js
server/test/testKecoRequester.js
server/test/testKmaScraper.js

remove data 10 days ago

---

server/lib/kecoRequester.js

fix unmodified code

---

server/controllers/controllerPush.js
server/test/testControllerPush.js

try catch for makePushMessage

---

server/lib/kecoRequester.js

prevent 503 error of airkorea

---

server/controllers/worldWeather/controllerWorldWeather.js

return 19, when weatherStr is 'possible light rain'

---

client/config-androidsdk16.xml
client/config-androidsdk20.xml
client/config.xml
client/gulpfile.js
client/package.json

#1828
use crosswalk on android 19
upgrade cordova-android, crosswalk

좌우 스크롤 오류 on android 4.4

---

client/config-androidsdk14.xml
client/config-androidsdk16.xml
client/config-androidsdk20.xml
client/config.xml
client/gulpfile.js
client/package.json

corodva-android, crosswalk version up

release 0.9.62

---

server/test/testKecoRequester.js
server/test/testKmaScraper.js

remove connecting db on test

---

server/controllers/worldWeather/controllerWorldWeather.js

return 33, when weatherStr is 'possible light snow'

---

client/package.json
client/www/js/controller.searchctrl.js
client/www/js/controller.start.js
client/www/js/service.util.js
client/www/js/service.weatherutil.js
client/www/tw.client.config.js

first check from daum, use key when state is OVER_QUERY_LIMIT

---

server/.ebextensions/01_add_cors.config
server/app.js
server/package.json

#818
add cors setting to nginx
add cors setting to node.js

support cors

---

server/controllers/controllerManager.js

update gathering time of current, shortest, short

---

server/controllers/geo.controller.js

update parser of google address

---

client/scss/ionic.app.scss
client/www/js/controller.searchctrl.js
client/www/templates/tab-search.html

#1836
translate완료후에 init하게 수정
긴 도시명 "..."로 표시
location icon position 조정
current position enable시에 현재위치 날씨 업데이트 시도하게 변경

fix did not display current location in current language

---

client/scss/ionic.app.scss

fix scrolling-x on daily, houlry

---

client/www/js/controller.searchctrl.js
client/www/js/service.weatherutil.js

#1831 #1474
에러 메시지 오류 수정
google 받은 주소 정보를 단위로 분리해서 거기서 name 및 addres르 가지고옴
daum과 google로 받는 순서 및 데이터 수정.

fix fail to get address from google after failing to get from daum

---

server/controllers/airkorea.dust.image.controller.js
server/lib/airkorea.finedust.image.parser.js
server/test/testImageParser/testAirkoreaImageParser.js

#716
: It can extract dust value from image which is provided by air korea.

#716 added dust parser controller

---

server/controllers/controllerTown.js
server/controllers/geo.controller.js
server/test/testGeoController.js

#1678
google api를 사용하여 주소 복원해서 사용

"분당구/성남시/KR" 로 들어오면 "경기도/성남시분당구"로 변경

---

server/controllers/controllerKmaStnWeather.js
server/controllers/controllerTown.js
server/controllers/controllerTown24h.js
server/controllers/worldWeather/controllerWorldWeather.js
server/lib/kmaScraper.js
server/models/modelCurrent.js
server/routes/v000803/route.geo.js
server/routes/v000803/routeTownForecast.js
server/test/testControllerTown.js

#1061
new weather type 65,66 for converting weather(description)
update weather by pty of stn weather
update mid temp by temp of stn weather

update weather, mid temp by data of aws stn weather,

---

server/controllers/geo.controller.js
server/test/e2e/test.e2e.geo.controller.js
server/test/testGeoController.js

#1646
country 존재여부, kma address 존재여부, address 존재여부, name 존재여부
위 체크사항에 따라 외부 api에 요청
new e2e test

get params 시나리오 변경

---

server/controllers/worldWeather/controllerWorldWeather.js

changed value of air grade
: from IAQI value to grade(1~6)

#1699 changed value of air grade

---

server/controllers/worldWeather/controllerAqi.js
server/lib/AQI/aqiRequester.js

#1881
try,catch for JSON.parse
warning log for fail to get api data

try,catch for JSON.parse()

---

server/lib/lifeIndexKmaRequester.js

miss call wrong variable

---

client/gulpfile.js
client/package.json
client/www/index.html

#1866 #1868 #1865
gulp-minify-css to gulp-clean-css
remove gulp-concat
update cordova-uglify to 0.3.0 this version don't support image compression.
remove libs it's for old cordova-uglify

remove libs unused

---

client/www/js/controller.forecastctrl.js
client/www/js/service.weatherinfo.js
client/www/js/service.weatherutil.js

Separate location and weather updates.

---

server/controllers/worldWeather/controllerAqi.js
server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerWorldWeather.js

#1752 adjusted log level

---

server/config/config.js
server/controllers/controllerManager.js
server/controllers/kecoController.js
server/lib/kecoRequester.js
server/models/modelMinuDustFrcst.js
server/test/e2e/test.e2e.keco.requester.js
server/test/testKecoRequester.js

support RltmMesureDnsty version 1.3

---

server/lib/kmaScraper.js
server/utils/convertGeocode.js

#1900
add url info in error log in convertGeocode
code out unsed functions
fix warning

update kma aws stn info for isCityWeather field

---

client/www/js/app.js
client/www/js/controller.guidectrl.js
client/www/js/controller.purchase.alexdisler.js
client/www/js/controller.purchase.j3k0.js
client/www/js/controller.start.js
client/www/js/controller.units.js
client/www/js/service.push.js
client/www/js/service.storage.js
client/www/js/service.twads.js
client/www/js/service.util.js
client/www/js/service.weatherinfo.js
client/www/js/service.weatherutil.js

fix refer to wrong variable

---

server/app.js

add health check url

---

server/package.json

remove mem limit

---

server/models/modelKmaStnHourly.js
server/models/modelKmaStnHourly2.js

update description about rns1h, rns1d of KMA AWS

---

server/controllers/controllerTown.js

fix wrong parameter of updateWeather

---

server/controllers/airkorea.dust.image.controller.js
server/controllers/controllerTown24h.js
server/test/testImageParser/testAirkoreaImageParser.js

Change format of dust forecast for client.
Add function getting image url from DB
#716

Dust Forecast module

---

server/controllers/kma/kma.town.short.rss.controller.js

#1914
move callback to out of try catch
return after emitting recvFail

prevent callback was already called

---

server/controllers/worldWeather/controller.ww.units.js
server/test/test.controller.ww.units.js

time property string to number

---

.travis.yml

backend CD

---

client/www/js/controller.forecastctrl.js
client/www/js/controller.searchctrl.js
client/www/js/controller.start.js
client/www/js/service.weatherinfo.js
client/www/js/service.weatherutil.js

#1845
use backend string in $scope.getWeatherStr
use backend string for summary
remove _convertKmaWsdToStr, _makeSummary in forecastctrl
remove function for parsing data in weatherutil
getWorldWeatherInfo -> getWeatherByGeoInfo
getGeoInfoFromAddress -> getGeoInfoByAddr
getGeoInfoFromGeolocation -> getGeoInfoByLocation
use name, country, address, location from server when currentPosition is true at updateCity

use new api weather/coord, geocode/addr

---

client/www/js/controller.start.js

fix wrong popup to fail getting address info

---

client/www/js/controller.tabctrl.js

#1877
already push close button if type is search

fix ui error of popup window in search page

---

.travis.yml

update after_deploy in travis.yml

---

.travis.yml

check config.js in travis.yml

---

.travis.yml

git add config.js for release mode

---

server/controllers/kma/kma.town.short.rss.controller.js

call callback when self.RETRY in short.rss

---

server/controllers/controllerTown24h.js
server/routes/v000901/route.kma.addr.js
server/test/test.controller.town24h.js

#1903
make summary after converting units

update grade of dustForecast and summary

---

before_server_deploy.sh

remove before_server_deploy.sh

---

server/controllers/worldWeather/controller.ww.units.js
server/test/test.controller.ww.units.js

convert aqicn data to arpltn

---

server/routes/v000901/route.kma.addr.js

insert string after convert units

---

client/www/js/app.js
client/www/js/controller.forecastctrl.js
client/www/js/controller.units.js
client/www/js/service.weatherutil.js
client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json
client/www/templates/tab-dailyforecast.html
client/www/templates/tab-forecast.html
client/www/templates/units.html
server/locales/de.json
server/locales/en.json
server/locales/ja.json
server/locales/ko.json
server/locales/zh-CN.json
server/locales/zh-TW.json

#1740
remove unit convert code
remove grade to string

support airUnit

---

server/controllers/worldWeather/controllerAqi.js
server/controllers/worldWeather/controllerWorldWeather.js
server/models/worldWeather/modelAqi.js

check invalidate data of AQI
Add aqiValue
#1939

check invalidate data of AQI

---

server/controllers/worldWeather/controllerWorldWeather.js

fix wrong condition for checking invalid aqi

---

server/controllers/worldWeather/controller.ww.units.js

add datatime, station in arpltn

---

server/controllers/controllerKmaStnWeather.js
server/controllers/controllerTown.js

KMA의 일기(weather) 정보가 다른 언어로 변경 안되는 문제 수정

---

server/controllers/controllerTown24h.js
server/controllers/kecoController.js
server/controllers/worldWeather/controller.ww.units.js
server/lib/unitConverter.js
server/test/test.unit.converter.js
server/test/testKecoController.js

#1943 #1903
calculate aqi when aqi unit is airkorea, airkorea_who
if check preperty of some items before convert units
time of yesterday also changes to number

set grade if it has value in arpltn

---

server/controllers/controllerPush.js
server/test/testControllerPush.js

use v000901 api for push

---

server/controllers/controllerTown24h.js
server/lib/kmaTimeLib.js
server/test/test.controller.town24h.js

#1522
add night property to kma data
new func 2017.12.22 13:34 -> 1334

sunset,sunrise 정보에 따라 skyIcon 선정

---

ios/widget/TodayViewController.m

대기오염정보 안나오는 문제

---

client/www/templates/tab-forecast.html

check XXXValue before binding

---

client/www/js/controller.forecastctrl.js
client/www/js/controller.start.js
client/www/js/controller.tabctrl.js

#1507
iOS에는 switchToLocationSettings이 없어서 swtichToSettings로 대처

switchToLocationSettings를 잘못호출함.

---

client/www/js/controller.forecastctrl.js
client/www/templates/tab-dailyforecast.html
client/www/templates/tab-forecast.html

#1777
loading time에 chart가 짤려보이는 이슈가 있어 div로 변경함

ion-scroll to div

---

client/www/js/controller.forecastctrl.js

refreshInterval is not defined at setRefreshTimer

---

client/scss/ionic.app.scss
client/www/data/update.info.js
client/www/index.html
client/www/js/app.js
client/www/js/controller.settingctrl.js
client/www/js/controller.tabctrl.js
client/www/js/service.storage.js
client/www/js/service.util.js
client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json
server/locales/de.json
server/locales/en.json
server/locales/ja.json
server/locales/ko.json
server/locales/zh-CN.json
server/locales/zh-TW.json

#1713
update.info.js에서 정보를 읽어서 표시
버튼용 짧은 구문 추가
주의 : cordova.getAppVersion이 느림
sendMail(), openMarket() settingCtrl -> util
new data key 'disableUpdateInfo', 'appVersion'

new update information popup

---

server/lib/kmaScraper.js

#1964
remove '기상실황표' from pubDate

www.kma.go.kr -> www.weather.go.kr

---

client/www/js/service.util.js

fix Util.version is undefined

---

server/controllers/controllerPush.js
server/models/modelPush.js
server/test/e2e_local/test.e2e.controller.push.js
server/test/testControllerPush.js

push : kma source에서 geo가 있으면 town보다 우선 사용

---

client/www/js/controller.searchctrl.js
client/www/js/controller.units.js
client/www/js/service.push.js
client/www/js/service.weatherinfo.js
client/www/js/service.weatherutil.js

#1845 #1757
updateAlarm 호출전에 업데이트 필요여부 검토
#1757의 잘못된 예외처리 수정 -> time param은 외부에서 찾아서 전달(기존은 함수내에서 찾음) in updateAlarm
에러 예외 처리 in getWeatherByGeoInfo
잘못 삭제된 convertAddressArray 복원

update push when units are changed

---

client/www/js/service.push.js

Fix condition was wrong handled

---

client/www/js/controller.forecastctrl.js
client/www/js/service.weatherinfo.js
client/www/js/service.weatherutil.js
ios/widget/TodayViewController.m

#1971
기존 city data에 location 정보가 없으면 newCityInfo에서 추가
new _makeQueryUrlWithTown
iOS widget : api endpoint 수정

geoInfo.location 없는 경우 지원

---

server/controllers/controllerTown.js
server/controllers/controllerTown24h.js
server/controllers/kecoController.js
server/lib/unitConverter.js
server/test/test.controller.ww.units.js

#1978
unit이 (null)로 오는 경우 기본값으로 설정
airUnit 기본 값을 airKorea -> airkorea 변경 (대소 수정)
khaiUnit 변환시 대소 오류 수정
insertStr에서 airUnit이 airkorea로 덮어 씌워지는 문제 수정

v000901에서 aqi 관련 오류 수정

---

server/controllers/controllerHealthDay.js

#1982
연속 요청시에 error발생이 심하여, map -> mapSeries
today가 '*'로 오는 경우 예외처리

Prevent parsing error in HealthDayController.getData

---

server/lib/kmaScraper.js

set timeout request for kma scraping

---

server/controllers/controllerManager.js
server/controllers/controllerTown.js

summary 만들때, aqi grade 체크

---

server/controllers/worldWeather/controllerWorldWeather.js
server/test/e2e_local/test.e2e.controllerWorldWeather.js

set google_key for get address by geocode in world weather

---

ios/widget/TodayViewController.m

#1986 #1987
time을 문자열에서 숫자 지원으로 변경
source(KMA, DSF)를 사용하여 KR, Global 구분

processWeatherResultsWithShowMore 사용에서 제외

---

server/controllers/controllerPush.js
server/controllers/geo.controller.js
server/controllers/kasi.riseset.controller.js
server/controllers/kma/kma.town.short.rss.controller.js
server/lib/collectTownForecast.js
server/lib/kecoRequester.js
server/lib/kmaScraper.js
server/lib/midRssKmaRequester.js
server/package.json

#2003
cache dns for short rss, push, geo ctrl, kasi, collect town, keco, scrape, mid rss

dns cache what is used

---

ios/widget/TodayViewController.m
ios/widget/TodayWeatherUtil.m

#2005
저장된 city data는 index만 사용
받은 데이터가 없는 경우(오류) 예외처리

lat 0, lng 0인 경우 예외처리

---

server/controllers/worldWeather/controllerRequester.js
server/controllers/worldWeather/controllerWorldWeather.js
server/utils/convertGeocode.js

add google key for request googleapis

---

server/routes/v000803/route.nation.js

#739
update accept-language, query params

new city in national weather

---

client/scss/ionic.app.scss
client/www/templates/tabs-android.html

revert hide tab title

---

client/www/js/app.js
client/www/js/controller.searchctrl.js
client/www/js/controller.start.js
client/www/js/service.weatherutil.js
client/www/templates/tab-dailyforecast.html
client/www/templates/tab-forecast.html

#2018
etc
failToLoadAppVersion 는 에러가 아니므로 console로만 출력

url이 undefined 로 넘어가는 문제 수정

---

client/www/js/app.js
client/www/js/controller.searchctrl.js
client/www/js/controller.start.js
client/www/js/service.weatherinfo.js
client/www/js/service.weatherutil.js
client/www/templates/tab-dailyforecast.html
client/www/templates/tab-forecast.html

exception reload city

---

client/www/js/controller.forecastctrl.js

'substr' of undefined at applyWeatherData

---

client/www/js/service.weatherutil.js

geoinfo 추가 전에 parsed weather data가 null인지 확인

---

client/scss/ionic.app.scss
client/www/index.html
client/www/js/app.js
client/www/js/controller.nation.js
client/www/js/controller.settingctrl.js
client/www/js/service.weatherutil.js
client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json
client/www/templates/nation.html
server/locales/de.json
server/locales/en.json
server/locales/ja.json
server/locales/ko.json
server/locales/zh-CN.json
server/locales/zh-TW.json

#1856 #1170 #1140
globalization이 없으면, navigator.languages에서 region 정보 가져옴
new getNationWeather
retry 조정

new National weather page

---

server/controllers/controllerManager.js
server/controllers/kecoController.js
server/lib/kecoRequester.js
server/models/arpltnKeco.js
server/models/sido.arpltn.keco.model.js
server/routes/v000001/routeGather.js
server/test/e2e_local/test.e2e.keco.requester.js
server/test/testKecoRequester.js

#1896
remove xml2json
pm10Value24, pm25Value25추가
pm25Grade는 pm25Grade24로 변경(기존에 24시간 기준 grade가 pm25Grade에 저장)
새로운 pm25Garde1h를 pm25Grade에 저장
pm10Grade도 pm25Grade와 동일
date 항목 추가

KECO 시도별 실시간 측정정보 API 업데이트

---

server/controllers/worldWeather/controller.ww.units.js

thisTime array가 2개 아닌 경우 500 반환

---

server/controllers/controllerTown24h.js
server/routes/v000803/route.nation.js

version을 req object에 추가

---

server/lib/DSF/dsfRequester.js

lat나 lon이 0으로 오는 경우 허용하게 수정

---

server/controllers/controllerTown.js
server/controllers/geo.controller.js
server/routes/v000901/route.kma.addr.js

API v000901에서 "/KR" 로 오는 경우 보완하게 수정

---

server/controllers/controllerKmaStnWeather.js
server/controllers/controllerTown.js

#1061
aws stn weather가 존재하는 항목에 한해서 업데이트
mergeCurrentByStnHourly에서 aws stn hourly weather로 업데이트
getKmaStnMinuteWeather에서 aws stn minute weather로 업데이트
try catch 오류 수정 in getKmaStnMinuteWeather

aws stn weather로 날씨 정보 업데이트 오류 수정 및 정리

---

server/controllers/kecoController.js
server/lib/kecoRequester.js

#1896
미세먼지 데이터를 과거 10일까지 저장
주의 : tw-service에 수정사항이 먼저 적용되어야 함.

미세먼지 정보 가장 최근 것 하나 가지고 오는 것으로 수정

---

server/controllers/controllerTown.js
server/controllers/controllerTown24h.js
server/routes/v000901/route.kma.addr.js

#1971 #1678
"/KR"로 요청오는 경우가 많아서 client의 즐겨찾기 정보에 location을 추가하기 위함임.

kma/addr 요청에 location 정보도 추가

---

server/lib/kecoRequester.js
server/test/testKecoRequester.js

각 시도별 값의 평균 Object 추가

---

client/www/js/controller.tabctrl.js

#2029
updateInfo parser를 try로 쌈

prevent window.updateInfo.find is not a function

---

ios/widget/TodayWeatherShowMore.m
ios/widget/TodayWeatherUtil.m

#2061
time이 "0400"문자형에서 4로 숫자형으로 변경되면서 발생한 오류.
nssTime에 %02d로 숫자형 nTime을 넣는 것로 수정 in getByTimeArray
etc
지역이 한국이라고 한국어로 표기된 부분 수정 (추후 제대로 수정 필요)

시간별날씨 오류 수정

---

client/www/index.html
client/www/js/app.js
client/www/js/controller.setting.radio.js
client/www/js/controller.settingctrl.js
client/www/js/controller.units.js
client/www/templates/setting-radio.html
client/www/templates/units.html

units, startupPage, refreshInterval 설정을 새페이지에서 선택하게 수정

---

client/www/js/controller.start.js

log update for debugging

---

client/www/js/app.js

fav가 없는 경우(위젯에서 즐겨찾기 없이 들어오는 경우) forecast page로 가는 이슈 수정

---

client/www/js/controller.forecastctrl.js

#2049
API 변경후에 geoInfo 가지고 오는 부분 제거되어, log 설명도 수정
에러 발생한 이후에 return 안하는 부분 수정

update current position 이후에 저장된 location과 비교 개선

---

client/www/js/app.js

prevent read property 'tabsTop' of null

---

client/www/js/app.js

prevent call method 'lastIndexOf' of undefined

---

client/www/js/controller.forecastctrl.js
client/www/js/controller.searchctrl.js
client/www/js/service.push.js

#2056
etc
update log : searchctrl.js, push.js

applyWeatherData에서 에러 발생해도 다음 동작되게 개선

---

client/scss/ionic.app.scss
client/www/js/controller.nation.js
client/www/js/service.weatherutil.js
client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json
client/www/templates/nation.html
server/locales/de.json
server/locales/en.json
server/locales/ja.json
server/locales/ko.json
server/locales/zh-CN.json
server/locales/zh-TW.json

#1856
_getHttp에 timeout param 추가

전국날씨 강수, 풍량/풍속 정보 제공

---

client/www/js/service.weatherinfo.js

fix mistyping

---

client/www/js/controller.searchctrl.js

#2010
query string으로 description을 사용하지 않고, terms로 만든 문자열 사용

자동완성된 주소를 googleapis에서 못 찾는 문제

---

server/controllers/worldWeather/controllerWorldWeather.js

fix SyntaxError

---

server/lib/kmaScraper.js

#2075
getCityWeather에 date 정보 추가

도시별날씨 중에 서산(129) 못 찾는 문제

---

server/controllers/controllerTown24h.js

일별날씨에서 날짜 중복이 있는지 확인

---

server/controllers/controllerHealthDay.js

#257 #1447
etc
외부 서버에서는 Code(예 returnCode)는 데이타 타입이 변경될 수 있음

잘못된 indexType의 저장되는 문제

---

server/controllers/controllerTown24h.js
server/controllers/worldWeather/controller.ww.units.js

make summary aqi, weather

---

server/controllers/controllerHealthDay.js

health index 중에 하나가 에러나도 계속 진행

---

server/controllers/airkorea.dust.image.controller.js
server/controllers/kecoController.js

airkorea를 airnow로 바꿀때 오류

---

server/controllers/worldWeather/controllerWorldWeather.js

airnow grade 오류 수정

---

client/scss/ionic.app.scss
client/www/index.html
client/www/js/app.js
client/www/js/controller.air.js
client/www/js/controller.forecastctrl.js
client/www/js/controller.setting.radio.js
client/www/js/controller.settingctrl.js
client/www/js/controller.tabctrl.js
client/www/js/service.weatherinfo.js
client/www/js/service.weatherutil.js
client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json
client/www/templates/tab-air.html
client/www/templates/tab-dailyforecast.html
client/www/templates/tab-forecast.html
client/www/templates/tabs-android.html
client/www/templates/tabs.html
server/locales/de.json
server/locales/en.json
server/locales/ja.json
server/locales/ko.json
server/locales/zh-CN.json
server/locales/zh-TW.json

#1846
new controller.air, tab-air
TABLE_WIDTH를 640으로 맞춤
controller.forecastctrl와 controller.air가 같이 사용할 기능들은 tabctrl로 이동
unit 설정이 변경되었을때, 데이터 리로드함

new air info page

---

ios/widget/TodayViewController.h
ios/widget/TodayViewController.m
ios/widget/TodayWeatherUtil.m

- widget 지역변경시 지역명은 empty 처리 하지 않기
- server error code 처리

[iOS][widget] Widget 추가 개선 포인트 #2074

---

server/app.js
server/controllers/controllerPush.js
server/controllers/controllerTown24h.js
server/controllers/worldWeather/controller.ww.units.js
server/routes/v000902/index.js
server/routes/v000902/route.dsf.coord.v000902.js
server/routes/v000902/route.kma.addr.v000902.js

#1895
- new insertSkyIconLowCase, _parseSkyStateLowCase in controllerTown24
- new routes/v000902/index.js
- new routes/v000902/route.kma.addr.v000902.js
- new routes/v000902/route.dsf.coord.v000902.js
- skyIcon 값 넣어주는데서 변경하기 까다로워서 뒤에서 한번에 변경하게 수정함
- 습도아이콘은 아직 client에서 쓰지 않아서 바로 변경함

v000902 sky icon name in lowcase

---

server/app.js
server/controllers/airkorea.dust.image.controller.js
server/controllers/airkorea.hourly.forecast.controller.js
server/controllers/controllerTown24h.js
server/lib/kecoRequester.js
server/models/arpltn.hourly.forecast.js

#2089
17시 이후 데이터는 예보 날짜를 조정함.
new getDustImage -> imgPaths를 Param으로 전달
etc
msrStn information에서 location 정보가 잘못 된 경우가 있어서 보정함.

airkorea image -> parsing -> filter msr stn -> db

---

server/controllers/controllerTown24h.js
server/controllers/kecoController.js

#2096 #2089
측정된 미세먼지 정보 날짜는 24:00을 사용하기 때문에 hourly array만들때 00:00으로 변환
예보추가할때 비교 오류 수정

시간별 대기 예보 만들때 오류 수정

---

client/www/js/app.js
client/www/js/controller.searchctrl.js
client/www/js/controller.start.js
client/www/js/service.weatherinfo.js

#2097
load city 정보에서 country가 없더라도 그대로 유지함
#2002
Util.region에 KR은 버그임으로 수정함

기본 지역은 KR로 설정하는 부분 제거

---

client/www/templates/tab-forecast.html

khaiXXXX property name을 aqiXXX로 통일

---

server/controllers/worldWeather/controller.ww.units.js

unit name이 null로 오는 경우 예외처리 (at requesting dsf)

---

client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json
server/controllers/controllerTown.js
server/lib/aqi.converter.js
server/locales/de.json
server/locales/en.json
server/locales/ja.json
server/locales/ko.json
server/locales/zh-CN.json
server/locales/zh-TW.json

aqi grade에 따른 action guide 추가

---

server/controllers/controllerTown24h.js

#2082
과거데이터가 없고 예보만 있는 경우 빈데이터(측정정보 없음) 하나 추가하고, 예보 추가함

airInfo 과거데이터가 없는 예보가 있으면 보정처리

---

client/package.json

use cordova-plugin-ionic-webview

---

client/scss/ionic.app.scss
client/www/js/controller.tabctrl.js
client/www/locales/ko.json
server/locales/ko.json

#1713
main 14 -> 16px
checkbox 14->18px

update info 정보 폰트 크기 조정

---

client/www/js/controller.start.js

사용자가 현재 찾기하게 되면 바로 날씨정보를 가지고 오게 변경

---

server/controllers/controllerPush.js
server/models/modelPush.js
server/routes/v000705/routePushNotification.js
server/routes/v000902/index.js
server/routes/v000902/route.push.update.list.js
server/test/e2e_local/test.e2e.controller.push.js
server/test/e2e_local/test.e2e.route.push.update.list.js
server/test/testControllerPush.js

#1975
- new _getCurrentTime
- updatePushInfo호출시 updatedAt이라고 현재시간 속성 추가
- new _removeOldList
- 180일 이상 업데이트가 없는 push에 대하여 삭제
- new /v000902/push-list api
- new updatePushInfoList
- 여러개의 push 정보를 업데이트
#1443
- client에서 전달되는 location 정보 확인

pushInfo를 리스트 받아서 처리

---

server/controllers/controllerPush.js
server/lib/kmaTimeLib.js
server/models/modelPush.js
server/test/e2e_local/test.e2e.controller.push.js
server/test/testControllerPush.js
server/test/testKmaTimeLib.js

#1842
- new kmaTimeLib.toLocalTime
- new _filterByDayOfWeek in controllerPush
- test code는 날마다 결과가 달라서 e2e_local에 추가

new check day of week in push

---

client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json
server/controllers/alert.push.controller.js
server/lib/aqi.converter.js
server/locales/de.json
server/locales/en.json
server/locales/ja.json
server/locales/ko.json
server/locales/zh-CN.json
server/locales/zh-TW.json
server/models/alert.push.model.js
server/routes/v000902/route.push.update.list.js
server/test/e2e_local/test.e2e.alert.push.controller.js
server/test/e2e_local/test.e2e.route.push.update.list.js
server/test/test.alert.push.controller.js

#1701
- new alert.push.model, alert.push.controller, test.e2e.alert...
- aqi.converter
- new sortByGrade, name2string
- locales
- new 8 sentences for alert push
- update v000902/push-list
- new category(alarm, alert) in push info object

new alert push api

---

server/controllers/controllerPush.js

update key를 registrationId, id에서 registrationId, cityIndex로 변경

---

server/controllers/controllerPush.js

#2134
pushes colleciton에 강제로 id를 추가함.
id 기준으로 업데이트, 삭제함

fix wrong key

---

server/controllers/alert.push.controller.js
server/controllers/controllerPush.js
server/models/alert.push.model.js
server/models/modelPush.js
server/routes/v000705/routePushNotification.js

#2134
- 클라이언트에서 도시별로 id를 구분하게 되어 cityIndex별 id로 변경

push 데이터 구분을 type, registrationId, cityIndex, id 4개 합으로 구분

---

server/controllers/worldWeather/controllerAqi.js

adjusted log level

---

server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerWorldWeather.js

#2140
- request -> find -> save를 하는데 이전 save가 완료되지 않은 상태에서 find되면서 앞에 데이터 저장안됨
- yesterday가 없는 경우 빈 object를 만들어서 array에 오류가 없도록 함.

두 개를 순차적으로 request and save시에 데이터 없어지는 문제

---

server/routes/v000803/routeTownForecast.js

#2089 #2096
remove AirkoreaForecast in v000803/town

'last' of undefined at ControllerTown24h.AirkoreaForecast

---

server/controllers/controllerTown.js
server/controllers/controllerTown24h.js
server/controllers/kecoController.js

#2144 #2082
- make aqi object in getHourlyAqiData
- fix undefined query in getDustFrcst
#1512
- check areaNo in townInfo in getLifeIndexKma

fix some bugs at making AirInfo

---

server/controllers/controllerTown24h.js

대기 시간별 예보가 없는 경우 예외 처리

---

server/controllers/worldWeather/controllerWorldWeather.js

#2148
current 찾는 조건을 업데이트 시간이 1시간 이내인 경우로 변경

디비에서 해외 날씨 데이터 가지고 오는 경우 실패하는 문제

---

server/app.js
server/controllers/alert.push.controller.js

push mode일 떄 app.js에서 alert push 시작

---

server/controllers/controllerKmaStnWeather.js
server/controllers/controllerTown.js

update log info at getKmaStnMinuteWeather for read

---

client/www/js/controller.tabctrl.js

fix undefined summary of message for sharing

---

client/www/js/controller.forecastctrl.js
client/www/templates/tab-dailyforecast.html
client/www/templates/tab-forecast.html

summary을 weather와 air로 분리한다.

---

server/controllers/airkorea.hourly.forecast.controller.js

skip invalid geocode of station

---

server/controllers/alert.push.controller.js

#1701 #2132
$where에 들어가는 함수는 mongodb version에 따라 es6를 지원하지 않음.

fix MongoError: Failed to call method

---

client/www/js/controller.air.js
client/www/js/controller.forecastctrl.js
client/www/js/controller.tabctrl.js

#2121
loadWeatherData는 항상 콜되는 것이 아니라서
applyWeatherData에서 $scope.currentPosition 설정

location icon이 제대로 표시 안되는 문제

---

server/config/config.js
server/controllers/alert.push.controller.js
server/controllers/controllerPush.js
server/controllers/controllerTown24h.js
server/routes/v000803/route.nation.js
server/routes/v000902/index.js
server/routes/v000902/route.kma.v000902.js

#1701
- alert 반응이 느려(특히 미세먼지) tw-service를 직접 call함.
- new coord2addr()
- config.push.serviceServer -> config.apiServer or config.serviceServer

new /v000902/kma/coord/:loc

---

server/controllers/controllerPush.js
server/lib/kmaTimeLib.js

#1842 #2126
- date를 새로 생성하여 사용 in toLocalTime
- organize log in _filterByDayOfWeek

요일별 알림 오동작 수정

---

server/controllers/controllerTown.js

동네예보나, Weather(현재날씨의 일기)와 rns간의 보정 오류 수정

---

ios/widget/TodayViewController.m

+ iOS9을 쓰고 있는 기기에서는 위젯을 세팅하면 위젯이 비정상적으로 길게 출력이 됨 #2037
- ios9 버젼체크후 처리
+ [iOS][widget] 간략히 보기 일때 상세보기 화면이 겹쳐져서 나오는 이슈 #2173
- compact/expanded mode처리에서 상세보기 화면 enable/disable 제거처리

2173-2037-mixed-view-issue

---

client/www/js/controller.start.js

#1476
- 현재위치로 날씨보기와 사용자 혼돈이 있어 제거

remove find by location

---

client/www/js/controller.searchctrl.js

현재위치를 사용하는 경우 추가로 현재위치 업데이트 함.

---

client/www/js/controller.forecastctrl.js

미세예보 있는 지역에서 없는 지역 변경시 잘못된 미세예보표시 오류 수정

---

server/controllers/controllerKmaStnWeather.js

#2179
눈,비,눈싸라기의 경우 맑음/구름조금/구름많음/흐름으로 변경
뇌우의 경우 번개로 변경

rns(kma aws)에 의해 pty가 0이 되면 weather도 갱신

---

client/www/js/controller.searchctrl.js
client/www/js/controller.start.js

#2191
isLocationEnabled가 false일때도, isLocationAuthorized를 체크해서 조정
긴급 수정으로 추가 수정할 부분들이 있음.

위치권한요청 팝업에서 취소 버튼 누르면 무한 로딩하는 문제

---

client/www/templates/purchase.html
client/www/templates/start.html

modify margin for iPhone X

---

client/www/js/controller.air.js
client/www/templates/tab-forecast.html

#1846
- 오염물질의 value가 0이더라도 표시되게 수정 in 시간별날씨
- exception 방지 in 대기정보

prevent exception when pollutants obj is undefined

---

server/controllers/worldWeather/controllerWorldWeather.js

new aqi action guide in DSF api

---

server/controllers/worldWeather/controllerAqi.js
server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerWorldWeather.js
server/models/worldWeather/modelDSForecast.js

Changed time of using DB data from 1Hour to 15Min for Alram
re-use past DSF data
: if there are yesterday’s DSF data in the DB, it would use it
: if the last query is not 1 hour before,  today’s data which is from
0:00 can be used.
#2172

renew data every 15min for alram, re-use past DSF data,

---

client/scss/ionic.app.scss
client/www/templates/purchase.html
client/www/templates/start.html

#2192 #2193
- #2193 에서 수정된 margin 원래대로 돌리고, scss에서 보정하게 변경

margin for iphone x

---

server/controllers/controllerTown24h.js

동일한 요일 있는지 확인하는 코드 추가

---

server/controllers/alert.push.controller.js

#1701 #2130 
- 예보가 있는 경우가 아니라면 항상 현 날씨,대기 상황을 저장함
- 마지막 상태가 알림 미발생 상태일때만 알림전달 여부 체크함

alert 확정 시나리오 오류수정

---

ios/widget/TodayViewController.h
ios/widget/TodayViewController.m
ios/widget/TodayWeatherShowMore.m

+ [iOS][widget] iOS9을 쓰고 있는 기기에서는 위젯을 세팅하면 위젯이 비정상적으로 길게 출력이 됨 #2037 #TW-113
- iOS9 미세먼지 텍스트 컬러 이슈 수정

TW-113 iOS9 미세먼지 텍스트 컬러 이슈 수정

---

client/scss/ionic.app.scss
client/www/locales/ko.json

#1851
- 한국어 문구 개선
- alert swtich css 수정

setting-push UI 개선

---

server/config/config.js
server/lib/airkorea.finedust.image.parser.js

Moved pixel pos to config

---

server/controllers/alert.push.controller.js
server/controllers/controllerPush.js
server/locales/ko.json
server/test/e2e_local/test.e2e.controller.push.js

#1701
- 1시 미세먼지가 나쁨 -> 1시부터 미세먼지가 나쁨입니다.
- fix test error
- 3(+1)/4(-1) -> 최저3(+1) 최고12(+7)

TW-121 Push message 개선

---

server/controllers/controllerTown24h.js

- old api (v000803)에서는 dayOfWeek 설정을 하지 않음

TW-111 dayOfWeek이 undefined가 아닌지 확인

---

server/controllers/controllerTown24h.js

#1846
- air summary는 warn으로 변경

make summary error 분류

---

client/www/js/controller.push.js

기본 알람 시간 조정

---

server/controllers/controllerTown.js

- AWS의 의한 비 그침 기능 제한
- 이슬비,약한비,약진눈깨비가 아니고, AWS Time이 30분이상인 경우에만 비그침 사용

TW-92 이슬비에서 비확인안되는 문제

---

server/controllers/alert.push.controller.js
server/test/test.alert.push.controller.js

- shortest 2개 모두가 비예보가 있는 경우 비로 결정
- shortest가 1개만 있는 경우 그 값에 따름
- forecast는 실제로 전송하지 않고, log가 출력

TW-154 눈/비 예보 알림 결정 강화 & 예보는 전송하지 않고, 로그만 출력

---

server/config/config.js
server/controllers/controllerManager.js
server/controllers/controllerTown.js
server/routes/v000001/routeGather.js

- 도시별일기와 AWS RNS만 보고 current.pty는 무시

TW-92 current 데이터 오류로 pty가 1이 되는 문제

---

server/controllers/alert.push.controller.js

- find시에 _id제거해야함
- 동시 요청 갯수 10개로 제한
- alert push 나가는 경우 error출력(slack용)

TW-156 Mongodb Error

---

server/controllers/controllerManager.js
server/controllers/kma/kma.town.current.controller.js
server/controllers/kma/kma.town.short.controller.js
server/controllers/kma/kma.town.short.rss.controller.js
server/controllers/kma/kma.town.shortest.controller.js
server/lib/kmaTimeLib.js
server/lib/midRssKmaRequester.js

- current, short, shortest, short.rss를 DB 1.0, 2.0 동시 저장하게 변경
- current, short, shortest, short.rss의 과거 데이터는 한 번에 지우게 변경
- System 시간을 넣기 때문에 과거 9일 유지하게 수정
- mid[forecast, land, temp, sea], mid.rss DB1.0,2.0 동시저장

TW-58 KMA DB2.0

---

server/controllers/controllerKmaStnWeather.js
server/test/e2e_local/test.e2e.findNearAws.js

- 요청지역에서 10km이내의 AWS측정소를 사용하게 변경

TW-92 stn 갯수 조정

---

server/controllers/alert.push.controller.js
server/test/test.alert.push.controller.js

TW-20 대기경보에 대한 개선

---

server/controllers/alert.push.controller.js

- infoObj(weather data)에 name 있으면 사용
- town 정보 사용
- town 정보도 없다면 측정소 정보 표시

TW-161 alert push의 이름이 undefined 로 전달되는 문제

---

server/controllers/worldWeather/controllerWorldWeather.js

TW-152  Change checking time period from 1H to 15Mins

TW-152  Change checking time period from 1H to 15Mins

---

server/controllers/alert.push.controller.js

TW-165 current가 pty가 1이지만 도시별날씨, AWS모두 강수가 없는 경우

---

server/controllers/alert.push.controller.js

- shortest가 2개이상있고, 둘 다 pty가 1이상이어야 사용
- update log info

TW-154 shortest check

---

server/controllers/worldWeather/controllerWorldWeather.js

until 15mins means that it is from 00:00:00 mins to 15:59:99
mins(mm:ss:ms)
So it should minus 16 minus

TW-152 ThreeThisTime

---

server/controllers/alert.push.controller.js
server/controllers/controllerKmaStnWeather.js
server/controllers/controllerManager.js
server/controllers/controllerTown.js
server/lib/kmaScraper.js
server/models/modelKmaStnHourly2.js
server/models/modelKmaStnMinute2.js

*거리 제한 0.2는 기존 유지에 대한 전달이 잘 못 되어 다시 0.2로 변경했습니다.*
- kma stn hourly/minutes schema
- rs15m 추가 저장 (강수확인용)
- alert.push
- push를 보낼지 여부를 rns도 같이 봄
- DSF source는 pty에 따라 rns 설정
- weather forecast는 shortest가 정리된 0~29분 사이에만 전송
- air forecast는 실용성차원에서 30분~59분 사이에만 전송
- forecast는 아직 알림 보내지 않음
- 동시 연결을 6개로 제한
- pty, rns 설정
- rns는 기존 rns와 rs15m을 같이 봄 (둘중에 한개라도 있으면 강수로 판단
- rnsSource 필드로 weather, rs15m에 의해 변경되었는지 남김
- 일기정보상에 약한/이슬 비/진눈깨비는 rns를 강제로 true로 변경
- rns로 pty를 1이상으로 설정할때는 local aws에서도 강수가 확인되어야 변경함.
- current(dongnae), aws city hourly, aws city min, aws local min obj로 원본남김
- shortest 오류 문제 TW-82
- 정기적으로 업데이트 하게 변경
- short
- 매시간 업데이트하게 변경

TW-92 TW-165 TW-82 현재날씨 PTY 설정 및 알림 관련 수정

---

client/scss/ionic.app.scss
client/www/templates/nation.html

TW-170 iPhone 화면 확대 사용시에 전국날씨가 짤림
* 전국날씨 페이지에 스크롤 추가
* 하단 마진 추가
* 불필요한 Div 제거

TW-170 iPhone 화면 확대 사용시에 전국날씨가 짤림

---

ios/widget/TodayWeatherShowMore.m

+ widget에서 airnow grade color 지원 #1977
- #TW-109 airnow grade color 6단계 로 color값 변경

TW-109 airnow grade color 6단계 로 color값 변경

---

client/www/js/service.push.js
client/www/js/service.weatherinfo.js

- source가 있는 경우에만 push update
- updateCityInfo 오류 수정

TW-173 check cityInfo.source

---

server/controllers/worldWeather/controllerCollector.js

TW-177 system down at getting error from dsf

---

server/controllers/alert.push.controller.js

TW-180 도시명이 두번 나오는 문제 수정

---

server/controllers/alert.push.controller.js
server/controllers/controllerPush.js
server/lib/unitConverter.js
server/models/alert.push.model.js
server/models/modelPush.js
server/routes/v000902/route.push.update.list.js

- client에서 airForecastSource 받음
- airForecastSource에 따라 airkorea, kaq 요청함

TW-174 TW-121 push setting에 kaq 지원

---

server/controllers/worldWeather/controllerWorldWeather.js

TW-152 Three ThisTime

---

client/www/js/controller.air.js
client/www/js/controller.forecastctrl.js
client/www/js/controller.tabctrl.js
client/www/js/service.push.js
client/www/js/service.weatherutil.js
client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json
client/www/templates/tab-air.html
client/www/templates/tab-dailyforecast.html
client/www/templates/tab-forecast.html
server/locales/de.json
server/locales/en.json
server/locales/ja.json
server/locales/ko.json
server/locales/zh-CN.json
server/locales/zh-TW.json

- 일별예보 2일이상 지원가능하게 수정
- 간격 문제로 날짜 포멧 MMDD -> DD로 변경
- KAQ 출저 정보 추가
- push 정보에 대기예보출처 추가

TW-181 KAQ 지원

---

ios/widget/MainInterface.storyboard
ios/widget/TodayViewController.h
ios/widget/TodayViewController.m

+ #TW-138 [iOS][widget] 앱내에서 현재위치 사용으로 되어 있지만, 실제 디바이스에서 위치서비스 off한 경우 #2218
- location off시 버튼 및 도시이름 레이블 제외 모두 hidden
+ #TW-142 [iOS][widget] next city 버튼 과 지역name은 항상 표시되도록 수정 
- TW-138과 같이 off한 경우에 나타나날 수 있는 상황과 같은 예외상황에서 버튼/지역이름 항상 표시되도록 수정

TW-138, TW-142 locationOffIssue-nextBtnEnable

---

server/routes/v000902/route.push.update.list.js

TW-173 push list update하다가 에러나면 로그 출력

---

server/controllers/controllerManager.js
server/controllers/kaq.dust.image.controller.js
server/controllers/kaq.hourly.forecast.controller.js

- requestTask가 분단위 변경이라서 7분으로 조정
- remove dataBackup folder in folderList
- image의 시작 시간은 pubDate의 20시간 뒤부터임.
- update image prefix of kaq

TW-184 update kaq hourly

---

server/controllers/alert.push.controller.js
server/test/test.alert.push.controller.js

- name이 '오존'인경우 '가'를 '이'로 변환
- airList 만들때, grade가 없는 경우 list에 넣지 않게 수정.

TW-186 오존가 -> 오존이

---

server/controllers/controllerPush.js
server/test/e2e_local/test.e2e.controller.push.js

- arpltn이 없는 경우 발생
- str도 있는지 체크해서 추가하게 변경

TW-162 alarm push에 '통합대기 undefined' 전달되는 문제

---

server/controllers/controllerTown24h.js
server/locales/de.json
server/locales/en.json
server/locales/ja.json
server/locales/ko.json
server/locales/zh-CN.json
server/locales/zh-TW.json
server/test/testControllerTown.js

- 모든 오염물질의 grade가 1,2인경우 데이터가 아닌 단문으로 표현

TW-191 대기상태가 보통,좋음인 경우 단문으로 처리

---

server/controllers/alert.push.controller.js

#1701
- 악천후 경보 처음 상태 업데이트시에 나쁨이거나 경보 상태이면 push 전송하게 변경

TW-195 사용자 알림 등록후 첫 상태 업데이트 시에 알림 전송

---

server/controllers/worldWeather/controllerWorldWeather.js

TW-152 check current date and hour
: if current’s time is 01:00, it can be skip.

TW-152 check current date and hour

---

client/www/js/app.js
client/www/js/controller.air.js

* 차트의 rect 위치 맞지 않는 문제 수정
* safari에서 예보가 없는 경우 빈 데이터를 설정할 때 new Date() 시 invalid로 생성되어 날짜가 설정되지 않는 문제 수정
- new Date() 시에 입력 날짜 포멧 변경(yyyy-mm-ddThh:mm:ss)

TW-95 미세먼지 페이지에서 시간별 예보 표시 #1849

---

client/www/index.html

TW-202 설정 화면에서 메뉴 리스트의 크기가 다른 문제
* 다음 depth가 있는 경우와 없는 경우 구분하지 않고 동일한 스타일로 변경

TW-202 설정 화면에서 메뉴 리스트의 크기가 다른 문제

---

client/www/js/app.js

- ionic config에서 swipeBack을 disable 시킴

TW-201 setting-radio.html에서 swipe시에 앱 동작 멈춤

---

server/controllers/controllerTown24h.js

- return empty string when airinfo is invalid

TW-204 summaryAir에서 통합대기 undefined

---

server/controllers/controllerKmaStnWeather.js
server/controllers/controllerTown.js
server/controllers/controllerTown24h.js

- 온도차와 날씨(일기)값을 최소값 2.5로 하여 특이사항이 없는 경우 온도차와 일기를 기본값으로 함
- 일기가 없는 경우 sky를 기반으로 생성

TW-200 summary 기본 값 설정

---

client/www/js/service.push.js
client/www/js/service.weatherutil.js

TW-181 air forecast airkorea -> kaq

---

server/app.js
server/controllers/controllerTown.js
server/controllers/controllerTown24h.js
server/controllers/kecoController.js
server/routes/v000903/index.js
server/routes/v000903/route.kma.v000903.js

- new v000903
- airInfo -> airInfoList
- new cTown.makeAirInfoLit, cTown.AirForecastList
- string, unit converting시에 airInfoList 고려

TW-206 인접 대기측정소 정보 3개 전달

---

server/controllers/controllerManager.js
server/controllers/kma/kma.town.short.rss.controller.js
server/lib/midRssKmaRequester.js

- config.db.version 2.0, 1.0 중에 한군데만 저장

TW-58 gather에서 DB 2.0에만 저장

---

server/controllers/controllerTown24h.js
server/controllers/kma/kma.town.shortest.controller.js
server/controllers/worldWeather/controllerWorldWeather.js

- controllerTown24h
- shortest중에 과거 데이터는 제외
- shortest obj에 pubDate 추가
- controllerWorlWeather
- shortest 생성(가장 가까운 1시간 간격 예보 3개)

TW-208 shortest 개선

---

server/controllers/alert.push.controller.js

- forecastObj에 weather info가 빠져서 발생한 이슈
- 날씨 정보와 대기 정보 사이에 공백 추가

TW-213 Alert message error (NaN시부터 비가 내릴 예정입니다.)

---

server/controllers/controllerManager.js

- controllerManager
- setTimeout을 사용하여 완화
- 완전 해결책은 아님
- issue 발생하는 경우 task가 멈추기 때문에 short를 task에 제외함

TW-120 Maximum call stack size exceeded at controllerManager.js

---

server/controllers/controllerManager.js
server/controllers/kma/kma.forecast.zone.controller.js
server/lib/collectTownForecast.js
server/lib/midRssKmaRequester.js
server/models/kma/kma.forecast.zone.model.js
server/models/kma/kma.town.mid.rss.model.js
server/routes/v000001/routeGather.js
server/test/e2e_local/test.e2e.kma.forecast.zone.controller.js

- 원인 전국 mid rss에서 서산이 빠지고 홍성을 제공함
- weather.go.kr에 확인하니, 온도의 경우 각 지역으로 listPointNumber별로 요청시 더 자세한 온도를 제공하는 것을 확인함
- 사용하지 않고 있던 예보지역코드 디비화해서 각자의 예보코드를 저장
- midTemp, midRss에서 데이터를 가지고 올때 예보지역코드를 기반으로 데이터 수집 및 저장

TW-211 Fail to find midRss regId=11C20101

---

server/lib/kmaScraper.js
server/test/testKmaScraper.js

TW-221 kmastnmunute2 toArray 속도 개선

---

server/controllers/kaq.hourly.forecast.controller.js
server/test/e2e_local/test.e2e.kaq.hourly.forecast.controller.js
server/test/testImageParser/testKaqImageParser.js

- kaq.hourly.forecast.controller
- modelImg에 따라 ModelimgCase4 또는 Modelimg사용
- modelimg_CASE4, modelimg가 아닌경우 modelimg_CASE4 사용
- test.e2e.kaq.hourly.forecast.controller
- 4가지 modelimg parsing하기 위해 시간 조정
- testKaqImageParser
- test comment 수정

TW-185 support modelimg of kaq

---

client/www/js/service.weatherutil.js

TW-223 날씨 정보 못 가지고 오는 문제

---

client/www/client.config.js
client/www/js/service.weatherutil.js
ta.ios/www/client.config.js
tw.ios/www/client.config.js

TW-145 날씨 사진 테마 지원 #1855

---

server/controllers/worldWeather/controllerAqi.js
server/controllers/worldWeather/controllerWorldWeather.js
server/routes/v000902/route.dsf.coord.v000902.js

- new queryTwoDaysWeather2
- checkValidDate에 mins를 추가해서 지정시간만큼 체크하게 수정
- thisTime과 aqi 비교시에 mTime사용하며, 6시간차까지 허용
- controllerAqi
- prevent duplicate calling callback

TW-207 dsf, waqi 분리

---

server/controllers/controllerManager.js
server/controllers/kaq.hourly.forecast.controller.js
server/test/e2e_local/test.e2e.kaq.hourly.forecast.controller.js

- modelimg별로 업데이트 시간이 다름.
- 최근 업데이트 날짜 폴더에 modelimg가 4종류 모두 있는지 확인
- 지정 업데이트 시간, 근처 4시간 업데이트 시도
- modelimg가 모두 모이지 않았으면 추가 진행하지 않음.

TW-224 KAQ 미세먼지 PM2.5 예보 데이터 오류

---

server/controllers/controllerPush.js
server/test/e2e_local/test.e2e.controller.push.js

- push alarm에서 kaq data parsing 추가
- '흐리고 ', '구름많고 ', '구름적고 ' 제거

TW-225 push alarm에서 kaq 지원

---

server/controllers/worldWeather/controllerAqi.js

TW-207 retry request feed when old feed

---

server/controllers/controllerTown.js
server/controllers/controllerTown24h.js

TW-240 summary weather 조정

---

server/controllers/kma/kma.town.short.controller.js
server/controllers/kma/kma.town.short.rss.controller.js
server/controllers/kma/kma.town.shortest.controller.js
server/models/kma/kma.town.current.model.js
server/models/kma/kma.town.mid.forecast.model.js
server/models/kma/kma.town.mid.land.model.js
server/models/kma/kma.town.mid.sea.model.js
server/models/kma/kma.town.mid.temp.model.js
server/models/kma/kma.town.short.model.js
server/models/kma/kma.town.short.rss.model.js
server/models/kma/kma.town.shortest.model.js

- sort, query param은 index 생성
- controller는 들여쓰기만 정리했음

TW-242 kma db index 정리

---

client/www/js/controller.searchctrl.js
client/www/js/service.push.js
client/www/js/service.weatherinfo.js

- controller.searchctrl
- updateCity는 날씨정보 가지고 온 경우(source 갱신)만 update
- service.push, service.weatherinfo
- updateCityInfo에서 push 갱신여부 판단
- service.push
- push정보에 package 추가

TW-241 push list 갱신 안되는 문제 수정

---

client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json
server/controllers/controllerTown24h.js
server/controllers/kecoController.js
server/locales/de.json
server/locales/en.json
server/locales/ja.json
server/locales/ko.json
server/locales/zh-CN.json
server/locales/zh-TW.json

- 문자열 업데이트
- grade가 모두 보통이상인 경우 가장 높은 지수 표시

TW-191 update summary air

---

client/www/js/controller.purchase.alexdisler.js
client/www/js/controller.purchase.j3k0.js
client/www/js/controller.purchase.js

* Purchase 화면에서 StatusBar 색상 설정 코드 제거

TW-247 Purchase 화면에서 StatusBar 색상 변경

---

server/controllers/controllerPush.js
server/locales/de.json
server/locales/en.json
server/locales/ja.json
server/locales/ko.json
server/locales/zh-CN.json
server/locales/zh-TW.json
server/test/e2e_local/test.e2e.controller.push.js

- 현재는 summaryAir 전달
- 오늘/내일은 24시간 평균 값 전달

TW-191 todayAir 용 push message

---

server/controllers/controllerManager.js
server/controllers/kaq.hourly.forecast.controller.js

- model 중에 modelimg, modelimg_CASE4 만 parsing
- disable existAllModelImg

TW-224 kaq data update 시간대 변경

---

client/scss/ionic.app.scss
client/www/js/controller.air.js
client/www/templates/tab-air.html

- update css and templates for weather info
- goWeather linke error 수정
- new css main-box-air-summary

TW-229 weather info in air page

---

ta.ios/widget/MainInterface.storyboard
ta.ios/widget/TodayViewController.h
ta.ios/widget/TodayViewController.m
ta.ios/widget/TodayWeatherShowMore.h
ta.ios/widget/TodayWeatherShowMore.m
ta.ios/widget/widget.entitlements

+ 	#미세먼지앱 및 오늘날씨 위젯타입확장용 미세먼지위젯 구현 #2182
- 미세먼지 위젯 간편히 보기 구현

TW-126-today-air-widget-init-release

---

client/www/data/update.info.js
client/www/js/app.js
client/www/js/controller.tabctrl.js

- updateInfo ta, tw 분리
- enablePopup flag 추가

TW-231 update info에 popup enable 여부 추가

---

client/gulpfile.js
client/ta.config.xml
client/ta.package.json
client/www/data/update.info.js

- set version of ta to 0.1.0
- use new upload key for ta

TW-133 update gulpfile.js for ta, release

---

client/scss/ionic.app.scss
client/www/js/controller.searchctrl.js
client/www/templates/tab-search.html

- package 별로 list 분리
- aqi icon, str, action guide 표시

TW-264 즐겨찾기 페이지 업데이트

---

server/controllers/controllerTown24h.js

- api version up 이후 emoji를 못 찾음
- api version up 되면 skyIcon 내용이 소문자+'_'으로 변경됨
- string을 lower case로 비교하게 변경

TW-265 push에서 emoji 못 찾는 문제

---

client/www/index.html
client/www/js/app.js
client/www/templates/tab-search.html

- global js variable은 angular template에서 접근 안됨
- package를 rootScope에 등록

TW-264 set rootScope.package for accessing on templates

---

client/www/js/controller.searchctrl.js

- updateCity를 하지 않아서, updateWeatherData에서 에러 처리됨
- city 업데이트시에 빠진 데이터 수정

TW-273 즐겨찾기에서 현재위치 on하면 데이터 갱신 안되는 문제

---

server/controllers/controllerTown.js

TW-277 map -> mapSeries

---

client/www/templates/ta-tab-weather.html
client/www/templates/tab-dailyforecast.html
client/www/templates/tab-forecast.html

- 시간별날씨에 자외선,식중독 추가
- 자외선 수치 값 추가

TW-275 자외선 수치 값

---

client/gulpfile.js
client/package.json
client/tw.package-androidsdk16.json
client/tw.package.json

- gulpfile
- plugin add facebook4
- tw.package-androidsdk16.json
- for android sdk16~19
- package.json
- cordova-android 6.3.0

TW-272 facebook analytics

---

server/controllers/airkorea.dust.image.controller.js
server/controllers/airkorea.hourly.forecast.controller.js
server/controllers/img.hourly.forecast.controller.js
server/controllers/kaq.hourly.forecast.controller.js
server/controllers/kaq.modelimg.case.controller.js
server/controllers/kaq.modelimg.controller.js
server/lib/kaq.finedust.image.parser.js

- string 오류 수정
- update xxxx.hourly.forecast.controller
- 꺼낼 pollutants 설정
- log 수정
- kaq.xxxx.controller
- imgPaths에 polutant name을 소문자로 접근하게 수정

TW-185 update xxxx.hourly.forecast.controller

---

server/lib/kecoRequester.js
server/lib/kmaScraper.js
server/s3/controller.s3.js

- controller.s3
- new copy, uploadData
- kecoRequester
- upload msrstn, ctprvn
- kmaScraper
- upload kma stn hourly weather

TW-269 upload keco msrstn, keco rltmarpltn, kma aws hourly

---

tw.ios/widget/TodayViewController.m

TW-280 prevent 'fail to load' on ios widget

---

server/lib/AQI/aqiRequester.js

- err 출력 및 전달하지 않고 msg 생성하여 전달

TW-282 ignore err that is circular structure

---

server/controllers/geo.controller.js

TW-288 update isKoreaArea

---

server/lib/kmaScraper.js

- update checkPubdate to base KmaStnHourly2
- update getStnPastHourlyWeather for performance

TW-269 update kmaScraper

---

server/lib/kecoRequester.js

- request error에서 connection error의 경우 warn으로 log level 조정

TW-293 연결오류시에 log level 조정

---

server/controllers/kecoController.js

- invalid는 뒤로 보내고, mangName이 도시대기인 경우 우선함

TW-172 sorting arpltnList

---

ta.ios/widget/MainInterface.storyboard
ta.ios/widget/TodayViewController.m
ta.ios/widget/TodayWeatherShowMore.h
ta.ios/widget/TodayWeatherShowMore.m

+ 	#TW-126 미세먼지앱 및 오늘날씨 위젯타입확장용 미세먼지위젯 구현 #2182
- 대기 bar size 기존 절반으로 조정
- 메인앱 이동 이슈 fix
- 더보기 disable
- 각 오염물질에 대한 grade 색 조정

TW-126-variable-issue-fix

---

tw.ios/widget/TodayViewController.m
tw.ios/widget/TodayWeatherShowMore.m
tw.ios/widget/TodayWeatherUtil.m
tw.ios/widget/WidgetConfig.h

+ #TW-280 [0.9.95][ios] widget 로드 할 수 없음
- release mode에서 자동으로 log출력 안되게 수정

TW-280 disable NSLog in release mode

---

server/app.js

- DB 오류시에 재연결을 위해 keepAlive 제거

TW-277 remove keepAlive in mongoose options

---

.travis.yml
server/controllers/alert.push.controller.js
server/controllers/controllerPush.js
server/models/alert.push.model.js
server/models/modelPush.js
server/package.json
server/routes/v000705/routePushNotification.js
server/routes/v000902/route.push.update.list.js
server/test/e2e_local/test.e2e.controller.push.js

- alert.push
- new fcmToken in model
- update registration id and token
- push
- new fcmToken in model
- new firebase-admin
- fcmToken이 있는 경우 fcm 우선 사용

TW-261 support fcm

---

client/www/js/controller.push.js
client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json
server/locales/de.json
server/locales/en.json
server/locales/ja.json
server/locales/ko.json
server/locales/zh-CN.json
server/locales/zh-TW.json

- back arrow나 Cancel시에 팝업으로 저장여부 문의

TW-297 popup for confirm save

---

client/www/js/controller.searchctrl.js

- 저장된 도시가 많은 경우 즐겨찾기 페이지에서 나오는데 오래 걸림
- loadWeatherData를 event 기반으로 한개씩 업데이트 함
- 현재위치는 1회이므로 그냥 init에서 시도함

TW-299 page 속도 개선

---

client/www/js/controller.forecastctrl.js

TW-300 check validation of day chart

---

ta.ios/widget/MainInterface.storyboard
ta.ios/widget/TodayViewController.h
ta.ios/widget/TodayViewController.m
ta.ios/widget/TodayWeatherShowMore.m
ta.ios/widget/TodayWeatherUtil.m
ta.ios/widget/WidgetConfig.h
tw.ios/widget/TodayViewController.h
tw.ios/widget/TodayViewController.m

+ 	#TW-315 [iOS][TA][widget] 지역변경이 안되는 이슈
- index 잘못저장되는 이슈 fix
- NSLog->DebugLog로 변경

TW-315 not-change-adress

---

server/lib/kmaScraper.js

- rs1h와 rs6h사이에 rs3h 추가
- table cell이 예상하고 있는 propertyName을 넘으면 error처리

TW-318 kma aws 매분관측자료 포멧 변경 대응

---

server/controllers/kma/kma.town.current.controller.js

- pubDate가 null인 경우 fcsDate로 데이터 보정

TW-319 past current 업데이트시 오류 수정

---

server/controllers/alert.push.controller.js
server/controllers/controllerPush.js
server/package.json
server/test/e2e_local/test.e2e.alert.push.controller.js
server/test/e2e_local/test.e2e.controller.push.js

- updateAt이 오래된 중복 알림 제거
- push 정보 업데이트시 registrationId가 우선 키, registrationId가 없는 경우 fcmToken을 키로 저장.

TW-320 registrationId, cityIndex, id 중복 알림 제거

---

client/www/data/update.info.js
client/www/js/app.js
client/www/js/controller.push.js
client/www/js/service.firebase.js
client/www/js/service.push.js

- fcm
- grant permission -> has permission on iOS
- register is not needed
- fix wrong appVersion path
- check window.package name
- TW-317
- diagnostic
- resume 이나 run 시에 registerLocationStateChangeHandler가 call되지 않음
- fix wrong updateInfo json format

TW-271 support firebase on iOS

---

server/controllers/alert.push.controller.js
server/controllers/controllerPush.js

- add fcmToken on log
- use sendFcmNotification when pushInfo has fcmToken on iOS
- keep sending message when fail to sendNotification

TW-311 fcm on iOS

---

server/app.js
server/controllers/controllerManager.js
server/controllers/worldWeather/dsf.controller.js

- new line
- Run maintainDB on the gather mode

TW-58 minor fix

---

client/www/js/service.push.js

- format : http://co.wizardfactory.net:8080/browse/TW-271?focusedCommentId=10539&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-10539

TW-271 support aps format for firebase push on ios

---

client/www/js/service.weatherutil.js

* 날씨 아이콘의 naming 변경으로 skyIcon을 날씨 아이콘으로 변경하는 조건문이 동작하지 않음
- 날씨 아이콘의 naming 규칙에 맞게 수정

TW-325 공유 시 날씨 아이콘 표시되지 않는 문제

---

server/controllers/worldWeather/controllerWorldWeather.js
server/routes/v000902/route.dsf.coord.v000902.js

- overwrite thistime if the data has bigger time.

TW-58 fixed 3 thistime issue

---

client/www/js/service.push.js
client/www/js/service.weatherinfo.js

- window.updateCityInfo 없는 경우 에러 처리
- cityIndex가 0인 pushInfo는 갱신 at loadPushInfo
- pushInfo에서 geo, town 둘 중에 하나라도 데이터가 있으면 upload함
- init시에 window.updateCityInfo 생성

TW-241 현재위치에 대한 push 정보 갱신 안되는 문제

---

server/controllers/worldWeather/controllerWorldWeather.js
server/controllers/worldWeather/dsf.controller.js

updated current date the same as current data’d date, if current data
has been received.

TW-58 updated current date

---

server/controllers/controllerPush.js
server/routes/v000903/index.js
server/routes/v000903/route.geo.v000903.js
server/test/e2e_local/test.e2e.controller.push.js

- v000903/geo 지원 for push alarm
- 기존 tw-service에서 데이터를 가지고 오는 구조에서 내부 call로 변경할 예정
- weather request 순서 정리
- source KMA, town이 있는 경우 KMA, source DSF면 dsf
- geo만 있는 경우 api server로부터 geoinfo가지고 와서 재요청

TW-330 TW-241 source없는 경우 대처, 속도개선

---

client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json
client/www/templates/purchase.html
server/locales/de.json
server/locales/en.json
server/locales/ja.json
server/locales/ko.json
server/locales/zh-CN.json
server/locales/zh-TW.json

- add privacy policy, terms of use

TW-329 new auto-renew purchase info for iOS

---

server/controllers/alert.push.controller.js
server/controllers/controllerPush.js
server/models/alert.push.model.js
server/models/modelPush.js
server/routes/v000705/routePushNotification.js
server/routes/v000902/route.push.update.list.js
server/test/e2e_local/test.e2e.controller.push.js

- pushInfo/alertPush 업데이트시 town이 있으나, first가 빈문자열인경우 오류 처리
- 저장된 push 정보에서 DSF 우선함
- pushInfo.source가 없으면 그대로 저장
- uuid, appVersion 추가 저장

TW-241 현재위치 알림/알람 개선

---

server/controllers/worldWeather/controllerWorldWeather.js
server/controllers/worldWeather/dsf.controller.js

TW-58 add log

---

client/www/js/controller.settingctrl.js

- add isIOS func in $rootScope

TW-329 fix error isIOS on purchase.html

---

server/controllers/controllerPush.js

TW-333 Updating the path '_v' would create a conflict at '_v'

---

server/controllers/controllerTown24h.js
server/controllers/kasi.riseset.controller.js
server/controllers/kma/kma.town.mid.controller.js
server/controllers/worldWeather/controllerWorldWeather.js
server/controllers/worldWeather/dsf.controller.js

- 데이터나 정상적인 경우보다 flow와 비정상적인 경우 위주로 로그 출력
- 혹시 데이터를 많이 출력하게 되면 코드 위치정보를 같이 출력하여 추후 빨리 제거 가능하게 하자

TW-293 log 줄임

---

server/controllers/kecoController.js
server/lib/kecoRequester.js
server/models/arpltnKeco.js
server/routes/v000803/route.nation.js

- map을 사용하여 각 sido별 최신 데이터를 수집하게 변경
- nation api에서 airInfoList가 필요없으므로 데이터 축소를 위해 삭제

TW-123 시도별 미세먼지 정보 모두 수집 안되는 경우 보완

---

ta.ios/widget/MainInterface.storyboard
ta.ios/widget/TodayViewController.m

+ #TW-326 [iOS][widget][TA] 하단 라인 오류
- storyboard 위치 조정
- favorite 설정안했을때 화면 오류 수정

TW-326 bottom line issue

---

server/routes/v000901/route.dsf.coord.js
server/routes/worldweather/routeWeather.js

applied a new format of DSF query to all route

TW-50 applied a new format of DSF query to all route

---

tw.ios/widget/TodayViewController.m

+ #TW-336 오늘날씨 위젯에서 가끔 Error 53이 뜨며 새로고침이 안됩니다
- error description 추가

TW-336 added error description

---

server/controllers/alert.push.controller.js
server/controllers/controllerPush.js
server/test/e2e_local/test.e2e.controller.push.js

- town 정보는 가급적 사용을 자제함 (client에서 없어지고 있음)
- 현재위치(cityIndex:0)은 source가 안맞는 경우가 있어 우선 예외처리

TW-340 fix wrong town info in push notification

---

client/www/js/service.push.js

- location이 있는 경우 town은 생성하지 않음

TW-340 post wrong town object for push notification

---

client/www/js/controller.units.js

- airUnit이 aircn인 경우 default로 변경

TW-344 aircn 오류 수정

---

server/controllers/alert.push.controller.js
server/controllers/controllerPush.js
server/models/alert.push.model.js
server/models/modelPush.js
server/test/e2e_local/test.e2e.alert.push.controller.js
server/test/e2e_local/test.e2e.controller.push.js

- disable push/alert push with updateBy info when token was not found
- new field 'updatedBy' for disabling by system on alert push and push

TW-347 fcm registration token was not found

---

client/scss/ionic.app.scss
client/www/templates/nation-air.html

TW-349 스크롤 안됨,메뉴가 항목가림

---

client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json
client/www/templates/purchase.html
server/locales/de.json
server/locales/en.json
server/locales/ja.json
server/locales/ko.json
server/locales/zh-CN.json
server/locales/zh-TW.json

- scroll 가능하게 수정
- 복원버튼 이동
- 구매후 아이콘 및 설명 오류 수정

TW-351 TW-229 구매페이지에서 div 겹치는 문제

---

server/controllers/worldWeather/controllerWorldWeather.js

- check validation on makeHourly, makeCurrentData

TW-350 check validation of data of prep_xxx 2

---

server/controllers/controllerTown.js
server/controllers/lifeIndexKmaController.js
server/models/modelAreaNo.js
server/utils/update.areano.to.db.js

- areaNo가 없거나, area에 해당하는 데이터가 없는 경우 near 사용
- update.areano.to.db.js
- add 새로 추가된 데이터
- updatedAt filed 추가

TW-127 get near kma life index for areano that does not have data

---

server/controllers/controllerTown24h.js

- data 출력 레벨 조정
- 태하리 예외처리
- etc
- coord2addr 요청시 language 적용

TW-293 log 정리

---

server/controllers/alert.push.controller.js
server/controllers/controllerPush.js
server/test/e2e_local/test.e2e.controller.push.js

- send notification을 fcm, ios, android(gcm)으로 분리

TW-347 update fcm push process

---

server/controllers/controllerTown.js
server/controllers/controllerTown24h.js

- set req.geocode for getting health index
- fix param error on _retryRequest

TW-293 set req.geocode

---

client/www/js/service.branch.js
client/www/js/service.push.js

- location.url -> setCityIndex+reload event

TW-354 push에서 전달해주는 fav 처리 오류 수정

---

server/controllers/alert.push.controller.js
server/controllers/worldWeather/controller.ww.units.js
server/controllers/worldWeather/controllerWorldWeather.js

- shortest data도 보정함
- 날짜 비교를 Date로 변경해서 비교 for 24:00

TW-359 24시 shortest 오류 수정

---

tw.ios/widget/TodayViewController.h
tw.ios/widget/TodayViewController.m
tw.ios/widget/WidgetConfig.h

+ #TW-219 [iOS][widget] 현재위치 얻어오는 루틴이 실패시 처리
- processed getting location fail issue
- modified log method

TW-219 processed getting location fail issue

---

server/controllers/controllerTown.js
server/controllers/kma/kma.forecast.zone.controller.js

- new findForecastZoneByName()
- midTemp regId는 kma forecast code를 사용

TW-211 mid temp 개선

---

client/package.json
client/ta.package.json
client/tw.package.json
client/www/js/service.twads.js

- new cordova-plugin-screen-orientation
- listen orientationchange event

TW-348 recreate banner at rotation

---

server/controllers/worldWeather/dsf.controller.js

- darksky api가 에러나면 client에 에러전달하게 처림

TW-361 darksky api error나면 service restart 됨

---

server/controllers/controllerTown.js
server/controllers/controllerTown24h.js
server/controllers/kaq.hourly.forecast.controller.js
server/controllers/lifeIndexKmaController.js

- skip error in getAllDataFromDb
- update log error for collection.find
- update log message for following process
- batchSize from 101(default) to 30
- Reducing the batch size to keep the cursor alive.

TW-277 improve cursor id not found

---

server/controllers/kma/kma.forecast.zone.controller.js

- 광역시의 경우를 위해 regSp를 C로 고정
- "구"에 대한 index 처리 오류 수정

TW-369 중기예보를 위한 regId찾기 오류

---

server/controllers/worldWeather/dsf.controller.js

- filter method would return empty array even though there is no data
that is passed by function.

TW-152 fixed bug

---

tw.ios/widget/TodayViewController.m

+ #TW-368 widget: -[TodayViewController saveWeatherInfo:] + 344
- modified setobject crash issue

TW-368 setobject crash issue

---

server/controllers/alert.push.controller.js
server/controllers/worldWeather/controllerWorldWeather.js
server/controllers/worldWeather/dsf.controller.js

- db에서 데이터를 가지고 올때 result.updateDate가 항상 undefined 힘.
- result.updatedDate를 사용하지 않고, 바로 current.data.current.dateObj 사용

TW-359 alert.push 에서 간헐적으로 shortest를 못 찾는 문제

---

server/controllers/alert.push.controller.js
server/controllers/controllerPush.js
server/routes/v000705/routePushNotification.js

- update api delete version/push

TW-381 update api push delete

---

server/controllers/controllerTown24h.js
server/controllers/geo.controller.js
server/controllers/kasi.riseset.controller.js
server/controllers/kma/kma.town.short.rss.controller.js
server/controllers/worldWeather/controllerWorldWeather.js
server/lib/collectTownForecast.js
server/lib/kecoRequester.js
server/lib/kmaScraper.js
server/lib/log.js
server/lib/midRssKmaRequester.js
server/routes/v000803/index.js
server/routes/v000903/route.geo.v000903.js
server/s3/controller.s3.js

- set log level error for console
- remove cache domain(not needed)

TW-293 use logentries

---

server/app.js
server/controllers/controllerTown.js
server/controllers/controllerTown24h.js
server/controllers/kasi.riseset.controller.js
server/controllers/kma/kma.town.mid.controller.js
server/lib/collectTownForecast.js
server/lib/kmaScraper.js
server/lib/lifeIndexKmaRequester.js
server/routes/v000705/receiptValidation.js
server/routes/v000705/routePushNotification.js
server/routes/v000803/route.nation.js
server/routes/v000803/route.test.js
server/routes/v000902/route.push.update.list.js
server/test/test.controller.town24h.js
server/utils/convertGeocode.js
server/utils/makeGeocodeList.js

- meta에 sID추가
- 메세지 개선
- fnGetDataFromDb 잘못된 오류처리 수정
- getMid callback 처리 오류 수정

TW-386 내용없는 error log 개선

---

client/www/js/controller.searchctrl.js
client/www/js/service.push.js

- call removePushListByCityIndex when current location is disabled
- call delete api with cityIndex and fcmToken

TW-370 remove push list of current location when city is disabled

---

client/www/js/service.branch.js
client/www/js/service.push.js
client/www/js/service.weatherinfo.js

- index check tightly on canLoadCity()
- deeplink, push로 들어오는 fav를 숫자로 변환

TW-371 invalid cityIndex

---

server/controllers/controllerManager.js
server/lib/collectTownForecast.js

- retry시에 key 변경해주기 (key limit, error 구분하지 않고 변경함)

TW-396 동네예보 키 제한 수 넘을 때, 개선

---

server/controllers/img.hourly.forecast.controller.js
server/controllers/kaq.hourly.forecast.controller.js
server/models/kaq.hourly.forecast.model.js

- 이미 업데이트 된 데이터는 저장하지 않음
- folderName 변경사항 반영

TW-397 filter by invalid and updated

---

server/controllers/worldWeather/controllerAqi.js
server/controllers/worldWeather/controllerWorldWeather.js
server/controllers/worldWeather/dsf.controller.js
server/lib/AQI/aqiRequester.js
server/lib/DSF/dsfRequester.js

- data 못 가지고 온 경우 _makeOutputFormat 하기 전에 error callback
- dsf data 못 가지고 온 경우에는 error 전달

TW-398 dsf data 취득 실패시 죽는 문제

---

client/www/js/controller.setting.radio.js
client/www/js/service.push.js
client/www/js/service.weatherinfo.js

- TW-194 call Push.updateUnits() at setValue Unit
- console.info는 ios log에 나오지 않음
- TW-365
- pushList는 save 데이터를 GA로 보냄
- location check 오류 수정
- town의 경우 개별비교하게 수정 (location, town만 object임)

TW-400 TW-194 push 업데이트 관한 버그 수정

---

client/www/js/service.weatherinfo.js
client/www/js/service.weatherutil.js

- '대한민국' 이 없는 경우 town 생성에 에러가 발생함
- 기존 city에 location, location.lat가 없는 경우 업데이트

TW-402 TW-365 TW-340 address -> town 변환 이슈

---

server/lib/collectTownForecast.js

TW-401 check validation of current, short, shortest

---

server/controllers/worldWeather/controllerWorldWeather.js
server/lib/AQI/aqiRequester.js

- reduce timeout for aqiRequester.getData
- fix mistypo

TW-334 retry request when result.status is nug

---

server/controllers/alert.push.controller.js

- save 대신 update사용
- $set을 사용해서 alert 관련 기록 유지

TW-387 No matching document found for id

---

server/controllers/kma/kma.town.current.controller.js
server/controllers/kma/kma.town.mid.controller.js
server/controllers/kma/kma.town.short.controller.js
server/controllers/kma/kma.town.short.rss.controller.js
server/controllers/kma/kma.town.shortest.controller.js

- mid land가 없는 경우 체크
- errCode등 callback param을 Error 로 통일

TW-404 There are no mid datas from DB : modelMidLand

---

server/controllers/controllerPush.js
server/routes/v000705/routePushNotification.js
server/routes/v000902/route.push.update.list.js

- check lat property of location

TW-405 error location parsing of push

---

server/controllers/worldWeather/dsf.controller.js
server/test/testDSF/test.dsf.controller.js

- added test case
- sort after fulfilling missed data.

TW-391 added test case forfulfilling missed data

---

server/app.js
server/lib/log.js
server/package.json

- winston-logentries -> le_node
- winston 1.0.1 -> 2.4.3
- change options of winston to simple

TW-386 upgrade winston, le_node

---

server/controllers/worldWeather/dsf.controller.js

- Fixed bug on the Calculating date with timeOffset
- The only data of the same date with yesterday is allowed to find
missed hourly data.

TW-391 fixed bug

---

server/lib/collectTownForecast.js

TW-401 added invalid current, shortest

---

server/controllers/worldWeather/controllerWorldWeather.js
server/controllers/worldWeather/dsf.controller.js
server/lib/AQI/aqiRequester.js

- Added timeout value to axios on the AQI requester
- Added log message to trace DSF, AQI

TW-367 added timeout value to axios module on the AQI requester

---

server/config/config.js

fix "The opts.token property "Your Logentries key" does not appear to be valid."

fix travis build error

---

client/www/js/controller.kma.special.js
client/www/templates/kma-special.html

- TW-410
- fix test url
- img src -> ng-src

TW-410 오류 수정

---

server/controllers/kma/kma.town.mid.rss.controller.js
server/lib/midRssKmaRequester.js

TW-386 없어진 log level 조정

---

client/package.json
client/ta.package.json
client/tw.package.json

FIX build error at android

---

server/controllers/alert.push.controller.js
server/controllers/controllerPush.js

TW-415 push 유지가간을 60일로 제한

---

server/controllers/controllerTown.js

TW-412 초단기실황 변경에 따라 KMA AWS보다 실황우선

---

server/controllers/kma.specialweather.controller.js

TW-3 announcement을 9시간 뺌

---

server/lib/kecoRequester.js

TW-417 retry when receive DEADLINE HAS EXPIRED ERROR

---

server/controllers/controllerManager.js
server/controllers/kma/kma.town.current.controller.js
server/lib/collectTownForecast.js

- 새로운 데이터에서 데이터가 없는 경우 저장된 데이터로 채움

TW-425 습도,강수량 데이터가 없는 경우 예외처리

---

server/controllers/controllerTown24h.js

- added detailed log msg
- sometimes there is no mid data and appear "21 Oct 2018 10:30:50.682error daily data is invalid {"" log message.

TW-426 added detailed log msg

---

tw.ios/widget/TodayViewController.h
tw.ios/widget/TodayViewController.m
tw.ios/widget/widget-Info.plist

- added retry logic, added location privacys

Error 53 작업을 완료할 수 없습니다. 소프트웨어에 의한 ... #TW-429

---

client/www/js/app.js
client/www/js/controller.start.js
client/www/locales/de.json
client/www/locales/en.json
client/www/locales/ja.json
client/www/locales/ko.json
client/www/locales/zh-CN.json
client/www/locales/zh-TW.json

TW-421 [한국인터넷진흥원] 정보통신망법 의거, 스마트폰 App모니터링 결과서 및 개선 권고(2018-042467)
* start 페이지 실행 시 앱에서 사용하는 선택 권한에 대한 설명을 popup으로 표시함

TW-421 [한국인터넷진흥원] 정보통신망법 의거, 스마트폰 App모니터링 결과서 및 개선 권고(2018-042467)

---

server/controllers/geo.controller.js
server/lib/kecoRequester.js
server/test/testGeoController.js
server/utils/convertGeocode.js
server/utils/getGeoCodeFromDaum.js
server/utils/update.areano.to.db.js
server/utils/updateAreaNo.js

- Changed DAUM API to KAKAO API
: DAUM API wil not be available soon and it's replaced by KAKAO API.
: on the geo.controller.js, I added new function to use kakao api. Kakao API, in getting address, there is no factor to recognize
whether it’s 대한민국 or not. So, it checks/compares whether there is 일본 or
not.

TW 430 KAKAO API

---

server/controllers/controllerTown.js

- rn1 is not number type often
- Somtimes rn1 is not number type so that the getKmaStnMinuteWeather function can not be done properly.

TW-434 rn1 is not number type often

---

server/config/config.js
server/controllers/controllerManager.js
server/controllers/geo.controller.js
server/controllers/kecoController.js
server/lib/kecoRequester.js
server/test/e2e_local/test.e2e.keco.requester.js
server/utils/convertGeocode.js
server/utils/getGeoCodeFromDaum.js
server/utils/update.areano.to.db.js
server/utils/updateAreaNo.js

TW-430 Added kakao key box

---

server/config/config.js

- changed name of env of kakao keys

TW-430 changed name of env of kakao keys

---

server/lib/log.js

catch exception of invalid logentries token

TW-293 catch exception of invalid token
