server/app.js
server/config/config.js

#5 added mongoose DB

---

server/app.js
server/controllers/token.controller.js
server/package.json

- Added jwt module and token.controller.js file.
: It defines the basic functions to use jwt.

#8 added jwt module

---

server/app.js
server/lib/collect.js
server/lib/log.js
server/package.json

- Added collect module as lib/collect.js
: It works to get the weather data from DATA.go.kr
- Added log module as lib/log.js
: It is better for us to use log print.

Fixed #25 Added collect module and log module

---

client/config.xml
client/ionic.project
client/package.json
client/www/index.html
client/www/js/app.js
client/www/js/controllers.js
client/www/js/services.js
client/www/templates/chat-detail.html
client/www/templates/tab-account.html
client/www/templates/tab-chats.html
client/www/templates/tab-dash.html
client/www/templates/tabs.html

Fixed #17 ionic first code commit
* ionic 프로젝트 name을 TodayWeather로, template을 tab으로 변경

Fixed #17 ionic first code commit

---

server/lib/collect.js

- Added extension URL to get more informations at once.

#25 Added extension URL.

---

server/config/config.js
server/lib/collect.js
server/package.json
server/test/test.lib.collect.js

- Change the type of return value that receive the Data from server.
: From string to Object.
- Added test module as lib/collect.js
: It works the test procedure to check lib/collect.js module. (unit
test)

#25 modify collect.js and add test module

---

client/www/templates/tab-dash.html
client/www/templates/tabs.html

nav bar icon을 좀 더 적합한 것으로 변경.
시안에 맞게 layout작업 완료.
새로 분류해서 할 작업.
폰트 변경
element.style로 있는 값들 scss로 변경.
px로 지정된 값을 디바이스별로 설정 필요.
image들 적절한 사이즈 변환 작업

Fixed #38 UI Layout

---

client/config.xml

In config.xml include  setting orientation to protrait
update description and author of widget

Fxied #51 Freezing portrait mode

---

client/package.json
client/www/js/app.js

add cordova-plugin-statusbar
disable StatusBar.overlaysWebView
set StatusBar.backgroundColor to #22a1db

Fixed #50 status bar

---

client/config.xml
client/scss/ionic.app.scss

border 0 and background_size 0 on tabs
remove tab on config.xml
config.xml은 자동 생성되는 항목들이 있으니, 가능한 수정하지 말자.

Fixed #60 tabs의 border top line 없애기

---

client/www/templates/tab-dash.html

set overflow-scroll of ion-content to true

Fixed #68 sub scroll에서도 up/down swipe이 상위(ion-content scroll)에서 동작

---

client/www/js/controllers.js
client/www/templates/tab-dash.html

controller loading 이후에 timout 0를 이용하여, 지금 시간 바로 전부터 표시하게 설정.
현재시간 중심으로, 과거 8개, 미래 16개가 나오게 설정
hr line 끊어져 보이는 문제 수정.

Fixed #76 set x of scroll when loaded

---

client/.gitignore
client/ionic.project
client/www/js/controllers.js
client/www/templates/tab-dash.html

add proxies for rest api in ionic.project
weather data를 parsing하는 function를 생성.
실행할때, 위치정보와, 날씨 정보를 업데이트하고, pull to refresh할때 업데이트 한다.
todo : 오늘 기준으로 데이터 정리, 갱신시간이 넘어서는 경우에 갱신

Fixed #62 Server로 지역정보 전달하고, 시간별, 일간 날씨 정보 가지고 오기

---

server/models/forecast.js
server/models/test.js
server/models/town.js
server/utils/initForecasteDataToMongo.js

town, forecase(base데이터)관련 data object commit

#10 Data Object Commit

---

client/www/js/controllers.js
client/www/templates/tab-dash.html

save at localStorage
set false to enableHighAccuracy of geolocation

Fixed #85 위치정보와, 날씨 정보를 디바이스에 저장하기

---

client/ionic.project
client/scss/ionic.app.scss
client/www/js/app.js
client/www/js/controllers.js
client/www/templates/tab-dash.html

#78 차트의 디자인 시안 적용 작업
* 현재 시간 Circle로 표시
* 오늘의 최고 최저 온도 표시
* 선 스타일 변경

#78 차트의 디자인 시안 적용 작업

---

server/models/forecast.js
server/models/test.js
server/utils/initForecasteDataToMongo.js

1. initForecastDataToMongo Schema modified
2. Current array data in ForecastData limitation is define

#10 Current data limitation define

---

client/.gitignore
client/bower.json
client/ionic.project
client/www/index.html
client/www/js/app.js
client/www/js/controllers.js

add ionic-service-core, ionic-service-analytics
update ionic version to v 1.1.0
add www/lib on .gitignore

65 ionic services

---

client/www/js/controllers.js

Fixed #84 geolocation 정보 가지고 오기가 chrome과 android v4.4.2 에서 못 가지고 문제.

---

server/controllers/controllerManager.js
server/models/forecast.js

1. Controller use model modules
2. Modified Typing error( model/forecast.js)

#10 controller use model modules

---

server/models/forecast.js

- Added schema for the middle range forecast (target : MVP release)
- change line align.

#10 added the schema of the middle range forecast

---

server/controllers/controllerManager.js
server/routes/routeTownForecast.js

#117 fixed some bugs

---

server/models/forecast.js

1. for문으로 pop하는 부분을 slice로 변경
2. 데이터 업데이트시 제대로 저장되지 않는 부분 변경

#125 modified update sync to mongodb

---

client/ionic.project
client/scss/ionic.app.scss
client/www/js/controllers.js

change short object's key name to english.
timeTable length sets to 32.
change server url  to cloundfront.net

Fixed #122 server 측 변경사항에 맞게 수정

---

client/www/js/controllers.js

* $ionicPopup의 alert를 사용하여 Error Popup 추가

Fixed #103 error 발생시에 popup message 띄우기

---

client/www/js/controllers.js

모레 데이터에서 지금과 동일한 시간 이전의 데이터는 skip
data array가 32개 넘기전에 종료.

#127 short array의 시작 시간이 맞지 않는 문제

---

client/www/js/controllers.js

rest api protocol을 https로 변경함.
fix bug 사용하지 않는 과거 short data중에 skip 안되는 경우에 대하여 수정.

#142 ios9 emulator에서 위치 정보 갱신되지 않는 문제, #127 fix bug

---

server/controllers/controllerManager.js
server/routes/routeTownForecast.js

- When the server send short data to client, the count of short data is
always 16.
: It means that the start time stamp in the short data list that will
be sent always has 48hours gap with current time.

Fixed #138, Fixed #127 adjusted start time of short data in data array.

---

server/models/forecast.js
server/package.json

1. mongoose 버전 업데이트
2. mongoose 버전업데이트에 따른 쿼리 수정

#151 mongoose version update and then query modified

---

server/controllers/controllerManager.js
server/lib/collectTownForecast.js
server/routes/routeTownForecast.js
server/test/testCollectTownForecast.js

- added functions for Mid forecast data.
: to get mid forecast data from data.org
- added functions for shortest data.

fixed #53 added functions for Mid forecast.

---

client/www/js/controllers.js

getShortenAddress 계산시에 array 갯수로 구분하게 변경.
getWeatherInfo에서 addressArray parsing시에 array 갯수로 구분하게 변경
findDongAddressFromGoogleGeoCodeResults 에서 동, 읍, 면으로 구분하게 함.

Fixed #157 full address parsing을 하지 못하여, 배경화면만 나오는 증상.

---

client/scss/ionic.app.scss
client/www/js/app.js
client/www/js/controllers.js
client/www/templates/tab-dash.html

#133 현재 위치에 대한 주간날씨 지원
* 차트 & 데이터 영역 클릭 시 단기 예보와 주간 예보 정보가 번갈아가며 보여지도록 처리
* 주간 예보 정보를 위한 Template 기본 영역 잡기 & 샘플 주간 데이터 추가

#133 현재 위치에 대한 주간날씨 지원

---

server/controllers/controllerManager.js
server/lib/collectTownForecast.js
server/routes/routeTownForecast.js

- Added function that works to collect and distribute the Middle Range
Forecast for client.
: There is no organizing data for client yet.

fixed #134, fixed #153 Added the function of Middle range forecast

---

server/lib/collectTownForecast.js
server/test/testCollectTownForecast.js

tmx, tmn set valid values
(혹시 해당하는 날의 tmx, tmn value가 없다면 -50으로 처리)

#118 tmx, tmn set valid values

---

server/lib/collectTownForecast.js
server/test/testCollectTownForecast.js

Reverts WizardFactory/TodayWeather#171

Revert "#118 tmx, tmn set valid values"

---

server/controllers/controllerManager.js

- add the function that response the middle range forecast to client.

fixed #154, fixed #134 the function for middle range forecast

---

client/scss/ionic.app.scss
client/www/js/controllers.js
client/www/templates/tab-dash.html

dailyInfoArrary에서 t3h로 들어오는 데이터를 날별로 정리하여 저장.
parsePreShortTownWeather에서 dailyInfoArray data 생성.
parseMidTownWeather 에서 midData parsing하게 수정함.
add sky, pop, humidity
add weeklyChart css
지금 온도 갱신안되는 문제 수정.
현재위치 갱신안되는 문제 수정.

#163 주간날씨에서 하늘상태, 강수확률 및 습도 표시

---

client/www/js/controllers.js

googleapis에 language=ko 추가하여, 어떠한 언어를 사용해도,  한국어로 답변하게 만듬.

Fixed #177 ios system언어를 영어로 하는 경우 화면에 아무 것도 표시 되지 않는 문제

---

server/controllers/controllerManager.js
server/test/testCollectTownForecast.js

15시, 6시 이외의 데이터는 0으로 오는 부분 실제데이터로 수정 데이터가 아직 존재하지 않을 경우 invalid값으로 수정 (-50)

#118 tmx, tmn set valid data

---

client/bower.json
client/config.xml
client/package.json
client/www/index.html
client/www/js/app.js
client/www/js/controllers.js

apply https://github.com/apache/cordova-plugin-whitelist.git
add allow-navigation element
refer to http://docs.ionic.io/docs/cordova-whitelist
remove ionic-service-analytics, ionic-service-core on bower.json, index.html

#190 apply ionic-platform-web-client

---

client/bower.json
client/config.xml
client/hooks/after_prepare/011_update_config.js
client/package.json
client/www/js/controllers.js

ionicPlatform ready되면 checkForUpdates를 진행, 새로운 버젼이 있다면, ionicPopup.confirm을 실행, 사용자 확인후 deploy.update진행
iOS plist patch를 위해, 011_update_config.js 와, cordova-config-utils  추가
version 0.1.0 으로 변경 (config.xml, package.json)

#180 apply ionic deploy service.

---

server/controllers/controllerManager.js
server/test/testCollectTownForecast.js

tmx, tmn 를 현재 6시, 15시에만 들어오는 값을 다시 되돌려 놓음

#118 revert tmx, tmn value set 0 when specific time

---

client/www/js/app.js

#176 차트에 애니메이션 효과 추가
* time chart와 day chart의 데이터가 업데이트 되거나 shortForecast 값이 변경되면 차트에 애니메이션 효과를 주면서 보여지도록 처리함

#176 차트에 애니메이션 효과 추가

---

client/www/js/app.js

Fixed #133 현재 위치에 대한 주간날씨 지원
* 주간 차트 데이터에서 week가 "오늘"인 Bar에 빨간색 점 표시하도록 함

Fixed #133 현재 위치에 대한 주간날씨 지원

---

server/models/current.js

#202 modified wrong word in current

---

client/www/js/controllers.js

Fixed #196 Popup이 중복으로 표시되는 경우 닫히지 않는 문제
* 업데이트 체크가 끝난 후에 날씨 정보를 가져오도록 수정
* callback 대신 promise를 사용하여 중복으로 처리되지 않도록 함

Fixed #196 Popup이 중복으로 표시되는 경우 닫히지 않는 문제

---

server/models/current.js
server/utils/initForecasteDataToMongo.js
server/utils/initTownDataToMongo.js

#202 init base schema create script modified

---

server/models/midLand.js
server/models/midSea.js
server/models/midTemp.js
server/models/short.js
server/models/test.js
server/models/town.js
server/test/testCollectTownForecast.js
server/utils/initForecasteDataToMongo.js

1. 중기예보에 대한 스키마 정의
2. 중기예보 data object 구현

#155 Mid schema and data object

---

client/scss/ionic.app.scss
client/www/js/controllers.js

주간차트는 18개로 고정함
save dayTable, dayChart in localStorage
weeklychart is started from today -2
$cordovaGeolocation 대신에 navigator.geolocation 사용함

Fixed #220 화면 새로고침에서 주간날씨로 넘어가면, 에러나면서 주간차트 나오지 않는 문제.

---

server/controllers/controllerKmaIndexService.js

새로운 데이터를 생성할때 areaNo 저장하지 않는 문제 수정

#205 areaNo 저장 안하는 문제 수정

---

server/package.json
server/utils/initForecasteDataToMongo.js
server/utils/initTownDataToMongo.js

1. initTownDataToMongo에 path수정
2. run script 명령어 수정
3. initForecasteDataToMongo test.csv -> base.csv

#205 modified initTownDataToMongo path

---

server/controllers/controllerManager.js

스키마 변경으로 인한 소스 파일이름변경으로 나는 에러 해결함.
(forecast.js -> current, short로 변경)

#202 schema changing follow error

---

server/controllers/controllerManager.js
server/models/midLand.js
server/models/midTemp.js
server/package.json
server/utils/initForecasteDataToMongo.js
server/utils/initMidDataToMongo.js

1. forecast (temp, land) 데이터 mongodb에 저장.
2. mid 콜렉션 초기화

#155 mid forecast data save mongodb

---

client/config.xml
client/package.json
client/www/js/controllers.js

Fixed #233 android에서 위치를 찾지 못하는 경우 상세한 가이드

---

server/controllers/controllerManager.js

- To prevent error case
: If the server get the existed data on the db, it would be ignored.

Fixed #246 To prevent error case

---

server/app.js
server/controllers/kecoController.js
server/models/arpltnKeco.js
server/models/arpltnTownKeco.js
server/models/town.js
server/package.json
server/test/testKecoController.js

add tmCoord, kecoStationName to town
start하면 msrstrn 정보를 town에 추가함 10분마다 지역별로 측정소에서 계측된 정보를 arpltnKeco에 저장한다.
저장되면, town정보별로 arpltnTown 새로 만들어 저장한다

#225 provider에서 미세먼지 가지고와서 DB에 저장하기.

---

server/app.js
server/controllers/controllerShortRss.js
server/routes/routeTownForecast.js

- Sending RSS data
: When the server collect short data, it will use the short data from
RSS data.

Fixed #187 Sending RSS data

---

server/app.js
server/controllers/controllerKmaIndexService.js
server/controllers/lifeIndexKmaController.js
server/lib/lifeIndexKmaRequester.js
server/models/lifeIndexKma.js
server/routes/routeTownForecast.js
server/test/testControllerKmaIndexService.js
server/test/testLifeIndexKmaController.js
server/test/testLifeIndexKmaRequester.js

자외선, 체감온도, 식중독, 불쾌지수 만들었음.
각 지수를 object name으로 구분하게 했음.

Fixed #205 Provider 에서 상세날씨, 생활지수 등 부가 정보 가지고 와서 서버에 저장하기

---

server/controllers/controllerManager.js
server/routes/routeTownForecast.js

- The taMax&Min of the Mid forecast will be replaced by current data.

#264 MID's taMax, taMin are replaced by current

---

client/www/js/controllers.js
client/www/js/services.js

* loadStorage가 있는 경우에 undefined로 리턴되어 데이터 업데이트가 되지 않는 문제가 있어 true로 리턴 추가
* #194 이슈에서 수정한 conflict 코드 중 API에 파라미터 추가하지 않아 추가함
* 아래 두 가지 시나리오에 대해서 Flag로 처리
* (1) 이전 지역으로 데이터 요청 -> (2) 현재 위치 갱신 -> (3) 2번 결과가 동일 지역 -> (4) 1번 결과로 데이터 업데이트 & resolve 호출
* (1) 이전 지역으로 데이터 요청 -> (2) 현재 위치 갱신 -> (3) 1번 결과로 데이터 업데이트 -> (4) 2번 결과가 동일 지역 & resolve 호출

Fixed #255 동일한 지역에서, 데이터 갱신되지 않은 문제.

---

client/scss/ionic.app.scss
client/www/js/app.js
client/www/js/controllers.js
client/www/js/services.js
client/www/templates/tab-forecast.html
client/www/templates/tab-setting.html
client/www/templates/tabs.html

default color들을 TodayWeather에서 사용하는 색으로 변경
detail weather, setting page 추가
forecastType으로 short, mid, detail 분리
parse Mid, Short, Current 에서 detail에 사용할 데이터를 currentWeather에 추가
convertTimeString 는 service.js로 이동
SettingCtrl, TabCtrl 추가

Fixed #225 Fixed #269 detail weather, setting page 추가

---

server/models/current.js
server/models/midLand.js
server/models/midTemp.js
server/models/modelUtil.js
server/models/short.js
server/models/test.js

1. 과거데이터를 사용해서 중기데이터의 최저, 최고온도(midTemp) 과거값을 계산해서 가져옴
2. 과거데이터를 사용해서 중기데이터의 구름 상태를 계산해서 가져옴(midLand)
3. 중기데이터의 regId값을 변형할 util구현(modelUtil)

#264 use past data with middle forecast data

---

client/www/js/controllers.js
client/www/templates/tab-setting.html
server/app.js
server/controllers/kecoController.js
server/controllers/lifeIndexKmaController.js
server/lib/kecoRequester.js
server/routes/routeTownForecast.js
server/test/testKecoController.js
server/test/testKecoRequester.js
server/utils/convertGeocode.js

설정페이지에서 데이터 제공 정보를 보여주는 popup추가함

설정에서 정보창 추가. Fixed #281

---

client/scss/ionic.app.scss
client/www/js/services.js
client/www/templates/tab-forecast.html
client/www/templates/tabs.html

도시추가때까지, 검색탭 제거
큰 뼈대 프레임을  scss에서 조정할 수 있도록 추가하였음
미세먼지 parse방법 변경 - 문사와 다름

tab  추가에 따른 ui layout 변경. Fixed #285

---

client/www/js/controllers.js

add pm10, ultrv, sensorytem to summary

#99 상세날씨, 생활지수 내용을 summary에 넣기

---

server/controllers/kecoController.js
server/controllers/lifeIndexKmaController.js
server/lib/lifeIndexKmaRequester.js

lifeIndexKma에서 lastUpdateDate만 있고 data는 저장안된 경우가 있어서 save시에 예외처리 조건 추가
convertStringToDate 오류 수정

#263, 276 keco, lifeIndexKma 보정

---

server/controllers/controllerManager.js

for in  문법에서 초기화 하면 안되는 문제 수정.

node.js version에 따른 문법 오류 및 동작 오류 Fixed #283

---

server/app.js
server/controllers/kecoController.js
server/controllers/lifeIndexKmaController.js
server/routes/routeTownForecast.js

taskKmaIndexService 중지, 추후  client요청있을 때, 가지고와서 저장하고 갱신하는 형태로 변경
route에서 error발생시 죽는 문제 방지를 위해 try catch추가
db 쿼리 결과이후에 파싱중에 죽는 문제 방지를 위해 try catch 추가

#263, #276 keco, lifeIndexKma error 수정

---

client/config.xml
client/ionic.project
client/package.json

add crosswalk plugin
add cordova-plugin-inappbrowser

Fixed #147 add crosswalk #224 add inappbrowser plugin

---

client/www/js/controllers.js
client/www/js/services.js
client/www/templates/tab-forecast.html

new getTownFromFullAddress in WeatherUtil
rename parsePm10Grade to parsePm10Value
check arpltn of currentTownWeather before set correntForecast
fix param of parseUltrv

#269 상세날씨 Page 구현

---

server/models/midLand.js
server/models/midTemp.js

중기데이터에서 지역관련 스키마 삭제 및 그에 해당하는 소스 수정

#264 midLand, midTemp schema change

---

client/www/js/controllers.js
client/www/js/services.js
client/www/templates/tab-search.html

#194 도시 관리 및 설정 UI

---

server/models/current.js
server/models/forecast.js
server/models/midLand.js
server/models/midTemp.js
server/models/short.js
server/models/test.js
server/routes/routeTownForecast.js

1. current 를 이용한 short 과거데이터 바꾸기(개발중)
2. route를 이용해 서버와 연결
3. current저장에 동작되지 않는 부분 수정

#266 #261 modificated bug

---

client/scss/ionic.app.scss
client/www/templates/tab-search.html

#194 city search layout

---

client/scss/ionic.app.scss
client/www/index.html
client/www/js/controllers.js
client/www/templates/tab-forecast.html
client/www/templates/tab-search.html
client/www/templates/tabs.html

.tabs-dark .tabs의 background-color: inherit
index.html - body에 bg 제거, ion-nav-bar 제거, 추후 재조정
ion-tabs에 ng-style적용, $ionicView.beforeEnter  event에서 $rootScope의 viewColor변경

Fixed #309 탭 색깔을 배경색깔과 동일하게 맞추기 

---

client/bower.json
client/config.xml

NSExceptionDomains추가
update version of ionic, ionic-platform-web-client

Fixed #275 iOS에서 ionic deploy로 업데이트 안되는 문제.

---

server/models/current.js
server/models/dateUtil.js
server/models/short.js
server/models/test.js
server/routes/routeTownForecast.js

1. short data중 과거데이터는 current data를 사용함
2. 현재 short data의 t3h를 한시간간격인 t1h로 변경함
3. short data 오늘 기준 이전 데이터 개수가 16개에서 2일전으로 변경, 2일 후데이터까지 가져오게 만듬(오늘 이후 데이터는 3일 후로 변경예정)

#264 short data make 1hour and use current data

---

client/package.json
client/www/js/app.js
client/www/js/controllers.js

cordova-plugin-apple-watch에 포함된 NSUserDefaults 맵팅함수는 아래와 같습니다.
```c
applewatch.sendUserDefaults
```

#243 Added to share datas for apple watch

---

client/scss/ionic.app.scss
client/www/templates/tab-search.html

set height of city-list to 75% (iphone4 70%)
margin top and bottom of city list inset is 10px

#194 update city layout

---

client/config.xml

NSExceptionDomains에 cloudfront.net 추가

Fixed #324 bug로 날씨 정보를 못 가지고 오는 문제

---

client/www/js/controllers.js
client/www/js/services.js

appleWatch를 위한 setUserDefaults를 IOS Platforms에서만 하게 수정.
$http 함수에 대하여 모두 timeout 3000 으로 설정함.
상세날씨 정보를 못 가지고 오더라도, 날씨 정보 업데이트 되게 수정

상세날씨 Page 구현 #269 #331

---

client/www/js/services.js

tmx갱신하는 것에 대한 조건문 강화
ParseMid에서 dayInfo.tmx, tmn이 있는 경우에 이 값을 사용함 (mid 보다는 정확하고, current보다 부정확한 값임)

prePraseShort 오동작 수정  #333

---

client/config.xml
client/scss/ionic.app.scss
client/www/js/controllers.js
client/www/templates/tab-forecast.html
client/www/templates/tab-search.html
client/www/templates/tab-setting.html

fix layout error of iphone 6
change background-color when ionicview enter (not beforeEnter)
tab-forecast : background-color 속성을 inherit 로 주어 감빡임 제거
tab-search : set background-color to inherit, scroll false
tab-setting : set background-color to inherit, scroll false
#275 set NSAllowsArbitraryLoads to true and remove others

상세날씨 Page 구현 #269 ionic deploy error #275

---

client/www/js/controllers.js
client/www/templates/tab-forecast.html
client/www/templates/tab-search.html

GPS 정보에 의한 현재위치 도시의 경우에는 location mark 추가
add location-outline to address box city getting by gps
applewatch에서 오류 발생할 수 있는 부분 수정. #243

현재위치 정보의 경우 지역 아이콘을 넣어, 즐겨찾기 리스트와 분리 Fixed #339

---

client/www/index.html
client/www/js/app.js
client/www/js/controllers.js
client/www/templates/tab-forecast.html
client/www/templates/tabs.html

tab에 update btn를 추가했고, click이 발생하면, header가 나타나고 업데이트 진행됨
TabCtrl에서 ForecastCtrl로는 broadcast 사용하였음
Tab 위치 조정 : Search - Forecast - Update - Setting
tab-forecast.html에서 current weather info top padding 조정

pull-to-refresh를 버튼 또는 Tab Item으로 변경 작업 Fixed #82

---

client/www/js/services.js

parseCurrentTownWeather에서 parseSkyState에 Parameter 잘 못 넘기는 문제 수정

현재 날씨가 흐림에도, 맑음으로 나오는 문제 Fixed #343

---

server/controllers/controllerManager.js
server/models/shortest.js
server/models/test.js
server/routes/routeTownForecast.js
server/utils/initForecasteDataToMongo.js
server/utils/initMidDataToMongo.js
server/utils/initTownDataToMongo.js

shortest model과 router 연결 및 controller 연결

#202 add shortest data

---

client/scss/ionic.app.scss
client/www/js/controllers.js
client/www/templates/tab-forecast.html

scss에 412*732 추가
getWidthPerCol에 412추가
big-digit와 skystate 간격 비율 조정
iphone6+ 해상도에서 big-digit, sky state size조정

QHD 해상도 지원. Fixed #359

---

client/hooks/after_prepare/uglify.js
client/hooks/uglify-config.json
client/package.json

add cordoba-uglify
client/hooks/after_prepare/uglify.js, client/hooks/uglify-config.json 는 자동생성된 파일임.

js, html code optimize for production #348

---

chromeExtension/.gitignore
chromeExtension/manifest.json
chromeExtension/package.json
chromeExtension/uglify-config.json
chromeExtension/uglify.js
chromeExtension/www
client/config.xml
client/package.json

remove www
gulp를 사용하여 chrome용 dist를 생성하도록 변경
version 0.6.0으로 변경
set android-minSdkVersion to 14 on config.xml

크롬 확장 프로그램을 이용한 TodayWeather service 만들기 #206

---

android/res/xml/w2x1_widget_provider.xml
chromeExtension/manifest.json
client/config.xml
client/package.json
client/www/js/app.js
client/www/js/controllers.js
client/www/js/services.js

add file prefix on XXXSanitizationWhitelist for uglify
fixed error on ios(safari) - Can't find variable: chrome
fixed error decideTempIcon
extend convertMidSkyString

release version 0.6.1

---

chromeExtension/manifest.json
client/config.xml
client/package.json

service.js에 key 적용되지 않아서, 재 릴리즈 함

release version 0.6.3

---

client/www/js/app.js

* chart의 margin 처리 수정, 글자 표시 위치 조정

#346 일별날씨그래프가 화면에서 짤리는 증상

---

client/www/js/services.js

Mid Forecast Sky status Parsing Error Fixed #372

---

client/www/js/services.js

new convertKmaWsdToStr() on service.js
fixed wrong parameter of convertKmaPtyToStr, convertKmaRxxToStr in parseShortTownWeather

바람이 강할 때, 현재날씨 요약에 추가하기. Fixed #374, #347

---

server/test/testConvertGeocode.js
server/utils/convertGeocode.js

address를 geocode로 변경시에 daum api로 먼저 시도,
실패시에 google api를 사용

대림2동, 신공덕동, 사당1동 에러 수정 #358

---

server/controllers/controllerManager.js
server/routes/routeTownForecast.js

This reverts commit ca90f1b5f32a08d2501c0b264405dab33e345c9c.

#155 bug fix"

---

client/www/js/controllers.js
client/www/templates/tab-search.html

#388 도시 검색에서 '신' 으로 시작하게 되는 경우 느려서 타이핑 불가한 문제.
* 검색 결과를 10개만 먼저 추가하여 보여주고 스크롤 시에 10개씩 추가하도록 함

#388 도시 검색에서 '신' 으로 시작하게 되는 경우 느려서 타이핑 불가한 문제.

---

client/config.xml
client/package.json
client/www/js/app.js
client/www/js/controllers.js

check window.applewatch before use it in app.js

release version 0.6.5

---

client/www/js/app.js

Fixed #223 주간 차트에서 라인 겹치는 문제.
* 시간 차트에서 마지막 데이터가 없는 경우가 있음
- 데이터가 없는 경우에는 점을 그리지 않도록 처리
* 주간 차트에서 도시 변경 시 데이터 갯수가 달라지는 경우가 있음
- 데이터 갯수에 따라 선과 최대, 최소 기온 텍스트를 추가, 삭제하도록 처리

Fixed #223 주간 차트에서 라인 겹치는 문제.

---

client/config.xml
client/package.json
client/www/js/controllers.js

release version 0.6.6

---

client/config.xml
client/package.json
client/www/js/controllers.js

Hot fix invalid key of daum api when getAddressFromDaum

release version 0.6.7

---

client/www/js/controllers.js

Fixed #356 server에서 데이터를 전달해주지 못하는 경우에 에러 팝업 동작하기
* 특정 도시에서 날씨 정보를 업데이트 하지 못한 경우 에러 표시
* 도시 검색 화면에서 도시 검색 후 날씨 정보를 업데이트 하지 못한 경우 에러 표시(도시 추가 안됨)

Fixed #356 server에서 데이터를 전달해주지 못하는 경우에 에러 팝업 동작하기

---

client/package.json
client/scss/ionic.app.scss
client/www/js/app.js
client/www/js/controllers.js

자체 수정한 cordova-plugin-admob 를 사용하여 admob연결
admob 설정 - setOptions -> create -> show
bar-header 영역을 같이 사용하며, bar 50px, tabs 40px로 조정
runAdmob를 false로 설정하여 동작안시킴

admob 달기 #367

---

server/config/config.js

server_mode를 gather, service로 분리 #299

---

client/www/js/services.js

add code that uses native geolocation for android

Android 현재위치 검색을 native 수준까지 올리기. Fixed #383

---

client/package.json
client/www/js/controllers.js

plugin add cordova-plugin-local-notifications
add example code for local notification

날씨 알림을 위한 local notification 지원 #234

---

server/controllers/controllerShortRss.js
server/test/testShortRss.js

remove timezone value
modify test script

Fixed #408

---

client/config.xml
client/package.json
client/www/js/controllers.js

release version 0.6.8

---

client/www/templates/tab-search.html

remove line-height of input box

도시검색에서 input box에 글자 짤리는 문제. Fixed #434

---

server/controllers/controllerManager.js

- bug fixed
: There are no shift() method in DB object.

#428 bug fixed

---

client/config.xml
client/package.json
client/www/js/controllers.js

release version 0.6.9

---

server/controllers/controllerManager.js
server/lib/collectTownForecast.js
server/models/modelShortest.js
server/routes/routeTownForecast.js
server/test/testCollectTownForecast.js
server/test/testControllerManager.js

ec15164
add lastUpdateTime to modelShortest
new testControllerManager.js
update shortest test code in testCollectTownForecast.js
update TOWN_SHORTEST to new url in collectTownForecast.js
fix mistypo of dataCompleted in collectTownForecast.js
new mCoord of CollectData.resultList item for retrying requestData
update organizeShortestData function for new KMA SHORTEST API
new callback param of saveShortest
new requestShortestData for retrying requestData
55cf16d
shortestList에서 현재보다 빠른 것만 추가
callback, return 빠진 부분 추가
fixed duplicate variable
fef0ef6
git repo에 없는 keydata.js에 대하여 주석처리

신 동네예보정보조회서비스 초단기예보 적용 Fixed #441

---

server/app.js
server/controllers/controllerManager.js
server/controllers/midRssKmaController.js
server/lib/collectTownForecast.js
server/lib/midRssKmaRequester.js
server/models/modelMidRss.js
server/routes/routeTownForecast.js
server/test/testCollectTownForecast.js
server/test/testLifeIndexKmaRequester.js
server/test/testMidRssKmaController.js
server/test/testMidRssKmaRequester.js
server/test/testShortRss.js

new test, requester, controller MID RSS KMA
getRegIdByTown에서 에러 발생시에 1 대신 Error object 전달하게 수정
CollectData.listPointNumber, listCityCode를 최신 정보로 업데이트
new getMidRss in routeTownForecast.js
test code에서는 describe만 남겨서 어떤 것이 있는지 알 수 있게 정리

KMA 중기예보 RSS 가지고 오기. Fixed #453

---

server/lib/midRssKmaRequester.js

#453 midRssModel의 모든 save가 완료되면, saveMidRss가 종료되도록 수정

---

server/controllers/controllerManager.js

: Change the rule to gather data.
. Use the async module.

#450 added async function on gathering data.

---

server/controllers/controllerManager.js

Change name from ‘dbShortestList’ to ‘dbMidList’ in the saveMid
function.

#450 Change variable name.

---

server/lib/midRssKmaRequester.js
server/models/modelMidRss.js

#453 midData 의 tmx, tmn을 taMax, taMin으로 변경

---

server/app.js
server/controllers/controllerManager.js
server/controllers/midRssKmaController.js
server/lib/collectTownForecast.js
server/lib/midRssKmaRequester.js
server/routes/routeTownForecast.js
server/test/testControllerManager.js

exclude 와 lean을 사용하여 메모리 줄여 openshift에서 동작하는것 확인.
requestData에서 한번에 200개씩 GET 하여 저장하도록 변경
mid rss kma 도 서버 초기 업데이트 이후에 동작하도록 변경.

memory optimize #469

---

server/routes/routeTownForecast.js

At first, it makes the template data list before getting short data
from DB.
And, it will be merged with short , current, rss..etc.
So, It always contains exactly count that means always send expected
count.

#429 fixed, #428 fixed

---

client/scss/ionic.app.scss
client/www/js/app.js
client/www/js/controllers.js
client/www/js/services.js
client/www/templates/tab-forecast.html

서버 에러에 따른 예외처리 개선
강수확률표시에서 과거의 경우에는 강우량/적설량표시하도록 변경.
시간별 날씨에서 그저께부터 모레까지 표시
일별날씨에서 하늘상태 오류 수정.

#259 맞추어 표시내용 개선

---

server/controllers/controllerManager.js
server/controllers/midRssKmaController.js
server/routes/routeTownForecast.js
server/test/testPastConditionGather.js

getMidFromDB midtype parsing error 수정.
mergeShortWithCurrent 에 tmn, tmx 구하는 코드 추가.
mid에 currents와 shorts추가하는 코드 추가.

current 데이터를 저장하여 지난 날씨에 활용하기. #259 Fixed #474

---

server/app.js
server/controllers/controllerManager.js
server/controllers/controllerShortRss.js
server/lib/PastConditionGather.js
server/routes/routeTownForecast.js

save시에 invaild한 데이터로 overwrite하지 않음
pastGather는 하루치 요청함
pastGather시에 invaild data가 저장되어 있는 경우에도 retry시도함.
mongodb 연결시에 keepAlive와 connectTimeoutMS설정.
routing시에 invaild data 예외처리 추가.
shortRss에서 shift로 데이터 짜르는 것을 slice로 변경

실황을 제대로 못 가지고 온 상황에 대한 보완. #480 #466

---

client/config.xml
client/package.json
client/www/js/controllers.js

서버 에러에 따른 예외처리 개선
강수확률표시에서 과거의 경우에는 강우량/적설량표시하도록 변경.
시간별 날씨에서 그저께부터 모레까지 표시
일별날씨에서 하늘상태 오류 수정.

release version 0.6.10

---

server/controllers/controllerShortRss.js
server/models/modelShortRss.js
server/test/testShortRss.js

1. rss에 pubDate 추가
2. 최신 갱신 일자 확인
- ram과 db 둘 모두 최신 데이터가 있을 경우 갱신하지 않도록 처리
3. rss의 ws 데이터 소수점 오류 수정
- 소수점 아래 값이 비정상적으로 길 경우 첫째 자리만 유지

Fixed #440 added pubDate in rss weather data

---

server/controllers/controllerManager.js
server/lib/PastConditionGather.js
server/lib/collectTownForecast.js

task 걸리는 시간 체크를 위해, log 추가.
HTTP request time을 5초로 변경, 동시 request 갯수를 400개로 제한.
PastConditionGather시에 한번에 400개까지 load하게 변경.

과거 실황 데이터 수집기 #471

---

server/controllers/controllerShortRss.js

- bug fixed
: When it uses the statusCode of response returned by get() method, it
should check that the statusCode is available.

#496 fixed, bug fixed

---

client/www/js/controllers.js
client/www/js/services.js

current.t1h, yesterday.t3h가 undefined 인지 체크하게 변경 (값이 0인경우에도 false됨)
#290 적용하면서, #377 시작 위치 조정에 에러 발생한 것 수정.

#259 side effect #290 side

---

client/config.xml
client/package.json
client/www/js/controllers.js

#375 #441 #449 신 동네예보정보조회서비스 적용
미세먼지에서 '나쁩'으로 표기 되는 문제. #433
#259 side effect #290 side

release version 0.6.11

---

server/app.js
server/config/config.js
server/controllers/controllerShortRss.js
server/lib/kecoRequester.js
server/newrelic.js
server/package.json

add newrelic
addMsrstnInfoToTown 성능 이슈로 mapSeries에서 mapLimit 400개로 조정.

#503 apm #498 keco

---

server/controllers/kecoController.js
server/controllers/midRssKmaController.js
server/routes/routeTownForecast.js

한개의 db object를 가지고 오는 경우에 limit(1)로 설정함.

client query에 대한 속도 개선 #506

---

client/www/js/services.js
server/routes/routeTownForecast.js

client/www/js/service.js
lgt가 -1일 때도 vaild되는 문제 수정.
server/routes/routeTownForecast.js
_getMax 조건 잘 못 된것 수정.

실황을 제대로 못 가지고 온 상황에 대한 보완. #480

---

client/www/js/services.js

항상 어제 0시에서 시작하기 때문에, 현재시간/3으로 과거 비교 index를 구함.

summary 어제온도비교 이상함 #502

---

client/scss/ionic.app.scss

line-height 제거로 popup-body가 겹쳐서 나오는 문제 수정.

#367 fixed bug about line-height

---

client/config.xml
client/package.json
client/www/js/controllers.js

어제 온도 비교가 잘못되는 문제 수정.
현재온도를 제대로 못 가지고 오는 경우 개선.
앱이름 한글 지원.
팝업창에서 글자 겹치는 문제 수정.
update local-notifications plugin

release version 0.7.1

---

client/www/js/services.js
client/www/templates/tab-forecast.html

set line-height on region-sum
fix wrong parseSensoryTem

currentSummary 표시 오류, 체감온도 문자 오류 Fixed #525

---

server/controllers/controllerShortRss.js

- log.err() is changed to log.error()

fixed bug - undefined function

---

client/www/js/services.js

sensorytem is used instead of string on summary

---

server/controllers/kecoController.js

keco controller.js에서 pm10Str과 pm25Str 생성

keco client에서 미세먼지 undefined로 표시 되는 문제. Fixed #513

---

server/routes/routeTownForecast.js

calculate sensorytem(feelslike) in getCurrent

현재온도로 체감온도 계산하기. Fixed #493

---

server/routes/routeTownForecast.js

disjoined getShortRss
routeTownForecast.js 내용 중에
getShort에서 getShortRss를 분리했습니다.

Fixed #464

---

client/scss/ionic.app.scss
client/www/js/services.js
client/www/templates/tab-forecast.html
client/www/templates/tab-search.html

detail weather css renew like city search
change server url to todayweather.wizardfactory.net
add guide message for remove city on favorite list.

초미세먼지 지원 #537

---

server/controllers/midRssKmaController.js
server/routes/routeTownForecast.js

코드 내의 참조 오류를 수정했습니다.
code.cityCode를 regId로 변경

Fixed #534

---

server/routes/routeTownForecast.js

short rss에서 tmx 처리 오류. Fixed #541

---

server/lib/PastConditionGather.js

_checkBaseTimeByCoord는 currents collection이 비어도 생성업데이트 가능하게 수정.
_checkBaseTime는 죽지 않게만 수정

currents model이 비어 있는 경우에 _checkBaseTimeByCoord에서 죽는 문제. Fixed #510

---

client/www/js/controllers.js

timeOut를 사용하여 async하게 drawing하게 변경

iOS 재실행시에 처음으로 일별날씨 가면 화면 짤리는 문제. Fixed #544

---

server/controllers/controllerManager.js
server/controllers/kecoController.js
server/routes/routeTownForecast.js
server/utils/convertGeocode.js

- Some bugs is fixed.
: 세종특별자치시 에대한 예외처리.
: error on the arpltn
: error processing on the convertGeocode
: change the sequence when it need to convert the coord.

#516 Fixed Bug

---

client/www/js/services.js
client/www/templates/tab-forecast.html
server/controllers/kecoController.js

sensorytem과 t1h가 다른 경우에만 summary 추가.
pm10,pm25가 0보다 큰 경우만 보여줌 on detail-weather
parsePmXXInfo에서 value가 0보다 미만이면 '없음'으로  반환

#537 prevent side

---

client/www/templates/tab-forecast.html

-10도 이하이며, t1h와 다른 경우에 추가.
detail weather에서는 0도 미만이면 표시.

#493 체감온도 표시 기준 수정.

---

server/controllers/controllerManager.js
server/routes/routeTownForecast.js
server/test/testConvertGeocode.js

- Added the comment for ‘세종특별자치시’
- Added the ‘return’ in front of calling callback() when the error
occurs by convertGeocode.
- Blocked the test code on convertGeocode, because there is no key to
get the code by using DAUM.

#516 Fixed bug, Added comment

---

client/scss/ionic.app.scss
client/www/js/controllers.js
client/www/js/services.js
client/www/templates/tab-forecast.html
client/www/templates/tab-search.html

city-search, setting에서 forecast로 이동할떄, reddot커졌다가 작아지는 문제 수정.
광고 뒤에 광고에 대한 안내문구 추가함.
시간 표시 포멧 수정.

city-search에서 삭제버튼 나올때 row크기 변경되는 문제 수정.

---

server/routes/routeTownForecast.js

- Added the function that merges the shortcurrent with shortest data.

#368 Added merging short/current with shortest

---

client/www/js/services.js

pm10, sensoryTem, ultrv가지고 오는 code제거.
어제오늘, 미세먼지(보통, 좋음은 우선순위 낮음, 나쁨이면 높음), 초미세먼지(미세먼지랑 같이 나오지 않음), 강수량/적설량, 자외선, 체감온도/바람
우선순위 높음이 한개면 어제오늘만, 우선순위 높은 것이 없으면 어제오늘,미세먼지.

region(current) summary 우선순위 조정. Fixed #514

---

client/www/js/controllers.js
client/www/templates/tab-forecast.html
client/www/templates/tab-search.html

font, image size들의 최대 크기 지정.
광고 메세지 주석 처리.
날씨 정보에서 상단 현재 날씨 정보들 중간에 오게 조정.
search 에서 image size 고정.

iPAD 지원 #561

---

server/lib/collectTownForecast.js

error 발생시에 recvFail event 전달안하는 문제 수정.

midSea request error 발생시에 hangup 걸리는 문제. Fixed #564

---

server/controllers/midRssKmaController.js

저장을 tmn,tmx가 아니라, taMin, taMax로 변경하고, controller에 반영하지 않아, mid 갱신안된 문제 수정.

#453 midData 의 tmx, tmn을 taMax, taMin으로 변경 에 따른 오류

---

client/config.xml
client/package.json
client/www/js/controllers.js

iPAD 지원 #561
region(current) summary 우선순위 조정. Fixed #514
city-search에서 삭제버튼 나올때 row크기 변경되는 문제 수정.
iOS 재실행시에 처음으로 일별날씨 가면 화면 짤리는 문제. Fixed #544
초미세먼지 지원 #537
currentSummary 표시 오류, 체감온도 문자 오류 Fixed #525

release version 0.7.2

---

server/app.js
server/controllers/controllerManager.js
server/lib/kecoRequester.js
server/routes/routeGather.js

성능 측정에 용이하게 자기 자신에 query하는 형태로 변경함
/gather/xxxx 형태로 요청이 오면 수집함.
keco log 정리.

#492 task array에 put하는 방식에서 query로 변경.

---

server/app.js
server/bin/www

gather mode일 때, server timeout을 24hours로 변경.
remote keep alive message

#492 Fixed socket hang up

---

client/www/js/services.js
server/controllers/kecoController.js

미세먼지 정보가 없는 경우에는 summary에 넣지 않음.

미세먼지 정보가 없는 경우 "없음" 대신에 "-" 로 변경. Fixed #569

---

server/config/config.js
server/lib/log.js
server/package.json

#135 add logentries node module

---

server/app.js
server/controllers/controllerManager.js
server/routes/routeTownForecast.js
server/utils/convertGeocode.js

getDaySummaryList할 때, reh array가 비는 경우에는 그 날 데이터는 없다고 관주하고, 리스트에서 제거.

#579 reorganize log

---

android/res/layout/w2x1_widget_layout.xml
android/res/xml/w2x1_widget_provider.xml
android/src/net/wizardfactory/todayweather/widget/JsonElement/WeatherDailyDataElement.java
android/src/net/wizardfactory/todayweather/widget/JsonElement/WeatherMidDataElement.java

* widget 레이아웃 조정
* DailyDataElement 생성 시 죽는 문제 수정(reliability가 없는 DailyData가 있음)
* 이전 Commit 시에 새로 생성한 파일이 push 되지 않아 다시 push

#423 android widget 개선

---

client/config.xml
client/package.json
client/www/js/controllers.js

release version 0.7.3

---

server/config/config.js
server/routes/routeTownForecast.js

#556 remove ram mode

---

server/app.js
server/controllers/controllerManager.js
server/controllers/lifeIndexKmaController.js
server/lib/lifeIndexKmaRequester.js
server/routes/routeGather.js
server/routes/routeTownForecast.js

get lifeindex(생활지수) from KMA API
다른 생활지수는 추후에 controller내에서 계산해서 append할 예정.
change findOne to find in lifeIndexKmaController.js
db에 데이터가 없는 경우 appendFromKma하지 않고, 에러 처리함 -> 항상 requester에 의해 저장된 데이터 사용하게 변경.

#263 fsn(식중독), ultrv(자외선)지수

---

server/controllers/controllerManager.js
server/controllers/controllerShortRss.js

데이터가 저장된 시점에 log를 남겨, 데이터 받고 저장하는데 걸린 시간 체크.

#579 log when data saved

---

client/www/js/app.js
client/www/js/controllers.js
client/www/templates/tab-forecast.html

#291 차트의 width를 데이터 갯수에 맞게 후 지정할 수 있게 개선
* time data와 day data의 갯수에 맞게 scroll 되는 content width를 변경

#291 차트의 width를 데이터 갯수에 맞게 후 지정할 수 있게 개선

---

client/config.xml

disable ShowSplashScreenSpinner
set target-device to universal
set StatusBarStyle to light

#584 disable FadeSplashScreen

---

client/bower.json
client/www/js/app.js

ionic-bower version 1.1.1로 변경.
- #544 화면 짤리는 문제 해결, #291 ios에서 처음 화면 안나오는 문제 해결
admob test ad를 true로 변경함.

Fixed #544  Fixed #291 #367

---

server/config/config.js
server/controllers/controllerManager.js
server/package.json
server/routes/routeGather.js
server/test/Invalidate/testInvalidateCloudFront.js
server/utils/awsCloudFront.js

: Added a function to clear the cache on the CouldFront.

#568 Add a function to clear the cache on the CloudFront

---

client/www/js/app.js
client/www/js/services.js
server/lib/kmaTimeLib.js
server/lib/lifeIndexKmaRequester.js
server/routes/routeTownForecast.js

client
tmx, tmn 이 -50이 아닌경우에 사용하도록 단순화.
t3h을 tmx, tmn으로 보정하는 코드 제거.
server
add kmaTimeLib
adjustShort에서 t3h와 tmx,tmn 값 들에 대한 보정만 추가, rest api version 추가 후 적용 필요.

#366 adjust short forecast

---

server/controllers/controllerManager.js
server/lib/collectTownForecast.js

이전에 shortest request time을 40분에서 35분으로 변경하면서, 한시간 전 데이터 요청하게 되는 문제 수정.

API 미동작시에 대응할 crawler 제작. #594

---

client/www/js/app.js

#261 지금 온도를 표시하는 빨강점을 t3h위에 찍을 것이 아니라, 1시간단위로 표시.
* 현재 온도는 실제 온도로 적용하지 않고 3시간 단위의 선 위에 3등분을 하여 현재 시간에 해당하는 좌표에 빨강점을 찍도록 함
* warning 제거

#261 지금 온도를 표시하는 빨강점을 t3h위에 찍을 것이 아니라, 1시간단위로 표시.

---

server/routes/routeTownForecast.js

과거 데이터 생성 중에 '맑고 눈'이 되는 경우 있음. #610

---

client/www/js/services.js

현재 표시 레드 포인트 1시간단위로 이동. #261
"지금" 대신에 원래 시간으로 표시.

지금 표시를  시간으로 표시.

---

server/lib/MET/metRequester.js
server/test/testMET/testMetRequester.js
server/utils/convertGeocode.js

- Added new module to get world weather data by using MET service
provider.
: It’s basic code to get data.

#599, Added MET module

---

client/package.json
client/www/js/controllers.js
client/www/templates/tabs.html

Fixed #527 날씨 공유 기능
* Forcast 탭에서는 현재 보여지는 날씨 정보를 공유하고 도시 검색과 설정 화면에서는 앱 다운로드 경로만 공유

Fixed #527 날씨 공유 기능

---

server/controllers/controllerTown.js
server/lib/lifeIndexKmaRequester.js

lifeIndexKmaRequester.js
for 이후 add 잘 못하는 오류 수정.
controllerTown.js
getLifeIndexKma에서 short, dailyData에 저장된 정보를 current에 저장함.

Fixed #623 do not add lifeIndex of schema

---

client/www/js/services.js
server/controllers/controllerTown.js
server/controllers/controllerTown24h.js
server/controllers/lifeIndexKmaController.js

client
service.js
url에 version 추가
remove getPositionHours
getDayString 변경.
server
controllerTown24h.js
class의 self를 살림. adjustShort에서 0600, 1500에 tmx, tmn넣는 코드 제거.
tmx, tmn의 동일할때, 이전 타임과, 이후 타임에 대한 t3h를 비교하여 결정.

Fixed #602 익일 0시를 당일 24시로 변환

---

client/www/js/controllers.js

fixed #527 error utf8 code

---

client/www/js/app.js
client/www/js/controllers.js
client/www/js/services.js

시간별 차트에서 현재위치를 알리는 레드 포인터 위치 조정.
현재 하늘 상태가 제대로 표시하지 못하는 문제 수정.

fixed bug #602 0h to 24h

---

client/config.xml
client/package.json
client/www/js/controllers.js

시간별날씨의 시간단위를 0시~21시에서 3시~24시로 변경.
날씨 공유 버튼 추가 (예보와 업데이트 버튼은 하나로 변경)
최대,최저온도 시간대 오류 수정
밤에도 현재 하늘 상태가 낮으로 표시되는 문제 수정
과거데이터 중에 하늘상태가 맑고 눈으로 되어 아이콘 안나오는 문제 수정.
MET module 추가.
OWM api 추가.

release version 0.7.6

---

client/www/js/app.js

개발시에 ionic analytics 업데이트 안되게 주석 처리

---

server/test/testConvertAddress.js
server/utils/convertAddress.js

- getting the address by using geocode

#625 fixed, added getting address module

---

server/controllers/controllerManager.js
server/controllers/controllerShortRss.js
server/routes/v000001/routeGather.js

ShortRss 관련하여 콜백을 받을 수 있도록 수정하였습니다.
테스트를 했습니다만, 전체적인 이해력이 떨어져 실수가 있지않을까 걱정입니다.
확인부탁드립니다.

Fixed #477 Added callback function for ShortRss

---

server/controllers/controllerShortRss.js
server/controllers/controllerTown.js
server/controllers/controllerTown24h.js

modified comment in controllerShortRss.js
1. 유효하지 않은 최신 단기예보 데이터를 삭제하였습니다.
2. controllerShortRss.js에서 직전에 commit한 내용에서 상황에 맞지 않는 주석을 수정하였습니다.

Fixed #483 remove invalid recently short data

---

client/www/js/services.js

makeSummary에서 어제 오늘 온도 비교 오류. #647
현재 날씨와 비교할 yesterdayIndex 변경

Fixed #647 현재 날씨와 비교할 yesterdayIndex 변경.

---

client/www/templates/tab-forecast.html

Fixed #570 add humidity in detail weather

---

client/ionic.project
client/www/js/services.js
server/controllers/controllerTown24h.js

backend
v000705에서 overriding한 _makeBasicShortList 제거 short는 24시~24시 총 41개 사용함.
frontend
makeSummary를 위한, yesterdayIndex를 수정.
etc
ionic.project의 proxyUrl 변경.

Fixed #663 _makeBasicShortList의 overriding 제거.

---

server/controllers/controllerShortRss.js

mainTask에서 mapSeries 대신에 map을 사용하게 변경.
570 line에서 cb(err)만 던지면, function(item,cb)에서 item이 cb가 되어 버림.
rss의 경우 많은 쿼리에 대한 제약이 약하기 때문에 재시도 시간을 1min에서 3sec로 변경함.

Fixed #477 optimize short rss time

---

client/www/js/controllers.js
client/www/js/services.js

#668
statusbar 24dp인 경우에 대한 처리 추가.

#668 mashmallow statusbar size

---

client/config.xml
client/www/js/app.js
client/www/js/controllers.js
client/www/templates/tab-setting.html

status bar를 on/off할 수 있게 설정에 추가.

Fixed #670 status bar on/off

---

server/app.js
server/controllers/controllerManager.js
server/controllers/controllerTown.js
server/lib/collectTownForecast.js

shortString 데이터 모두 사용하게 변경.
collectdata timeout 연장.
shortest에서 데이터가 invalid한 것이 오는 경우 에러 표시하게 함.

#674 extend save data of short, shortest

---

client/config.xml
client/www/templates/tab-setting.html

#547 
사용자가 의견보낼수 있는 mailto 추가
클릭 의미로 > 아이콘 추가 하였음.

#547 mailto

---

client/bower.json
client/www/js/app.js
client/www/js/services.js

#266 getDayString에서  array 변경하고나서 index 처리 오류 있었음.
etc
update ionic-platform-web-client to 0.6.1 (에러나기 시작해서 업데이트 함, 0.7.1 version은 deploy문제 있음.)
http get timeout을 늘림.
current.time을 parse에서 Number로 변경함.

#266 fixed bug of getDayString

---

server/controllers/controllerTown.js

#673 add fsn to Summary when fsnGrade is over 2

Fixed #673 add fsn to Summary

---

client/www/templates/tabs.html

set forecast icon to android-sunny in tabs

set forecast icon to sunny in tabs

---

client/www/index.html

* Google Analytics 실행 코드 추가 - js 경로 앞에 "http:" 추가함

#489 사용자 사용패턴 분석할 수 있는 토대 마련

---

client/bower.json
client/www/index.html
client/www/templates/tab-forecast.html

img source가 변경되는 경우 ng-src로 변경.
css, js lib들 minify된 file로 변경.
remove xml2json

fixed img src error

---

client/www/js/controllers.js

#685 - 0.6.1 이전에 Ionic.User.anonymousId() 사라짐
추후 사용자 로그인 관리 필요함.

remove identifyUser()

---

client/www/templates/tab-forecast.html
server/controllers/controllerManager.js
server/controllers/controllerTown.js
server/controllers/kecoController.js
server/lib/kecoRequester.js
server/models/modelMsrStnInfo.js
server/test/testKecoController.js
server/test/testKecoRequester.js

gather에서 msrStnInfo(측정소정보)와 arpltn(측정소별데이터)정보를 저장하고, service에서 client요청이 오면, geo 정보를 바탕은 측정소를 뽑고, 측정소별 데이터를 뽑아서 합쳐서 전달.  
frontend
stationName 표시
backend
**new** modelMsrStnInfo.js, getAllMsrStnInfo(), getArpLtnInfo(), getMsrstnList(), parseMsrstnList(), saveMsrstnList(), getGeoInfo(), completeGeoMsrStnInfo(), getAllMsrStnInfo()
**remove** addMsrstnInfoToTown(), loadTownList(), updateTownArpltnInfo(), saveArpltnTown()
**rename** parseMsrstn() to getStationNameFromMsrstn()

#435 get AQI by GEO info

---

server/controllers/controllerTown.js
server/controllers/lifeIndexKmaController.js

이슈 #256 중 불쾌지수만 먼저 추가하여 Commit 합니다.

Fixed #256 added discomfort index

---

client/config.xml
client/package.json
client/www/js/controllers.js

탭 날씨 아이콘 변경
식중독지수 “경고”이상인 경우 표시
의견보내기 추가
android mashmallow에서 폰트 너무 큰 문제 수정.
상세날씨에 습도 추가.
데이터 검증부분 서버로 이동하면서 모바일 성능 약간 개선

release version 0.7.7

---

server/controllers/controllerTown24h.js

"fail to get daySummary"에 대하여, overriding되면서 log level 조정안된 코드 수정.

modify log level

---

server/test/testControllerTown.js

Fixed testControllerTown.js

---

server/controllers/controllerTown.js

Fixed #574 fixed float sum

---

server/controllers/controllerTown.js

fixed conditional statement of RxxToStr

---

server/controllers/controllerTown.js
server/controllers/lifeIndexKmaController.js

#256 added Decomposition index

---

client/www/templates/tab-forecast.html

check invalid data of wsd

---

README.md
client/bower.json
client/www/index.html
client/www/js/controllers.js

#489 사용자 사용패턴 분석할 수 있는 토대 마련.
* GALocalStorage을 사용하여 android에서 GA 기록됨

#489 사용자 사용패턴 분석할 수 있는 토대 마련.

---

README.md
client/www/js/app.js
client/www/js/controllers.js

* $stateParams을 사용하여 url에 param 추가
* "/tab/forecast?fav=1" 과 같이 fav에 index 번호를 넣어주면 city로 로딩

#619 즐겨찾기된 도시로 바로 이동가능한 url path 설정.

---

client/www/js/controllers.js
client/www/js/services.js

* localStorage에 마지막 로딩한 cityIndex를 저장하고 앱 실행 시 저장한 cityIndex로 로딩하도록 함

#640 라스트 뷰 관리.

---

server/test/testKecoController.js

fixed test error of dust forecast

---

server/controllers/controllerTown.js
server/controllers/lifeIndexKmaController.js

#256 added heat index

---

server/controllers/controllerTown.js

#667 #594
current api에서 가지온 온 데이타까 현재시간 (40분 이후)일 경우 api 데이터 우선 사용.
rns와 pty가 다른 경우, 보정함.
summary update.

stn weather info를 current와 summary에 적용.

---

server/controllers/controllerTown.js
server/controllers/midRssKmaController.js

#384
add shortPubDate, shortRssPubDate, currentPubDate, shortestPubDate
add tempPubDate, landPubDate in midData

add public date time

---

server/controllers/controllerTown.js
server/controllers/kecoController.js

make str by khai, o3, no2, co, so2 grade

---

client/www/js/services.js

#600 #381
rename _getShortSiName -> _getShortSiDoName

shorten name for jaeju

---

server/controllers/controllerTown.js

#594
stn hourly에 의해 전달된 현재온도가 최고 최전온도보다 높으면 갱신

mid, short의 최고,최저온도 갱신.

---

server/controllers/controllerTown.js
server/controllers/kecoController.js

함수 잘못  호출하는 코드 수정.

---

server/controllers/kecoController.js

#704
keco station 못 찾는 경우 warning으로 변경

modify log-level

---

client/scss/ionic.app.scss
client/www/index.html
client/www/js/app.js
client/www/js/controllers.js
client/www/templates/tab-forecast.html
client/www/templates/tab-search.html
client/www/templates/tab-setting.html

#749
scss
상단 광고 관련 변수 제거, 레이아웃 사이즈 재조정, 하단 여백을 위해 tabs margin-bottom 과, has-tabs의 bottom 조정함.
statusbar color를 배경색에 맞추어 변경되도록 수정.
admob 하단 배치
forecast - 레이아웃 재조정하면서 iOS에서 상단에 붙는 문제가 있어 iOS이 경우에만 20px띄우게 했음, 데이터 갱신할때 spinner나오게 수정, 상태바랑 근접하기 때문에 시간 표시 제거함.
search - 검색부분을 ion-header-bar로 이동함.
index.html - 광고 표시 영역으로 bottom을 추가함.

ads move to bottom

---

client/www/templates/tab-forecast.html

#718
체감온도가 현재온도와 다른 경우 표시
체감온도 없고, 불쾌지수 60 이상인경우 불쾌지수 표시
초미세먼지 font size 조정
강수량의 mm font size 조정.
작은 글자로, 대기오염정보 가시거리 기압 일강수량,일적설량, 불쾌지수(체감온도 나온 경우이며, 지수 60이상일때), 식중독지수, 부패지수 추가.

각종 지수 및 폰트 사이즈 조정.

---

client/www/templates/tab-forecast.html

대기오염 측정소명 추가.

---

client/config.xml
client/package.json
client/www/js/controllers.js

ios는 0.7.8 이고, android는 0.7.9 입니다.
광고 하단으로 이동
마지막 도시 기억 기능으로 다시 시작하는 경우 최종 확인한 도시 표시하게 개선
미세먼지, 초미세먼지 측정소 표기
상세날씨 정보에 불쾌지수 추가(60이상인 경우에만 표시함), 체감온도 현재온도와 다른 경우에 표시하게 개선.
배경컬러 변경
일부 지역에 대하여 박무, 연무 등 추가 정보 제공
대기오염에 대한 상세정보 제공
현재 온도가 당일 최고 온도 넘는 오류 수정.
제주특별차지도 도 제주도 로 짧은 이름으로 표시.
앱아이콘 디자인 조금 변경

release version 0.7.9

---

client/scss/ionic.app.scss
client/www/index.html
client/www/js/app.js
client/www/js/controllers.js
client/www/js/services.js
client/www/templates/tab-forecast.html

#385
dailyData 파싱할때,  fromToday, fromTodayStr 추가.
etc
line-height를 normal로 변경.
debug mode 일때, 기본 url을 tw-wzdfac로 변경.

 미세먼지 예보를 시간별날씨에서 하루 표시에 추가.

---

client/www/templates/tab-forecast.html

#747 도시 변경 안내를 위한 좌,우 방향 아이콘 추가.
* 날씨 정보 좌우에 <, > 버튼 추가
* 처음, 마지막 도시 구분 없이 scrolling 됨

#747 도시 변경 안내를 위한 좌,우 방향 아이콘 추가. 

---

client/www/js/controllers.js

#752 #749
check window.StatusBar before calling status bar.

statusBar 호출전에 존재 여부 확인

---

client/www/js/controllers.js
client/www/js/services.js

#761 #385
week is 오늘 을 모두 fromToday is 0 로 변경.

fixed error about week is 오늘

---

client/www/js/controllers.js

#711
check keyboard visible when city list clicked

check keyboard visible when city list clicked

---

server/controllers/controllerManager.js
server/lib/kmaScraper.js
server/routes/v000001/routeGather.js

#754
check publishing date of stn weather info
5분에 한 번더 scraper를 호출함

check publishing date

---

server/models/modelMinuDustFrcst.js

add minu dust forecast index

---

client/www/js/controllers.js

#769
Updating time of changing statusbar color is little fast

Use loaded instead of enter

---

client/www/js/app.js
client/www/templates/tab-forecast.html

#769
ng-style 중 일부 one time binding으로 수정.
android에서 scrolling을 native로 변경.

ng-style 중 일부 one time binding으로 수정, android에서 native scrolling 사용.

---

client/www/js/app.js
client/www/js/controllers.js
client/www/js/services.js
client/www/templates/tab-setting.html

#409
set start page to forecast -> android에서 back 꼬이는 문제 수정.
util 에 guideVersion, showAd 추가.

make link for guide on setting

---

client/www/js/services.js

 fixed error parser of pty

---

server/controllers/controllerTown.js
server/controllers/lifeIndexKmaController.js

#256 added life indexs

---

server/models/arpltnKeco.js
server/models/lifeIndexKma.js
server/models/modelKmaStnDaily.js
server/models/modelKmaStnHourly.js
server/models/modelKmaStnInfo.js
server/models/modelMidForecast.js
server/models/modelMidLand.js
server/models/modelMidRss.js
server/models/modelMidSea.js
server/models/modelMidTemp.js
server/models/modelMinuDustFrcst.js
server/models/modelMsrStnInfo.js
server/models/town.js

#726
index들 몇 개 text로 변경함.
refer
A collection can have at most one text index.

Create Text Index

---

server/controllers/controllerManager.js
server/lib/kmaScraper.js

#754
stn hourly data가 쌓이면서 저장속도가 급속히 떨어짐.
10분까지늘었다가, 1개만 저장하기 시작하면서 10초정도 만에 모두 끝남.
server 처음 시작할때, kmaStnHourly 동작하지 않는 문제 수정.

kma stn hourly data를 한개만 저장함.

---

server/controllers/kecoController.js

#782
'2016-04-23 24:00'는 Date object로 바로 변환이 안되어 보완함.

set 24h to 00h and next date

---

server/controllers/controllerTown24h.js
server/routes/v000705/dailySummary.js
server/routes/v000705/index.js

#803
daily summary api for notification, native widgets

new api daily/town/

---

server/config/config.js
server/package.json
server/routes/v000705/index.js
server/routes/v000705/receiptValidation.js

#524
new api v000705/check-purchase

receipt validation server

---

server/controllers/controllerTown24h.js
server/routes/v000705/dailySummary.js

#803
dailySummary에 title, text, yesterday, today, tomorrow 로 정리
town요청시에도 dailySummary object 추가 (for social sharing)

update api daily/town/

---

client/package.json
client/scss/ionic.app.scss
client/www/index.html
client/www/js/app.js
client/www/js/controller.purchase.js
client/www/js/controllers.js
client/www/js/service.twads.js
client/www/js/services.js
client/www/templates/purchase.html
client/www/templates/tab-forecast.html
client/www/templates/tab-search.html
client/www/templates/tab-setting.html

#524 #791
You have to update cordova to 6.1.1
new modules - controller.purchase, service.twads

add cordova-plugin-inapppurchase, com.admob.plugin

---

server/controllers/worldWeather/controllerRequester.js
server/controllers/worldWeather/controllerWorldWeather.js

- added function which response result of adding geocoding to client.

#799 add responding client

---

client/package.json
client/www/js/controller.purchase.js
client/www/js/service.twads.js

#541
plugin 존재 여부 체크 하는 부분 수정.

fixed error checking plugin

---

client/config.xml
client/package.json
client/www/js/service.twads.js

#791
move to  appfeel/admob-google-cordova
this plugin need some time for create banner.
remove duplicate plugin info config.xml and package.json

move to  appfeel/admob-google-cordova

---

server/app.js
server/config/config.js
server/controllers/controllerPush.js
server/controllers/controllerTown24h.js
server/models/modelPush.js
server/package.json
server/routes/v000705/index.js
server/routes/v000705/routePushNotification.js
server/test/testControllerPush.js

#181
node-gcm, apn 추가.
ControllerPush.start와 apnFeedback을 정기적으로 실행.
notification이 나갈때는 requestDailySummary REST API로 데이터 수집해서 전달함.

push notification server

---

client/www/js/app.js
client/www/js/controllers.js
client/www/templates/tab-forecast.html

#791
chart size 조정을 hasTabs에서 parent element의 height로 변경.
forecast.html에서 forecastType을 ng-if 로 변경하면 short chart에서 점들이 한페이지 몰림.

modify trigger point of resizing chart

---

client/package.json
client/www/js/service.twads.js

#791
change admob plugin to new

Change admob plugin

---

client/package.json
client/www/js/controllers.js
client/www/js/service.applewatch.js

#243 #407
관련 코드는 service.appleWatch로 이동
실행시 에러 나는 경우가 있어 apple watch plugin 제거.
추후, 직접업데이트와 도시목록 설정까지 같이 하도록 변경예정.

isolation apple watch code and remove plugin

---

client/www/templates/tab-setting.html

enable scroll of setting menu

---

client/www/js/app.js

#824
앱 실행시 currentWeather.time 못 찾는 문제 수정.

fixed undefined error time of chart func

---

client/www/js/controllers.js

#602 #431
tablet (720 이상)의 경우 고정.
24시 추가로 21시 이후에 현재 시간대 안보이는 문제 수정.
화요일부터는 월요일이 아닌 일요일부터 표시 하게 수정.
iphone4,iphone5 7칸 표시.
width가 320일때, small text, image 크기 10%키움

chart start position

---

client/www/js/controllers.js

#828
ionic deploy 동작하지 않아 일단 코드 제거함.
isolation 한 코드는 이슈에 달아 두었음.

ionic deploy code out

---

client/package.json

remove deploy plugin

---

client/www/js/app.js
client/www/js/controllers.js
client/www/js/service.twads.js

#791
timeWidth 변경될때, chart 다시 그림.
tab 만들어질때, layout 재조정 - 없으면, 처음 가이드에서 나올때 문제됨
disable ad banner auto show  - 처음 가이드에서 광고 나와버림.

fixed layout error of admob

---

client/www/js/controllers.js

fixed string error

---

client/www/data/town.js
client/www/index.html
client/www/js/app.js
client/www/js/controllers.js
client/www/js/services.js

#769 
town.json -> town.js http.get이 상당 지연발생함.
remove transition of chart

#769 controllers 성능개선

---

client/www/js/controller.purchase.js

#807 #524
ios purchase info는 array가 아님.

fixed error about receipt data format

---

client/www/js/controller.purchase.js

#845 #807 #524
ios purchase info는 array가 아님.

잘 못 수정된 부분 고침

---

server/app.js
server/config/config.js

#181
change push notification sender to gather

change push notification sender

---

client/www/js/controllers.js

#820 #181
알람 설정안되어 있을 때, 팝업 안닫아지는 문제 수정.

check alarmInfo before removeAlarm

---

client/package.json
client/www/js/service.twads.js

#791
network state를 봐서 create banner함.
online으로 변경시에 create

freeze admob when no internet connection

---

client/scss/ionic.app.scss
client/www/templates/tab-search.html

#854
font-size 20px->17px
css  정리.

동이름이 길 경우 알림 아이콘 잘리는 문제

---

client/config.xml
client/scss/ionic.app.scss
client/www/js/app.js
client/www/js/controllers.js
client/www/js/services.js
client/www/templates/tab-forecast.html

#805
splash screen manual hide
주요화면 binding으로 변경.( '위치 찾는 중' 코멘트 제거함 - 갱신어려움)
ngShortChart, ngMidChart lazy loading으로 변경.
$compileProvider.debugInfoEnabled(false); 추가.
WeatherInfo.loadCities(), WeatherInfo.updateCities() run time 에 실행하게 변경.
console log 정리.

loading time 개선

---

client/bower.json
client/www/js/app.js
client/www/js/controller.purchase.js
client/www/js/controllers.js
client/www/templates/purchase.html

#524
products 정보를 못 가지고 오더라도 죽지 않고, page 표시되게 수정.
ios 8이전에는 in app purchase 동작 안함.

products가 못 가지고 온 경우 안죽게 개선

---

client/www/js/controller.purchase.js
client/www/js/controllers.js

#791
가이드에서 back key로 나오는 경우, purchase page에서 back button으로 나오는 경우 광고 나오게 수정.
광고 있는 경우 ios에서 layout 맞지 않아 padding div 추가.

광고 안나오는 경우 수정.

---

client/config.xml

#805
Maintain Aspect Ratio 사용.
Splash screen delay to 0.

splash screen 설정 조정.

---

client/www/js/controllers.js
client/www/js/services.js

시간별에서 과거시간에도 강수확률로 나오는 문제.

---

client/config.xml
client/package.json
client/www/js/controllers.js

가이드 추가 - 설정에서 간단한 가이드를 확인할 수 있습니다.
알람 설정 기능 추가 - 도시목록에서 알람 설정하세요.
불쾌지수 아이콘 추가
시간별날씨에서 간격 수정
광고 제거 기능 추가

release version 0.8.2

---

server/controllers/lifeIndexKmaController.js

#839
date에 맞지 않으면 다음날 데이터로 보고 skip.

생활지수 데이터가 없는 경우 다음 날짜로 넘김

---

client/www/js/services.js
server/controllers/controllerTown.js

#876
_getDaySummaryListByShort 시에 short를 모두 overwrite한다
단 t3h개 8개가 되지 않는 경우에는 적용하지 않는다.
decideTempIcon()에서 9이상인 경우 항상 Temp-10으로 설정함.

current가 없는 경우 대비 mid에 short를 full overwrite

---

android/src/net/wizardfactory/todayweather/widget/JsonElement/AddressesElement.java
android/src/net/wizardfactory/todayweather/widget/WidgetUpdateService.java

#874
check status of response of google api
use NETWORK_PROVIDER and GPS_PROVIDER for getting location
check addr of AddressesElement

check addr of AddressesElement

---

server/app.js
server/package.json
server/routes/v000803/index.js

v000803에 json web token으로 POST 요청을 처리하는 부분을 추가했습니다.
private키와 public키는 따로 전달해드렸습니다.

#8 apply jwt for post request.

---

client/www/js/services.js

#700
broadcast loadCompleteEvent after ionic platform ready

fixed bug permission popup for location when starting app

---

server/lib/lifeIndexKmaRequester.js

#888
set limit of _recursiveGetLifeIndex to 500
Fixed warning

out of memory when _recursiveGetLifeIndex

---

server/controllers/controllerManager.js

over retry count for kma short request

---

server/controllers/controllerManager.js

#732 #702
3분부터 10분간격으로 update하게 수정함.
과거 current 수집은 오랜 시간 걸리므로, task의 맨 마지막으로 이동 시킴.

keco가 update되지 않는 경우 발생함.

---

server/controllers/controllerTown.js

#594 #740
short의 tmx,tmn 업데이트할 때 같이 수정함.

aws stn hourly 쓸때 체감온도 안 맞는 문제.

---

server/routes/v000803/index.js

#8 #875
module exports가 없어서 죽는 문제 수정.
fixed warning

killed when app is starting

---

server/routes/v000803/index.js

#8 modified error objects

---

server/lib/kecoRequester.js

#895
255 line에 return 추가. (이슈원인)
추가로 빠진 부분 추가.
fixed warning

killed when ctprvn requests exceeded

---

server/controllers/controllerTown.js
server/routes/v000001/routeTownForecast.js

#899
v00001/town 에도 getKmaStnHorlyWeather를 적용하고, 데이터가 없는 경우가 발생하지 않게 조치.

current data가 없는 경우 android widget죽는 문제.

---

server/controllers/lifeIndexKmaController.js

#864 #839
source index는 고정한 상태에서 dest index만 변경해야 함

lifeindex 없는 경우 skip 오류 수정.

---

android/AndroidManifest.xml
android/res/drawable/divider.xml
android/res/layout/widget_provider_configure.xml

#763 Android widget 개선.
* configuration activity를 menu activity와 같이 투명 theme 적용
* configuration activity의 layout 수정

#763 Android widget 개선. 

---

android/src/net/wizardfactory/todayweather/widget/WidgetUpdateService.java

#763 Android widget 개선.
* 여러 개의 Widget을 설치한 상태일 때 업데이트 시에 각각 해당 도시로 업데이트 되도록 수정

#763 Android widget 개선.

---

client/www/js/controllers.js

#915
width뿐만 아니라,  height값도 지정해준다.

특정 webview version에서는 height값을 주지 않으면 실제 이미지 사이즈로 동작함.

---

server/controllers/controllerTown.js
server/controllers/controllerTown24h.js

#786
Short RSS를 pubdate가 기존 short보다 빠를 경우에만 overwrite하게 수정.
short->mid로 변경시에 wsd추가.
R06,S06을 3시간 단위로 변경.
wsd는 소수점1자리까지 계산.

풍속 추가, R06 S06을 3시간단위로 분리, RSS update룰 추가.

---

client/www/js/services.js

#575
읍면동, 상위레벨에 시,군,구인지 확인하는 코드 추가.

대학교 XX동 오류 수정

---

android/src/net/wizardfactory/todayweather/widget/JsonElement/AddressesElement.java

#575
읍면동, 상위레벨에 시,군,구인지 확인하는 코드 추가.

대학교 XX동 오류 수정 (android widget)

---

server/app.js
server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerRequester.js
server/controllers/worldWeather/controllerWorldWeather.js
server/models/worldWeather/modelGeocode.js

- Added a function for only one location weather data.
- Added a function for requesting weather when the client requests the
data first time.

#885, #799 Added a function for requesting weather

---

client/config.xml
client/package.json
client/www/js/services.js

일부 안드로이드폰에서 UI 깨지는 문제 수정.
위젯 적용시에 즐겨찾기 목록에서 도시 선택하게 개선
위젯에서 데이터 못 받는 경우에 죽는 문제 수정.
위젯에서 위치정보 못 가지고 오는 경우 알림표시

release version 0.8.4

---

server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerRequester.js
server/controllers/worldWeather/controllerWorldWeather.js

- Added sending WU data to client
: If the request is first time, it will request to collector and get
back the result to client.
: If the request is not first time, it will get WU data from DB and
send it to client.

#885, #799 Added sending WU data to client

---

client/scss/ionic.app.scss
client/www/templates/tab-search.html

#854
P element를 사용하여 공간 확보가 안되는 경우 축약되도록 함.
공간확보를 위해 40% 강제 배정함.

동이름이 길 경우 알람 아이콘 안보이는 문제

---

server/controllers/controllerTown24h.js

#418
title - 위치+시간+현재날씨
text - 오늘 or 내일 날씨

알림에서 오늘or내일 + 현재 날씨 표시

---

server/controllers/controllerTown.js

#378
_getTownDataFromDB 에러 수정.

routing에서 데이터를 못 가지고 온 경우 callback 안부르는 문제.

---

server/controllers/controllerManager.js
server/lib/lifeIndexKmaRequester.js
server/test/testLifeIndexKmaRequester.js

#697 #628
#697에서 AreaList를 자체 디비에서 가지고와서 갱신하게 함으로써, town db가 갱신된 경우에 따라서 같이 갱신되지 않음.
서버 실행시에 life index db를 갱신하게 수정.

Update life index db from town db

---

server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerRequester.js
server/controllers/worldWeather/controllerWorldWeather.js

- changed the log message
- Fixed the bug which uses unknown object
- Added the command for getting all weather data by using URI.
- sorting the WU data when data is sent to client.

#799, #885 fixed bug

---

server/lib/kecoRequester.js

#935
지역별 정보는 '예보없음'이 아닌 경우에만 업데이트하도록 변경함.

미세먼지 예보 저장하기 전에 validation 확인

---

server/controllers/controllerTown24h.js

#921 #786
예보 강수량이 있으나 실제 오지 않는 경우에 대하여 error log나오지 않게 수정.

예보 강수량이 있으나 실제 오지 않는 경우에 대하여 로그 수정.

---

server/controllers/controllerTown.js
server/lib/kecoRequester.js

#942
세종시를 지원하기 위해, Keco._sidoList에 세종 추가.
버그 수정
24시(0시) 30분 이전에 날짜가 이전날로 전달되는 문제 수정.

airkorea 세종 지역 지원

---

server/controllers/controllerTown.js

#168 #654
해당 시간 데이터가 없는 경우 이전 시간 데이터 사용.
yesterday의 동일 시간에 데이터가 없는 경우, 이전 시간 데이터 사용하게 변경.

풍향, 풍속, 습도, 온도는 해당 시간 데이터 사용하게 변경.

---

server/lib/lifeIndexKmaRequester.js

#962
callback 빠진 코드 추가.
#954
updateTimeTable 변경.
사용하지 않은 지수 주석처리.

provider로 부터 이전 데이터 받으면 멈추는 문제.

---

client/www/js/controllers.js
client/www/js/services.js

#960
window.innerHeight가 늦게 셋팅될때 문제가 발생함
innerHeight대신 screen.height를 사용하도록 변경함.
$cordovaPreferences 전에 $ionicPlatform.ready() 체크하는 코드 추가.

crosswalk에서 화면 깨지는 문제

---

client/www/js/controllers.js

#941
키보드 띄웠다가 닫으면 광고 중간에 나오는 문제 수정.
Forecast이상하게 나오는 문제 방지.

키보드 관련 이슈들

---

android/AndroidManifest.xml
android/res/values/strings.xml

#763
1x1 widget 제거 (manifast만 수정했음)
strings 수정 - 기본(?)파일을 한글로 해야 한글로 나옴.

android widget 개선.

---

server/controllers/controllerTown.js

#955
shortest 합칠때 date, time 비교 오류 수정.

shortest 합칠때 date, time 비교 오류 수정.

---

client/config.xml
client/package.json
client/www/js/services.js

release version 0.9.1

---

server/controllers/controllerManager.js

#593 #263
life index gathering을 10분으로 이동.

lifeindex gathering이 1시간 늦어지는 문제.

---

server/package.json

#787
update winston-logentries to 2.0.0

unknown log level : err 발생

---

server/controllers/controllerTown.js
server/controllers/controllerTown24h.js
server/lib/kmaTimeLib.js
server/routes/v000001/routeTownForecast.js
server/routes/v000705/dailySummary.js
server/routes/v000705/routeTownForecast.js
server/routes/v000803/routeTownForecast.js

#955 #953
current, short, shortest 모두 24시로 전환후 merge
merge 구조 개선 중.
shortest는 현재시간이 포함된 short object는 업데이트 하지 않고, 그 다음 object부터 업데이트.
current가 들어 있는 short object는 current 데이터에 기반해서, 강수량, 날씨를 표시함..
shortest를 short합칠때, rn1을 r06, s06으로 변환
routeTownForecast 함수들 순서 보정
skyAm, skyPm 못 만드는 경우 sky나 다른 sky로 대처하는 코드 추가.

recalculate current stnhourly shortest

---

server/controllers/kecoController.js

#978
object copy와 check하는 기준은 -1이 아니라 undefined로 변경함.

초미세먼지가 -1로 표시 되는 문제.

---

server/lib/lifeIndexKmaRequester.js

#984
lifeindex에 대하여 request count code추가.
중복 error 출력 제거.

식중독지수의 REQUESTS초과

---

client/www/js/controllers.js
client/www/templates/tab-forecast.html

#978
khai, pm10, pm25의 데이터가 없으면 대기정보에서 빼고,
상세대기정보에서는 정보가 없음을 표시.
대기정보가 없는 경우 표시 아이콘 변경.

초미세먼지가 -1로 표시 되는 문제

---

server/controllers/controllerKmaStnWeather.js
server/controllers/controllerTown.js
server/lib/kmaTimeLib.js
server/test/testKmaTimeLib.js

#974
object clone이 제대로 되지 않고, 빈 object가 만들어져서 발생한 문제임.
object clone방법 변경.

현재날씨 정보가 제대로 안나오는 증상.

---

server/controllers/controllerKmaStnWeather.js
server/controllers/controllerTown24h.js

#981 #977
두번째까지 못 찾으면 continue해서 cityWeather를 만나야 함.
0.1도 같이 미묘한 차이는 무시하게 0.5라는 padding을 줌.
makeDailySummary에서 stnWeather 없을때 발생하는 버그 수정.

적정 측정소 못 찾아서 실패하는 경우.

---

server/controllers/controllerManager.js
server/lib/lifeIndexKmaRequester.js

#984
ReturnCode가 1인경우 servicekey change하고, 한바퀴돌았다면 더이상 retry안함
에러가 여러번 오기 때문에 requests가 한텀 종료하고나서 키 변경함.

984 service key change

---

server/controllers/controllerTown24h.js

#932 #418
간헐적으로 데이터가 없을 수 있을므로 체크코드 추가.

check objects

---

server/controllers/controllerKmaStnWeather.js
server/controllers/controllerTown.js

AWS 분당구(수내동) 강수가 업데이트 되지 않음.

---

server/routes/v000803/index.js

v000803에 GET하는 경우 응답없음

---

client/www/js/controllers.js

diff 오류 수정.

---

client/www/js/app.js

#943
class name 을 잘 못 지정하여 발생한 문제 수정.

mid guide lines 중복 만들어지는 문제.

---

client/www/js/controllers.js
client/www/templates/tab-dailyforecast.html
client/www/templates/tab-forecast.html

#1010 도시가 하나 밖에 없는 경우 Swipe 아이콘 숨김 처리
* 도시가 하나 밖에 없어서 Swipe 동작이 발생하지 않는 경우에 Swipe 아이콘 숨김 처리

#1010 도시가 하나 밖에 없는 경우 Swipe 아이콘 숨김 처리

---

server/controllers/controllerManager.js

#1006
tasks가 특정 갯수 이상 쌓이면 process종료하여 재시작함.

kma stn hourly 가지고 오다가 멈춤.

---

server/controllers/controllerTown.js
server/controllers/lifeIndexKmaController.js

#1000 #990
grade의 보통은 2로 맞춤.
기온, 체감온도는 차이값을 grade로 사용.
좋음 상태는 2.5로 하여 보통보다 우선순위가 높고, 나쁨보다 낮음.

summary 개선

---

client/www/js/services.js

#982
getCurrentPosition을 platform ready로 감싸서 해결.

platform ready 전에 get current position불리는 문제.

---

server/controllers/controllerTown.js

#990
100mm/cm이 넘는 경우도 있으므로 제한 품.

강수/적설량 10이 넘으면 str생성시에 올림처리함.

---

client/www/js/app.js
client/www/js/services.js
server/controllers/controllerTown.js

#1023
3시 이내의 경우 currentIndex 다르게 구하게 변경.
diffDays는 모바일 시간이 아니라, server로부터 받은 current.date를 사용.
backend
yesterday를 찾을 때, 0시의 경우 24시로 변경하여 찾도록 수정.

1시~2시 까지 현재위치 표시 안되는 문제.

---

server/controllers/controllerTown.js
server/lib/kmaTimeLib.js
server/test/testKmaTimeLib.js

#998 #997
time으로만 비교 하기때문에 하루가 넘어가는 00시에 문제가 발생함.
Date object를 사용하여 비교하게 수정.

00시(24시)일때, stn hourly data가 overwrite되지 않는 이슈.

---

client/www/js/app.js

현재위치 포인트 크기 조건문 수정 빠진 부분 추가.

---

client/www/js/app.js

#1022
line을 그릴때, 현재시간 위치에 data object를 추가하고, 현재시간 위치 이후부터 데이터를 한칸씩 당겨서 위치를 잡는다.

시간별 차트에서 현재 온도에 맞게 라인 꺾기

---

client/config.xml
client/package.json
client/www/js/services.js

차트에서 현재온도 반영하게 개선
앱시작시 차트 좌우 스크롤 안되는 문제 수정.
측정소로부터 실시간 날씨 업데이트 되게 개선
맑은 날씨에서 번개오는 경우 아이콘 표시 안되는 문제 수정.

release version 0.9.5

---

server/controllers/controllerTown.js
server/controllers/controllerTown24h.js
server/routes/v000705/dailySummary.js
server/routes/v000705/routeTownForecast.js
server/routes/v000803/routeTownForecast.js

#1037 #1007
forEach->for 중간 return하기 위해서 변경.
req에 modelXXXX data가 없는 경우를 위한 예외처리 추가

req에 data가 없는 경우 예외처리.

---

server/lib/kecoRequester.js

#1050
rawData가 array가 아닌경우 에러로 처리함.

service error나는 경우 예외처리.

---

client/www/js/services.js

ios NSUserDefault 지원

---

client/www/js/app.js

#1055
data가 update될 때, initLine과 line 함수를 변경해버리는 오류가 있었음.

hourly weather data의 length가 변경될때, hourly temp chart에서 path가 끊어지는 문제

---

client/www/js/app.js
client/www/js/services.js

#1054
y domain생성시에 현재온도도 고려하게 수정.
버그
displayItemCount는 어제꺼부터 체크하게 수정
#1056 plugins 체크오류 수정.

hourly temp chart에서 current temp도 고려

---

server/controllers/controllerTown24h.js

#418
오늘내일 날씨 정보를 오전,오후로 표시함.
최고 최고온도 이모지 변경.
비오는날 현재 비가 안온 경우에 강수확률표시.

push message 개선.

---

client/www/js/services.js

#1062
background에서 10분이상 있는 경우 resume시에 날씨정보 갱신.

resume시에 날씨갱신.

---

client/www/js/controller.purchase.js

구독 갱신 기능 마무리.

---

server/app.js

#992
gather mode에서 push mode분리.

push service 분리

---

server/controllers/controllerTown24h.js

#418
android, ios에서 XXXArrowToBar가 표시안됨.

ArrowToBar 표시 안됨.

---

client/www/js/controllers.js

#1071
에러 발생시에 재시도 버튼이 들어간 팝업창 제공.

위치정보 못 가지고 온 경우 재시도 시나리오 개선.

---

client/www/js/app.js

#1076
timeChart, dayChart 갱신될때, hourly-table, day-table제거.

날씨아이콘,강수확률 업데이트 오류

---

client/www/js/controllers.js

#1071 #1062
Loading show 전에 popup있으면 close

Popup이 떠 있는 상태에서 resume되면 popup위에 loading이 뜨는 문제.

---

client/config.xml
client/package.json
client/www/js/services.js

팝업상태에서 resume시에 팝업창 위에 loading 나오는 문제 수정.
대기모드에서 돌아왔을 때, 자동 업데이트 지원.
날씨아이콘,강수확률 업데이트 오류 수정.
위치정보 못 가지고 온 경우 재시도 시나리오 개선.
가끔 차트 선이 안보이는 문제 수정.
알림 메세지 개선.
구독 갱신 기능 추가.
ios widget 추가.
android ui 개선.

release 0.9.8

---

client/bower.json
client/package.json
client/www/index.html
client/www/js/app.js
client/www/js/controllers.js
client/www/js/service.twads.js
client/www/js/services.js

#769
timeWidth, timeChart, dayWidth, dayChart 갱신시에 svg 없는 경우 무시.
주석및 안쓰는 변수 삭제
getCurrentPosition에서 maximumAge 사용 3sec
cordova-plugin-app-version 를 사용하여 version 정보 가지고 옴.

ionic.io, ngCordova 제거.

---

client/www/js/services.js

#958 사용자 분석

---

server/controllers/kecoController.js

#1089
arpltn이 없어도 죽지 않게 예외처리. line 146
fixed 3 warnings

대기 정보가 없는 경우 죽는 문제.

---

client/www/js/controllers.js

#1091
hourly forecast와 daily forecast가 분리 되면서 발생한 문제임.
조건문 수정.

일별날씨에서 날씨 공유 시에 날씨정보가 나오지 않는 문제.

---

client/scss/ionic.app.scss
client/www/js/controllers.js
client/www/templates/tab-forecast.html
client/www/templates/tab-setting.html

#1094
리뷰버튼 문구 변경.
업데이트 시각 추가.
대기정보 관련 문구 변경.
scss 0px -> 0으로 변경.

업데이트 시각 추가

---

ios/widget/Info.plist
ios/widget/TodayViewController.m
ios/widget/WidgetConfig.h

#1101
url 변경,  NSAppTransportSecurity 수정.

today extension url 오류

---

server/controllers/controllerPush.js

#1106
openshift에서 외부 요청이 없어 server가 내려가는 문제 방지

push server가 내려가는 문제.

---

android/src/net/wizardfactory/todayweather/widget/Provider/W2x1WidgetProvider.java
android/src/net/wizardfactory/todayweather/widget/WidgetProviderConfigureActivity.java
client/scss/ionic.app.scss
client/www/js/controllers.js
client/www/templates/tab-setting.html

#1105
업데이트 시간(분)을 설정하고 위젯에서 받아서 사용하게 개선.

android widgets 자동 업데이트 시간 설정

---

server/controllers/worldWeather/controllerWorldWeather.js
server/utils/dataTemplate.js

- Added data template
: First draft.

#1048 added template for world Weather

---

client/www/templates/tab-dailyforecast.html

일별날씨에 대기질 예보 개선

---

android/res/layout-v17/clock_and_current_weather.xml
android/res/layout-v17/clock_and_three_days.xml
android/res/layout/clock_and_current_weather.xml
android/res/layout/clock_and_three_days.xml
android/res/layout/current_weather_and_three_days.xml
android/res/layout/daily_weather.xml
android/res/layout/w1x1_current_weather.xml
android/res/layout/w2x1_current_weather.xml

위젯설정 화면 수정.

---

server/controllers/controllerTown.js
server/routes/v000705/dailySummary.js
server/routes/v000705/routeTownForecast.js
server/routes/v000803/routeTownForecast.js
server/test/testControllerTown.js

#970
routing시에 req.midData.dailyData 에 있는 정보를 확장함.
Fix warning.

dailyData에 sky, pty, lgt 정보 추가.

---

client/www/templates/tab-setting.html

설정화면 좌우 여백이 맞지 않는 문제.

---

android/src/net/wizardfactory/todayweather/widget/WidgetProviderConfigureActivity.java
client/config.xml
client/package.json
client/www/js/app.js

위젯 초기값정리.
0.9.9
ionic.io 제거.
iOS widget server address 오류 수정.
안드로이드 위젯 7가지 추가
안드로이드 위젯 자동업데이트, 투명도 조정 기능 추가.
날씨 데이터 업데이트 시각 추가.
권한 오류로 무한로딩걸리는 문제 수정.
화면설명 일부 변경
#970  fixed compile error
#958  disable setAllowIDFACollection

release 0.9.10

---

ios/widget/TodayViewController.m

#1126 #1112
ios widget에서 사용하는 address parser오류 수정.

service로 들어오는 request중에 잘못된 형식의 query가 있음

---

client/scss/ionic.app.scss
client/www/templates/tab-forecast.html

#1128 시간별날씨 차트에서 어제, 오늘 라인의 라벨 표시 추가

---

client/www/js/services.js

#1131
getWeatherInfo 에서 filter 제거

error get data when address is not in towns

---

client/www/js/app.js
client/www/js/services.js

#958 #769
app version이 plugin에서 읽어오면서 timing이 맞지 않아 문제 발생.

fixed app version

---

client/config.xml
client/package.json

특정 지역에서 날씨 정보 못 가지고 오는 문제 수정.
시간별날씨 온도 설명 추가.
new app icon/Splash Screen

release 0.9.12

---

client/config.xml
client/package.json
client/www/js/service.twads.js
client/www/js/services.js

#791
appfeel는 compile error발생함.
TheBosZ가 patch한 plugin을 fork해서 적용함.
AdUnit은 비어있을때 에러나서 의도적으로 넣은 것입니다. (다른 소스들이 남겨둔걸 볼때 문제되지 않아보여 남겼습니다.)

admob plugin 변경.

---

client/package.json
client/www/js/app.js

#1153
set usePreferredTextZoom to false

시스템 폰트 사이즈와 상관없이 font size 고정.

---

android/AndroidManifest.xml
android/res/layout-v17/clock_and_current_weather.xml
android/res/layout-v17/clock_and_three_days.xml
android/res/layout/air_quality_index.xml
android/res/layout/clock_and_current_weather.xml
android/res/layout/clock_and_three_days.xml
android/res/layout/current_weather_and_three_days.xml
android/res/layout/daily_weather.xml
android/res/layout/w1x1_current_weather.xml
android/res/layout/w2x1_current_weather.xml
android/src/net/wizardfactory/todayweather/widget/Provider/AirQualityIndex.java
android/src/net/wizardfactory/todayweather/widget/Provider/ClockAndCurrentWeather.java
android/src/net/wizardfactory/todayweather/widget/Provider/ClockAndThreeDays.java
android/src/net/wizardfactory/todayweather/widget/Provider/CurrentWeatherAndThreeDays.java
android/src/net/wizardfactory/todayweather/widget/Provider/DailyWeather.java
android/src/net/wizardfactory/todayweather/widget/Provider/W1x1CurrentWeather.java
android/src/net/wizardfactory/todayweather/widget/Provider/W2x1CurrentWeather.java
android/src/net/wizardfactory/todayweather/widget/WidgetUpdateService.java

#1158 #1149
service에서 데이터 업데이트시에도 layout 수정사항 반영하게 변경.
날짜 표시에서 년도 빼고, 요일 추가
시스템 글자 사이즈에 영향받지 않게 글자 크기 단위를 sp에서 dp로 변환.
minHeight 대신 MANUFACTURER가 samsung인 경우 글자 확대

투명도 및 설정값 제대로 반영되지 않는 문제 수정 및 레이아웃 수정.

---

android/AndroidManifest.xml

#1163
메뉴뒤에 앱이 나오거나, 메뉴는 안나오고 MainActivity만 나오는 경우도 있음.
MenuActivity set launchMode="singleInstance"
기타
위젯 나열 순서 변경.

앱이 background로 구동되어 있을 경우 위젯 클릭시에 메뉴가 뒤에 앱이 나오는 문제

---

client/www/js/services.js

#1167
navigator와 native를 동시에 실행하고, 3초단위로 3번 시도함

failed navigator.geolocation.getCurrentPosition

---

client/www/js/controllers.js
client/www/js/services.js

#1140
http request 이후 2초내에 응답이 없으면 다른 request를 보냄.

서버에서 응답이 200ms인데 Client에서 6000ms만에 응답 받는 문제

---

ios/widget/MainInterface.storyboard

#1173
change font color for iOS10
update layout for iOS10

iOS 10에서 widget짤림.

---

client/www/js/controllers.js
client/www/js/services.js

#1167 navigator.geolocation.getCurrentPosition 실패 케이스
* getCurrentPosition에 대한 GA 로그 변경
- navigator와 native의 retry 마다 로그를 남기지 않고, 최종 결과에 대해서 retry 횟수와 걸린 시간, 실패 시 이유 및 코드를 남김.
* GA Data Error 코드 정리

#1167 navigator.geolocation.getCurrentPosition 실패 케이스

---

server/controllers/controllerHealthDay.js
server/controllers/controllerManager.js
server/models/modelHealthDay.js
server/routes/v000001/routeGather.js
server/test/testControllerHealthDay.js

1. 생활보건지수를 가져오는 기능 추가
2. 테스트 코드 주석 처리(서비스키 필요한 테스트 코드)

#257 생활보건지수 정보를 가져오는 기능을 추가했습니다.

---

ios/TodayWeather/TodayWeather-Info.plist
ios/TodayWeather/TodayWeather.entitlements

#1172
admob에 의해서 발생하는 문제이며, admob sdk를 version up하거나 관련 설명을 추가해야 함.
관련 설명추가.

NSCalendarsUsageDescription

---

client/package.json
client/www/js/app.js

#1148 airbrige sdk 설치하기
* airbridge plugin 추가 & SDK 초기화

#1148 airbrige sdk 설치하기

---

server/controllers/controllerTown.js

낮은 온도에서 불쾌지수 표시됨.

---

client/config.xml
client/package.json

* cordova-plugin-app-preferences 버전 고정 추후 수정해야함
위젯 iOS10에 맞게 개선2
note3 레이아웃 맞춤
현재위치 검색 개선
날씨정보 업데이트 개선
위젯 메뉴 표시 개선
0.9.13
위젯 iOS10에 맞게 개선.
몇몇 모델에서 로딩시간 개선
시스템 글자 크기와 상관없이 앱,위젯 글자크기 고정
삼성 스마트폰에서 위젯 레이아웃 개선
위젯 업데이트 오류 개선
위젯 메뉴화면 개선

release 0.9.14

---

client/www/js/app.js
client/www/js/controllers.js
client/www/js/service.push.js

#1148
plugin check, set up goal

airbridge 목표설정.

---

ios/widget/MainInterface.storyboard

#1173
앱가기 버튼을 아래로 조금 내리고, 상단에 설명길이를 resizeable하게 변경했습니다.

iOS Widget 안내문구 개선.

---

server/utils/data/cityNormalGeocodeList.csv
server/utils/normalizeGeoCode.js

#1186
make cityNormalGeocodeList.csv

normalize cityGeocodeList

---

client/www/js/controllers.js
client/www/templates/tab-dailyforecast.html
client/www/templates/tab-forecast.html

#1188 화면 클릭으로 시간별날씨 <-> 일별날씨 전환 기능 제거
* ng-click 이벤트 제거 & changeForecastType 함수 제거

#1188 화면 클릭으로 시간별날씨 <-> 일별날씨 전환 기능 제거

---

client/www/js/controllers.js
client/www/js/service.applewatch.js
client/www/js/services.js
client/www/templates/guide.html
client/www/templates/tab-search.html
client/www/templates/tabs-android.html
client/www/templates/tabs.html

#1187 도시 검색 문구 변경
* 도시, 도시검색 대신 지역, 관심지역으로 변경
* Popup에서 OK, Cancel 버튼을 확인, 취소로 한국어 적용
* 관심지역이 하나도 없는 경우 resume 시 canLoadCity에서 에러 수정

#1187 도시 검색 문구 변경

---

client/www/js/app.js
client/www/js/controllers.js

#771 사용자 의견 보내기 할때, 기본 디바이스 정보 추가하기.
* mailto에 옵션 추가
- subject 추가
- body에 version, ua 정보 표시
* ga에 screen, outer width/height 이벤트 전달

#771 사용자 의견 보내기 할때, 기본 디바이스 정보 추가하기.

---

client/www/js/controllers.js

#1195
TabCtrl에서 layout설정 오류 수정.

탭바와 메뉴가 겹침

---

client/package.json

#1172
update admob-plugin
update admob-sdk version for ios

admob old sdk access privacy-sensitive data

---

ios/TodayWeather.xcodeproj/project.pbxproj

#1188
ios widget 에서 불필요한 image reference 제거

guide image 못 찾아서 컴파일 에러나는 문제.

---

client/www/js/controllers.js

#1135 현재 위치가 아닌 도시의 날씨 데이터를 가져오지 못하는 문제
* 위치정보를 못 가지고 오는 경우(getCurrentPosition)
- "현재위치를 찾을 수 없습니다." 문구 유지
* 다음, 구글에서 주소 정보를 못 가지고 오는 경우 (getAddressFromGeolocation)
- "위치 정보를 가져오지 못하였습니다." 문구 변경
* 서버로부터 날씨 정보를 못 가지고 온 경우 (getWeatherInfo)
- "날씨 정보를 가져오지 못하였습니다." 문구 변경

#1135 현재 위치가 아닌 도시의 날씨 데이터를 가져오지 못하는 문제

---

client/www/js/services.js

현재위치 못 찾는 오류

---

client/www/js/services.js

#1214 0.9.14 버전 이후로 GA의 이벤트가 기록되지 않는 문제
* google-analytics-plugin 1.5.6 버전에서 1.6 버전으로 업데이트 되면서 Parameter가 추가되어 이벤트가 기록되지 않았음

#1214 0.9.14 버전 이후로 GA의 이벤트가 기록되지 않는 문제

---

client/www/js/app.js
client/www/js/controllers.js

#771 사용자 의견 보내기 할때, 기본 디바이스 정보 추가하기.
* uuid 추가 & ga event 기록 추가

#771 사용자 의견 보내기 할때, 기본 디바이스 정보 추가하기. 

---

client/www/index.html

#1130 loading time 개선 2차
* angularjs app의 로드 시점을 device ready 이후로 변경
- <body>에서 ng-app 제거
- 로드 시점을 deviceready 이후로 이동(app.js의 run이 로드되지 않은 상태이므로 <script>에서 device ready 이벤트 처리를 해야 함)

#1130 loading time 개선 2차

---

client/www/js/app.js
client/www/js/controllers.js
client/www/js/service.push.js

disable airbridge when debug mode

---

server/controllers/controllerTown.js

#894
only get today, tomorrow
get data in getAllDataFromDb

spend long time in minudustfrcsts toArray

---

client/www/js/controllers.js

#1217 “TodayWeather@Wizardfactory” -> “광고없는 프리미엄 사용하기”
* Search 탭에서 키보드가 나올 때에도 광고 표시하도록 수정

#1217 “TodayWeather@Wizardfactory” -> “광고없는 프리미엄 사용하기”

---

client/www/js/services.js

#182
use daum service key in tw.client.config.js

update daum service key

---

client/package.json
client/www/js/app.js
client/www/js/controllers.js
client/www/js/services.js

#987 딥링크 및 동적링크 만들기
* App 실행 시 즐겨찾기가 없는 경우 Forecast 탭에서 에러 팝업 표시 후 확인 버튼 누르면 즐겨찾기 탭으로 이동하도록 시나리오 변경
* Service의 run에서 $ionicPlatform.ready 조건문 제거
* deeplink 플러그인 추가 & route 처리 추가

#987 딥링크 및 동적링크 만들기

---

server/app.js
server/controllers/controllerTown.js
server/controllers/controllerTown24h.js
server/package.json

#1240
add session id in log
"## +"와 "## -" 로 in/out mapping

tracking request

---

client/www/js/services.js

#1212
high accuracy를 true하게 되면 gps를 통해서만 위치를 잡음
high accuracy true, false 모두 요청함.

android api 15에서  위치정보 못 잡음.

---

client/www/js/controllers.js

callback 없는 alert에서 오류

---

client/www/js/services.js

#1212
high accuracy를 false, true, false, true로 요청함
동시에하면 정상동작하지 않는듯함.

android api 15에서 데이터 못 가지고 오는 문제.

---

android/gradle.properties
client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/gulpfile.js
client/package.json

add android/gradle.properties for useDeprecatedNdk
new gulp build_android
v0.9.18
cordova-plugin-app-preferences 지우고, 다시 추가.
v0.9.17
현재 위치 못 잡는 오류 개선
날씨 데이터 못 가지고 오는 오류 개선
화면 클릭시에 시간별/일별 날씨 전환 제거
온도 라벨 변경
가끔 광고와 메뉴가 겹치는 문제 수정.
history back 기능 제거
앱내 문구 변경.

release 0.9.18

---

client/www/js/services.js

#1246
fix wrong parameter of store,fetch api

apppreferences.js error

---

client/www/js/service.twads.js

#1146 #791
admob.events로 들어오는 message는 json이 아님.

type error

---

client/www/js/app.js

check plugin

---

client/www/index.html
client/www/js/controller.purchase.js
client/www/js/controllers.js
client/www/js/service.twads.js

#1245 #1227
Purchase.paidAppUrl나  Purchase.hasInAppPurchase가 존재하면 링크와 프리미엄 메세지 보여줌.

in app purchase 제공하지 않는 경우 메세지 변경.

---

client/package.json
client/www/js/services.js

#1161
upgrade version to 0.99.3

upgrade cordova-plugin-app-preferences version

---

client/www/js/app.js
client/www/js/services.js

logging javascript error

---

ios/widget/MainInterface.storyboard
ios/widget/TodayViewController.h
ios/widget/TodayViewController.m

#1098 #1112
iOS widget 충돌 문제 이슈 수정
- added stopUpdatingLocation
today extension 에서 과거 데이터가 미리 나오게 개선
- added routine saving previous data

iOS widget 충돌 문제 이슈 수정, 과거 데이터가 미리 나오게 개선

---

client/www/js/controllers.js

check rect object

---

client/www/js/controllers.js
client/www/js/services.js

fixed appPreferences on settings

---

client/www/js/app.js

#1263
new airbridgeCustomOnboarding on window

fix airbridgeCustomOnboarding is not defined

---

client/www/index.html

#1245 in app purchase가 없는 경우 "프리이엄" 광고제거
* {{adBannerMsg}} 가 보이지 않도록 ng-bind로 처리

#1245 in app purchase가 없는 경우 "프리이엄" 광고제거

---

client/www/js/controllers.js
client/www/js/service.twads.js

#1255
service.twads.js에서 run을 제거하고, tabCtrl에서 twAds 초기화함.

처음 앱 실행시 가이드에서 광고 나오는 문제.

---

client/www/js/controllers.js
client/www/js/services.js

#1085 권한이 없는 경우와 위치 정보를 못 가지고 오는 경우 분리.
* ga의 trackEvent의 data category 세분화
- [position / get / default, native(msg) / time], [position / error / default, native(msg) / time]
- [address / get / daum, google / time], [address / error / daum, google(msg) / time]
- [weather / get / shorten address(city index) / time], [weather / error / shorten address(city index + msg) / time]
* ga의 trackTiming의 data category 세분화
- [position / time / get / default, native], [position / time / error / default, native]
- [address / time / get / daum, google], [address / time / error / daum, google]
- [weather / time / get / info], [weather / time / error / info]

#1085 권한이 없는 경우와 위치 정보를 못 가지고 오는 경우 분리. 

---

client/scss/ionic.app.scss
client/www/js/controllers.js
client/www/templates/guide.html

#1255 
* 우측 상단에 닫기 버튼 추가
* ga의 trackEvent 추가
- [action / click / guide previous, guide skip, guide close, guide next, guide top close, auto search, city search]

guide에서 못 나가는 문제 체크 및 X 버튼 추가

---

client/www/js/controllers.js
client/www/js/services.js

#1169 #1167
add ga event for check position error

fix error of retry count

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/package.json
client/www/js/services.js

fixed version of cordova-plugin-google-analytics
ga.platformReady() before trackEvent.

release 0.9.22

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/www/js/services.js

#1275 google-analytics-plugin 1.7.1 버전에서 동작하지 않는 문제
* startTrackerWithId에 dispatchPeriod 파라미터 추가(기본값은 30)

#1275 google-analytics-plugin 1.7.1 버전에서 동작하지 않는 문제

---

client/www/js/services.js

#1167
set timeout to 5secs, retry count 2
remove log msg duplicated.

update retry count and timeout duration

---

client/www/js/services.js

#1279
set first city index when city index is over

fix city index is over

---

client/www/js/services.js

fixed error when items is null

---

server/controllers/controllerKmaStnWeather.js
server/lib/kmaScraper.js
server/test/testKmaScraper.js

#613
new _makeWeatherType
make test code for gathering kma weather description

add weatherType for parsing kma weather description

---

server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerRequester.js
server/controllers/worldWeather/controllerWorldWeather.js
server/lib/DSF/dsfRequester.js
server/lib/WU/wuRequester.js
server/routes/worldweather/routeWeather.js

- Added new API “/ww/010000/current/2?gcode=44.0,30.00”
: It only requests yesterday, today, forecast datas.

#1290 new API for yesterday + today + forecast

---

server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerWorldWeather.js
server/routes/worldweather/routeWeather.js

- Function which merge DSF data to daily data for client.
- Bug fixed.

#1290 added merging DSF data function

---

android/res/layout/w2x1_widget_layout.xml
android/res/layout/widget_provider_configure.xml
android/res/values-de/strings.xml
android/res/values-en/strings.xml
android/res/values-ja/strings.xml
android/res/values-ko/strings.xml
android/res/values-zh-rCN/strings.xml
android/res/values-zh-rTW/strings.xml
android/res/values/strings.xml
android/src/net/wizardfactory/todayweather/widget/Provider/AirQualityIndex.java
android/src/net/wizardfactory/todayweather/widget/Provider/ClockAndCurrentWeather.java
android/src/net/wizardfactory/todayweather/widget/Provider/ClockAndThreeDays.java
android/src/net/wizardfactory/todayweather/widget/Provider/CurrentWeatherAndThreeDays.java
android/src/net/wizardfactory/todayweather/widget/Provider/DailyWeather.java
android/src/net/wizardfactory/todayweather/widget/Provider/W1x1CurrentWeather.java
android/src/net/wizardfactory/todayweather/widget/Provider/W2x1CurrentWeather.java
android/src/net/wizardfactory/todayweather/widget/WidgetUpdateService.java

#613
new values-de,en,ja,zh-rCH,zh-rTW
fixed error of minSDKversion

new values-de,en,ja,zh-rCH,zh-rTW for android native widgets

---

server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerWorldWeather.js
server/models/worldWeather/modelDSForecast.js
server/models/worldWeather/modelWuCurrent.js
server/routes/worldweather/routeWeather.js

- Fixed bug
: missing crecipType on the DSF
: Added pre_type to the modelDSF
- Merge Timely date from DSF

#1290 #1068

---

server/controllers/controllerKmaStnWeather.js

skip Reh, Wsd when t1hIndex is undefined

---

server/controllers/worldWeather/controllerWorldWeather.js

- Fixed time table
- set decimal point

#1290 fixed time table, decimal point

---

server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerRequester.js
server/controllers/worldWeather/controllerWorldWeather.js
server/routes/worldweather/routeWeather.js

- When the weather data is made, it only uses DSF data.

#1290 use DSF only

---

server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerWorldWeather.js
server/routes/worldweather/routeWeather.js
server/utils/dataTemplate.js

- Changed ‘current’ to ‘thisTime’
: It has yesaterday and today data.
- Changed local time string
- remove all db data before the data needs to be updated.

#1290 changed structure

---

server/controllers/controllerTown.js
server/lib/collectTownForecast.js

#1304
데이터 수집시에 recv fail 케이스로 t1h도 추가.
_convertSummaryTo3H에서 invalid data가 들어 있는 경우 이전 시간 데이터 사용.

t1h가 -50인 경우

---

server/controllers/lifeIndexKmaController.js

#1301
life index를 못 찾는 경우 에러 반환.

life index 없는 경우 행업되는 문제

---

server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerRequester.js
server/controllers/worldWeather/controllerWorldWeather.js
server/models/worldWeather/modelDSForecast.js
server/models/worldWeather/modelGeocode.js
server/models/worldWeather/modelWuCurrent.js
server/models/worldWeather/modelWuForecast.js
server/routes/worldweather/routeWeather.js
server/utils/dataTemplate.js

- Changed time format
- Fixed time table and local time set
- Fixed typo
- Change element name from timely to hourly
- Added press to “thisTime”
- Fixed cloud value to float value
- Added cloud to “daily”

#1280 fixed bugs

---

server/controllers/controllerManager.js
server/lib/kmaScraper.js
server/lib/kmaTimeLib.js
server/routes/v000001/routeGather.js
server/test/testKmaScraper.js

#1315
new convertYYYYoMMoDDoHHoMMtoYYYYMMDDHHMM in kmaTimeLib
new kmaStnPastHourly api
시간별날씨정보를 한시간 단위로 저장함.

new kmaStnPastHourly gather api

---

server/controllers/controllerTown24h.js
server/routes/v000705/routeTownForecast.js
server/routes/v000803/routeTownForecast.js

#1268
new skyIcon in short and current
new skyIcon, skyAmIcon, skyPmIcon in dailyData

insert icon info in short, dailyData, current

---

server/lib/kmaScraper.js

#1315
pub date list에서 이미 저장된 경우는 제외함

check data for filtering saved data

---

android/res/layout/air_quality_index.xml
android/res/values-de/strings.xml
android/res/values-en/strings.xml
android/res/values-ja/strings.xml
android/res/values-ko/strings.xml
android/res/values-zh-rCN/strings.xml
android/res/values-zh-rTW/strings.xml
android/res/values/strings.xml
android/src/net/wizardfactory/todayweather/widget/Data/Units.java
android/src/net/wizardfactory/todayweather/widget/Data/WeatherData.java
android/src/net/wizardfactory/todayweather/widget/Data/WidgetData.java
android/src/net/wizardfactory/todayweather/widget/GetHttpsServerAysncTask.java
android/src/net/wizardfactory/todayweather/widget/JsonElement/GeoInfo.java
android/src/net/wizardfactory/todayweather/widget/JsonElement/WeatherElement.java
android/src/net/wizardfactory/todayweather/widget/JsonElement/WorldWeatherElement.java
android/src/net/wizardfactory/todayweather/widget/WidgetProviderConfigureActivity.java
android/src/net/wizardfactory/todayweather/widget/WidgetUpdateService.java

#1310 #1290
기본적인 방식은 앱과 동일함.
new strings fail_to_get_geoinfo, this_location_is_not_supported
new Units.java, GeoInfo.java, WorldWeatherElement.java
new updateWorldWeatherWidget, in WidgetUpdateService.java
F는 현재온도를 정수로, C는 소수점 한자리로 표시함.
최고,최저 온도는 정수로 표현.
디바이스의 unit 정보는 mLocalUnits에 저장, 날씨데이터는 WeatherData에 units object를 추가하고 거기에 저장.

android widget에서 단위, 다국어, 세계날씨 지원

---

server/app.js
server/controllers/controllerKmaStnWeather.js
server/controllers/controllerTown.js
server/controllers/controllerTown24h.js
server/controllers/lifeIndexKmaController.js
server/lib/kmaScraper.js
server/routes/v000705/dailySummary.js
server/routes/v000705/routeTownForecast.js
server/routes/v000803/routeTownForecast.js

#1315
new updateCurrentListForValidation, mergeCurrentByStnHourly
currentList에 들어갈 데이터 틀을 만들고, t1h가 -50인 경우에 stn hourly 로부터 채워 넣는다.

merge currentList from aws hourly data

---

server/controllers/controllerManager.js

#471
retry시에 failedList를 넣지 않고, 초기 baseTimeList넣는 문제 수정.
failedList를 date+time object를 넣지 않고, mCoord 넣는 문제 수정.

Fixed wrong of _recursiveRequestDataByBaseTimList

---

server/controllers/controllerManager.js
server/controllers/controllerTown.js
server/models/town.js
server/routes/v000001/routeGather.js
server/routes/v000705/routeTownForecast.js
server/routes/v000803/routeTownForecast.js

#1319
towns에 없는 지역은 mCoord, gCoord, areaNo를 찾아서 service에서 직접 towns collections에 저장.
새로운 mCoord는 current, short, shortest 를 gather api를 통하여 KMA에서 가지고와서 사용.
이때 gather api에서 새로운 mCoord에 대한 current, short, shortest를 저장함.
gather에서는 새로운 mCoord에 대한 데이터를 수집함.

client 요청에 의해 새로운 town 정보 추가하기.

---

ios/TodayWeather.xcodeproj/project.pbxproj
ios/widget/MainInterface.storyboard
ios/widget/TodayViewController.h
ios/widget/TodayViewController.m
ios/widget/TodayWeatherShowMore.h
ios/widget/TodayWeatherShowMore.m
ios/widget/TodayWeatherUtil.h
ios/widget/TodayWeatherUtil.m
ios/widget/WidgetConfig.h

Today Extension 확장 (show more)
#1112, #1268
iOS widget 충돌 문제 이슈 수정
- 추가 충돌이슈 수정(CoreLocation 및 nil 체크 추가)
Today Extension 확장 (show more)
- 더보기(ShowMore) 기능 추가

iOS widget 충돌 문제 이슈 수정

---

server/controllers/controllerManager.js
server/controllers/controllerTown.js
server/routes/v000705/routeTownForecast.js
server/routes/v000803/routeTownForecast.js

#1319
region, region/city 에서도 check db validation

short, current, shortest 각각 없거나, 업데이트가 늦으면 갱신

---

server/controllers/controllerManager.js
server/controllers/controllerShortRss.js
server/controllers/controllerTown.js
server/controllers/controllerTown24h.js

#1319
shortRss : modify retry time 3sec to 500ms
fix wrong word : convertWeaterString -> convertWeatherString
remove shortRss in getAllDataFromDb
routing 결과에 대한 오류 체크에서 short 길이 변경 -> 밤에는 모레 없음.

update coordDB for gathering short rss

---

ios/widget/TodayViewController.m

use liveTime as update time in ios widget

---

server/package.json

#1319
mongoose 4.7.6 version에서 연결 끊어지는 문제가 있음.

Fixed mongoose version

---

server/lib/collectTownForecast.js

check validation of short, shortest

---

client/build.json
client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/gulpfile.js
client/package.json

release script 수정 build with build.json
iOS 위젯에서 상세보기 지원.

release 0.9.24

---

client/www/js/controller.purchase.js

프리미엄 유저 광고 제거 페이지 들어갔다 나올 때 오류

---

android/src/net/wizardfactory/todayweather/widget/WidgetUpdateService.java
server/routes/v000803/routeTownForecast.js

#1310 #1342
android/src/net/wizardfactory/todayweather/widget/WidgetUpdateService.java
api 0.08.03 사용 -> 현재온도 소수점 한자리까지 지원.
locationName에 관한 오류 수정.
country, location, name 이 없는 경우 고려.
server/routes/v000803/routeTownForecast.js
v0.07.05 대비 v0.08.03 api에서 빠진 부분 수정.

세계날씨 안드로이드 위젯에서 이전 main app지원

---

server/controllers/controllerTown.js

check value of rs1h

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/package.json

remove android-targetSdkVersion=24

release 0.9.27

---

server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerRequester.js
server/controllers/worldWeather/controllerWorldWeather.js
server/models/worldWeather/modelDSForecast.js
server/test/testControllerWorldWeather/testControllerCollector.js

#1290
sunrise, sunset, pre_intmaxt, temp_mint, temp_maxt, ftemp_mint, ftemp_maxt 의 schema 변경. Number -> Date
new _getLocalLast0H -> timeZone 계산 수정.
timeZone 30분 간격 지원.

timeZone 계산 수정, sunrise, sunset,.. 날짜 데이터 수정.

---

ios/widget/Base.lproj/Info.plist
ios/widget/Base.lproj/MainInterface.storyboard
ios/widget/TodayViewController.m
ios/widget/TodayWeatherShowMore.h
ios/widget/TodayWeatherShowMore.m
ios/widget/de.lproj/Info.plist
ios/widget/de.lproj/MainInterface.strings
ios/widget/en.lproj/Info.plist
ios/widget/en.lproj/MainInterface.strings
ios/widget/ja.lproj/Info.plist
ios/widget/ja.lproj/MainInterface.strings
ios/widget/ko.lproj/Info.plist
ios/widget/ko.lproj/MainInterface.strings
ios/widget/zh-Hans.lproj/Info.plist
ios/widget/zh-Hans.lproj/MainInterface.strings
ios/widget/zh-Hant.lproj/Info.plist
ios/widget/zh-Hant.lproj/MainInterface.strings

#1347, #1355
Modified changing city button issue in showless mode
Modified 6days->5days daily weather about widget under 320 width

iOS Widget 상세보기에서 온도 짤리는 문제

---

server/controllers/controllerTown.js
server/routes/v000705/routeTownForecast.js
server/routes/v000803/routeTownForecast.js

KMA API 로 외국 요청이 들어오면 에러 처리.

---

server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerRequester.js
server/controllers/worldWeather/controllerWorldWeather.js
server/routes/worldweather/routeRequester.js
server/routes/worldweather/routeWeather.js
server/utils/dataTemplate.js

#1290
add sessionID for world weather
mh를 miles per hour 로 간주함.

add session id

---

server/controllers/worldWeather/controllerWorldWeather.js
server/models/worldWeather/modelDSForecast.js
server/utils/dataTemplate.js

fixed precip of daily

---

client/www/js/controller.units.js
client/www/js/service.push.js
client/www/js/services.js

add data (name, location, source, units, language) to push info

---

client/www/js/controller.units.js

fix saveUnits undefined

---

server/controllers/controllerTown.js

#1388
AQI, PM2.5 PM10 중에 가장 높은 것 하나만 표기.
지수중에서 좋은 경우 비중 높게 주는 기능 삭제

Summary에서 AQI관련값은 하나만 표기 (Backend).

---

server/controllers/controllerKmaStnWeather.js

#653
KMA WAS 중에는 분단위 업데이트를 항상 제공하지 않는  STN도 있음.

KMA WAS의 loglevel 조정.

---

server/controllers/controllerKmaStnWeather.js
server/controllers/worldWeather/controllerWorldWeather.js

description 에 따라 weatherType 추가.

---

client/www/js/controllers.js
client/www/js/services.js
client/www/templates/tab-dailyforecast.html
client/www/templates/tab-forecast.html

#1362
메인의 현재온도, 체감온도, 어제비교온도에 적용.
현재온도 크기 조정 (소수점자리 고려)

섭씨(C)는 소수점 한자리까지 표기, 화씨(F)는 정수 표기

---

client/www/js/controllers.js

#1388
AQI, PM2.5 PM10 중에 가장 높은 것 하나만 표기.

Summary에서 AQI관련값은 하나만 표기.

---

client/www/js/app.js

#1362
width 변경시에 제대로 적용될 수 있게 수정

일별날씨에서 지역 변경시에 화면 오류.

---

android/src/net/wizardfactory/todayweather/widget/WidgetUpdateService.java

Fixed wrong address

---

client/www/js/controllers.js
client/www/js/services.js

#1396 #1370
current parser에서 weatherType 빠진것 수정.
device language와 상관없이 convert해야함 (세계날씨는 영어로 전달됨)

fixed weatherType

---

android/src/net/wizardfactory/todayweather/widget/JsonElement/GeoInfo.java
android/src/net/wizardfactory/todayweather/widget/WidgetUpdateService.java
client/scss/ionic.app.scss
client/www/locales/ja.json

#1362
GeoInfo.java
독일어등 몇몇 언어에서 소수점 표기가 달라 발생하는 오류 수정.
WidgetUpdateService.java
google api parameter 오류 수정.
ja.json
format 오류 수정.

fix 일본어 표기 오류, 해외 위젯오류, 현재위치 지역명 오류

---

server/controllers/controllerKmaStnWeather.js

Fixed stnHourly

---

client/bower.json
client/www/index.html
client/www/js/app.js
client/www/js/controllers.js

#1406
lazy loading googleapis by ocLazyLoad

fixed application error

---

server/app.js
server/controllers/controllerPush.js
server/routes/v000705/routePushNotification.js

#1410
추가된 language, location, source에 대하여 예외처리.
DB에 저장된 데이터들 중에 source가 없는 경우 고려

Fixed 500 error of push post

---

client/config-androidsdk14.xml
client/config-androidsdk19.xml
client/config.xml
client/package.json

#1085
Fixed version of plugins.diagnostic on package.json
move definition plugin version to package.json - config.xml에 정의되어 있으면 삭제해도 빌드할때 다시 설치해버림

Fixed exception on lower android api

---

client/www/js/controllers.js

#1406
CDN용 URL이 동작 하지 않아 일반주소로 변경.

fixed wrong url

---

android/src/net/wizardfactory/todayweather/widget/WidgetUpdateService.java
client/www/js/services.js

현재위치 단위를 sublocality_level_1   으로 통일

---

server/app.js
server/controllers/controllerPush.js
server/controllers/controllerTown.js
server/controllers/kecoController.js
server/test/testControllerPush.js

#1308
db상에 예전에 저장되어 lang, units가 없는 경우 기본값 설정
message 생성할때마다, i18n instance 생성하여 사용
grade2str에서 i18n의  instance를 받게 수정.

Fixed error translation on push

---

client/www/js/controllers.js
client/www/js/services.js

#1362
header, content ratio를 좀 단순화 하고, AQI DATA 여부와 상관없이 화면이 허용하는 데로 사이즈 맞춤.
parseShortTownWeather에서 헷갈리지 않게 array내 currentIndex와 상위에 저장되는 currentIndex를 동일하게 유지.

화면비 조정, 시간별날씨차트 시작 위치 조정.

---

android/res/layout-v17/clock_and_current_weather.xml
android/res/layout-v17/clock_and_three_days.xml
android/res/layout/air_quality_index.xml
android/res/layout/clock_and_current_weather.xml
android/res/layout/clock_and_three_days.xml
android/res/layout/current_weather_and_three_days.xml
android/res/layout/daily_weather.xml
android/res/layout/w1x1_current_weather.xml
android/res/layout/w2x1_current_weather.xml
android/res/layout/w2x1_widget_layout.xml
android/res/values-de/strings.xml
android/res/values-en/strings.xml
android/res/values-ja/strings.xml
android/res/values-ko/strings.xml
android/res/values-zh-rCN/strings.xml
android/res/values-zh-rTW/strings.xml
android/res/values/strings.xml
android/src/net/wizardfactory/todayweather/widget/Data/WeatherData.java
android/src/net/wizardfactory/todayweather/widget/JsonElement/WeatherElement.java
android/src/net/wizardfactory/todayweather/widget/JsonElement/WorldWeatherElement.java
android/src/net/wizardfactory/todayweather/widget/WidgetProviderConfigureActivity.java
android/src/net/wizardfactory/todayweather/widget/WidgetUpdateService.java

#1362
update time은 디바이스 시간을 기준으로 함.
clock time은 날씨 현지 시간 기준으로 표시.
위젯 시작시에 pubdate or location text에 Loading으로 표기
sub_locality_1 부터 표기지만 국내는 sub_locality_2로 표기해야 함(앱과 맞추어야 함)
ConfigureActivity에서 OnClickListener 에서  update intent 보내게 변경 (7.0이상에서 위젯 추가시에 업데이트 안되는 문제 수정)

android widget update time, clock time 조정.

---

android/res/values-ko/strings.xml
client/package.json
client/www/js/controller.purchase.js
client/www/js/controllers.js
client/www/locales/ko.json

#1362
통합대기,대기질,대기지수 -> 통합대기 로 통일.
receipt validation url 오류 수정.
광고구매후 페이지 나올때 하단에 배너 광고 영역생기는 문제 수정
Premium 사용자 가이드에서 나올때 하단에 배너광고 영역 생기는 문제 수정.
inapppurchase, push plugin version 고정.

구매오류 및 광고관련 에러 수정.

---

server/controllers/controllerTown.js

add log for tracking skyString was undefined

---

client/www/js/controllers.js

Fixed summary error

---

client/www/js/services.js
client/www/templates/tab-forecast.html

#1425
server로부터 skyIcon이 오지 않는 경우에만 parse함.
_parseWorldSkyState parameter 오류 수정.
etc
visibility < 0 의 경우 표시하지 않음.

fixed _parseWorldDailyWeather

---

server/controllers/controllerTown.js

#1415
과거 short rss부터 데이터를 참고하고, 테이블상 필요없는 데이터추가하는 부분 수정.

append wrong short rss data

---

server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerWorldWeather.js
server/models/worldWeather/modelDSForecast.js
server/routes/worldweather/routeWeather.js

#1290
지정된 시간부터, 앞에 두시간 데이터를 merge
precType은 icon을 첫번째로 고려, prob가 50이상일때 type고려하게 변경.
save icon for precType
thisTime, hourly, daily에 skyIcon
sunrise, sunset 반영을 위해서 daily 먼저 생성함.
fix mistyping _chechHour -> _checkHour
etc
_description2weatherType 에서 and로 넘어오는 경우 첫번째 값 사용하게 변경.

hourly merge 1h to 3h

---

client/www/js/controller.units.js

#906
init 한 값은 obj가 아니라 this(self)에 저장
모든 데이터는 obj가 아니라 this(self)에 읽고,쓰도록 변경.

단위 load/save init 잘 못 사용하는 문제 수정.

---

client/www/js/controller.purchase.js
client/www/js/services.js
client/www/locales/ja.json
client/www/templates/tab-setting.html

#1362
구매복원 후 광고제거 페이지 나올때, 광고 공간 없어지지  않는 문제 수정
Fixed ja.json
settings 우측으로 쏠리는 문제 수정.
한국어 아닌 경우에도 국내는 동까지 표시.

일본어오류(가이드페이지), 설정레이아웃오류,국내 경우 동까지 표기관련 오류, 광고제거 후 오류 수정.

---

client/www/js/controllers.js
client/www/templates/tab-forecast.html
client/www/templates/tab-setting.html

#1368
한국어인경우에만 about 표시
source banner가 너무 빨리 표시 되는 문제 수정.

check showAbout in settings

---

server/controllers/worldWeather/controllerCollector.js
server/controllers/worldWeather/controllerWorldWeather.js

#1365 #1290
date 뿐만이 아니라, fullyear, month까지 비교하게 수정.

diff date 오류 수정.

---

server/lib/lifeIndexKmaRequester.js
server/test/testLifeIndexKmaRequester.js

update kma life index parser

---

server/controllers/worldWeather/controllerWorldWeather.js

#1290
논의로 1시간이 넘어간 경우에만 업데이트함.

use checkValidDate

---

server/controllers/worldWeather/controllerWorldWeather.js

fix precipitation error of dark sky

---

server/controllers/controllerHealthDay.js
server/controllers/controllerManager.js
server/controllers/controllerTown.js
server/routes/v000803/routeTownForecast.js

1. KMA 보건지수를 추가했습니다.
2. controllerTown.js의 ln:2494의 itemList.length가 1이하일 경우 처리될 수 있도록 수정했습니다.

Fixed #257 보건지수 추가
