WizardFactory/TodayWeather

client/www/js/app.js
* ionicConfigProvider에서 tabs.position을 bottom으로 설정
=> Fixed #27 기본 ionic tab template으로 android에서 하단에 tab이 위치하도록 변경

client/scss/ionic.app.scss, client/www/js/app.js, client/www/js/controllers.js, client/www/templates/tab-dash.html, client/www/templates/tabs.html
scroll을 위한 overflow-scroll와 함께, ion-refresher를 사용하면, ion-content의 height값이 pull-to-refresh할 때 변경되는 문제가 있음.
nav-bar를 제거하는 것으로 문제 해결.
chart 하단에 nav-bar 대신으로 5% 공백 추가.
chart-scroll 에서 scrollbar-x 제거.
tabs-item-hide 옵션을 주어 tabs menu제거.
status bar를 제거하고, fullscreen 화면으로 변경.
=> 61 pull to refresh

client/scss/ionic.app.scss, client/www/js/app.js, client/www/js/controllers.js
#78 차트의 디자인 시안 적용 작업
* 단기 예보의 현재(지금) 데이터를 currentForecast 정보로 업데이트 후 timeTable, chartTable의 데이터로 사용
* 차트 선을 monotone에서 linear로 변경
* 모든 데이터에 점으로 표시 추가(현재만 다른 스타일로 적용)
* 날짜 별 최대, 최소 온도 표시
* timeTable 데이터와 차트 점의 위치가 맞지 않는 문제 수정
-  x축의 range을 rangeRoundBands에서 rangeBands로 변경(보정 처리 제외)
=> Fixed  #78 차트의 디자인 시안 적용 작업

client/www/js/app.js, client/www/js/controllers.js
* 처음에 차트에 표시된 최고, 최저가 데이터가 업데이트되면 최고, 최저를 표시해주는 시간이 변경되지 않아 이전 위치에 온도만 변경되어 표시되는 문제가 생김
* 최저, 최저 값을 모두 표시 & css로 show/hide 처리 -> 최고, 최저만 값을 가짐 & css는 항상 show 처리하도록 수정
* 하루의 전체 데이터가 표시되지 않는 경우 최고, 최저값을 계산할 수 없으므로 서버에서 받은 shortForecast의 tmx와 tmn 값을 그대로 표시하도록 수정
* currentForecast.time가 shortForecast의 time이 같은 경우에만 현재 온도를 업데이트 함
=>  Fixed #128 차트의 최고,최저 온도 표시가 두번째 업데이트때 부터 표시되거나, 잘못 표기 되는 문제

client/scss/ionic.app.scss
big-digit, big-temp-point, big-temp-sky-state default value를 320x640에 맞추지 않고, 다양한 해상도에서 글자나 이미지가 겹치지 않게 변경.
=> #21 resize font-size, img

client/www/js/controllers.js
#169 앱 실행 시 사용자 가이드 페이지가 잠깐 보였다 사라지는 문제
* skipGuide의 초기 값에 의해 가이드 페이지가 보인 후에 $ionicPlatform.ready()에서 WebStorage에서 true를 가져와서 사라지게 됨
* $ionicPlatform.ready()에서 설정하는 시점이 느려서 발생하는 문제로 controller 시작 시에 설정하도록 시점 이동
=> #169 앱 실행 시 사용자 가이드 페이지가 잠깐 보였다 사라지는 문제

client/www/js/controllers.js
ionic.Deploy.info()의 전달되는 binary_version정보를 사용하지 않고, hard coding 함.
=> ionic deploy 로 업데이트 한 경우에, settings에서 버전이 변경되지 않는 문제. #363

client/www/js/app.js
* ios에서 alignment-baseline의 ideographic 속성이 적용되지 않아 겹치는 문제 다시 발생함
* 차트의 위쪽에 그릴 때 텍스트의 위치를 5px만큼 위에서 그리도록 y값 조정
=> #346 일별날씨그래프가 화면에서 짤리는 증상.

client/www/js/controllers.js, client/www/js/services.js
add week to dayInfo in parsePreShortTownWeather
When fail to find starting day of dayInfo in midData, insert dayInfo data in tmpDayTable
make dummay data for cityList
short에 최저/최고가 없는 경우, 일별예보에서 최고/최저 값이 잘 못 되는 경우 수정
먼저 short에 tmx, tmn값을 dayInfo에 저장하고, short를 한번 더 돌아서 t3h가 최고/최저를 넘어서면 t3h로 변경
getAddressToGeolocation의 경우에도 daum, google 두개 api사용하게 수정
=> 중기예보에 오늘 정보가 없으면 도시검색에서 에러나는 문제. #380 Fixed #389

client/www/js/services.js
Fixed #390 도시가 여러 개일 때 처음 보여지는 도시만 데이터가 업데이트되고 나머지 도시는 업데이트 되지 않는 문제
* "하늘시 구름동"인 경우에 WeatherUtil.getWeatherInfo가 reject로 처리되어 다음 도시의 정보를 업데이트하지 않음
* resolve, reject 관계없이 finally에서 다음 도시 정보를 업데이트하도록 수정
=> Fixed #390 도시가 여러 개일 때 처음 보여지는 도시만 데이터가 업데이트되고 나머지 도시는 업데이트 되지 않는 문제

client/www/templates/tab-forecast.html
Fixed #399 0도 일 때 reddot 이미지가 보이지 않는 문제
* currentWeather.t1h가 undefined일 때만 reddot 이미지를 표시하지 않도록 ng-if 조건문 변경
=> Fixed #399 0도 일 때 reddot 이미지가 보이지 않는 문제

client/www/js/services.js
short 정보가 invalid하면, 이전 t3h값으로 라인이 연결되게 만든다.
=> short forecast에서 중간에 데이터가 빠져서 차트가 제대로 그려지지 못하는 문제. #402

client/bower.json, client/www/js/controllers.js
change getTodayNowPosition() to getTodayPosition()
시간별에서 9이전에는 현재 시간보다 한 칸전부터 표시, 9시 이후에는 6시부터 24시까지 표시 단 6칸 표시되는 화면에서는 15시 이후에는 9시부터 표시함.
일별에서는 월요에는 지난 토요일부터 표시, 화~토요일까지는 월요일부터 표시, 일요일에는 화요일부터 다음주 월요일까지 표시 단 6칸 표시되는 화면에서는 수요일부터는 화~일까지 표시
fixed scrollTo issue on ionic-bower 1.2.0 (#431)
=> 시간별 날씨, 일별 날씨에서 차트 시작 위치 개선.  Fixed #377, Fixed #431

client/www/js/services.js
resultcode등 xml2json으로 변경된 값은 모두 소문자 처리됨.
pm10value는 '-'로 무의미한 값이지만 grade가 정상적인 경우에 대하여 처리하도록 개선
체감온도, 자외선, 미세먼지 설정 이후에 makeSummary하게 수정
=> #426 getPm10Info에서 예외처리 한거 오류 수정

server/controllers/controllerManager.js, server/lib/collectTownForecast.js, server/models/modelCurrent.js, server/models/modelMidForecast.js, server/models/modelMidLand.js, server/models/modelMidSea.js, server/models/modelMidTemp.js, server/models/modelShort.js, server/models/modelShortest.js, server/test/testControllerManager.js, server/utils/initTownDataToMongo.js
_recursiveRequestData를 사용하여, current, shortest, short, mid_forecast, mid_land, mid_temp, mid_sea 모두 실패한 경우에 대하여 재시도 하게 수정.
current, short, shortest는 30번까지 재시도, mid_XXXX는 10번까지 재시도함.
ram mode 의 경우 기존 방식으로 retrycount 3으로 시도함
CollectData 에서 기본 retrycount와 timeout은 0으로 설정
error 발생시에 error object를 callback으로 전달하여 최종에서 error stack과 함께 출력하도록 조정
save 관한 callback 위치 잘 못된것 수정
warnning 수정
=> DB gather - 데이터 모니터링 기능 추가 #427

server/app.js, server/controllers/controllerManager.js, server/lib/collectTownForecast.js, server/package.json, server/routes/routeTownForecast.js, server/test/testCollectTownForecast.js
organizeXXXX 에서 데이터를 모으는 변수 생성을 변경하여 썪이거나 중복되는 문제 수정.
saveOnlyLastOne flag를 두어서 이 경우에는 각 model의 XXXdata를 덮어쓰기 하여 최신한개만 유지하게 한다.
COUNT는 각 DATA에 대한 갯수로 갯수가 가변인 경우를 고려하면  한번 들어오는 갯수의 최대값을 설정해서 해야 한다.  상세한 동작확인은 하지 않았음
waterfall 내에서 이전 function으로 부터 return 값을 받는 경우에 맞게 수정.
mongoose version update
=> short data가 fcstDate, fcstTime이 중복되어서 저장되거나, 썪여서 저장되는 문제. #463

server/controllers/controllerManager.js, server/lib/collectTownForecast.js
async.waterfall 쓸때는 callback의 parameter 갯수를 맞추어야 함.
초반에 Current, Short, MidTemp, MidLand, Shortest 순으로 업데이트 하고 난 이후에 interval 설정을 한다.
provider에서 get 요청에 대하여 응답이 없는 경우가 있으므로, timeout주어서 끊고 다시 시도하게 변경함.
=> #427 fix callback bug in getXXXXData functions

server/controllers/controllerManager.js, server/lib/PastConditionGather.js, server/lib/collectTownForecast.js, server/test/testCollectTownForecast.js, server/test/testControllerManager.js, server/test/testPastConditionGather.js
#469 - controller manager에서 task가 에러나도, 다음 task로 넘어가게 수정.
#471 - new PastConditionGather . 주의 : 신동네예보는 어제까지만, 구동네예보는 8일전까지 실황 가지고 올수 있음.
current는 currentData를 최대 240개까지 저장하게 수정.
saveCurrent에서 pubDate가 없는 경우에는 pubDate를 갱신하지 않음. - pastConditionGather위한 수정
기존에는 여러개의 mCoord list로 업데이트했으나 이번에 baseTime 기준으로 반복해서 받아, save하게 새로운 함수들 추가
=> #469 과거 실황 데이터 수집기 #471

server/controllers/midRssKmaController.js, server/lib/midRssKmaRequester.js
routing시에 dailyData[0]보다 과거는 버림.
midRssMode.midData에 새로 받은 midData로 overwrite하게 수정.
=> midData가 현재기준 과거 8일뿐만 아니라, 1월초부터 들어오는 문제 #557

server/controllers/controllerManager.js, server/lib/collectTownForecast.js
api 에러 발생시에 retry count를 30에서 10으로 변경.
current, shortest 업데이트 타임을 35분으로 변경. 30분부터 kma api를 모니터링하니, 값이 순차적으로 생기면서 32분정도에 모두 채워짐.
api total count가 0인 경우에 empty object를 추가하지 않고 에러로 처리함 - 추후 totalcount가 0인 경우에 crawler 동작 시킬껀데 좀 더 상셍한 시나리오 필요.
api 속도 문제로 한번에 400개까지 받는 제한 제거 (메모리를 더 많이 사용하게 됨). 추후 api 수신과 save가 분리되어 있는데 이것을 일련의 과정으로 묶어서 분산시키는 방법 고려
=> API 미동작시에 대응할 crawler 제작. #594

server/routes/routeTownForecast.js
- If the town name is not appeared on the town DB, it would be saved
with XY to the dbTownList that contains the townDB on the memory.
=> fixed #592 To avoid calling convertGetcode again over again.

client/www/js/controllers.js, client/www/js/services.js
도시 검색시에도  provider api를 통해서 받는 address와 동일한 포맷으로 맞춤.
weather info 요청시에 second나 third없는 경우에 / 빼도록 개선.
Shorten address 만들 때, 시+구, 시or도 표시되게 개선.
getTownFromFullAdress에서 시or도 + 시or군or구, 시or도  로 town object 만들어지도록 개선.
특별시, 특별자치시, 광역시 는 모두 시 로만 표시함.
=> #381 도시 검색에서 시도, 시구명으로 추가 가능하게 개선

client/www/templates/tab-search.html
#546 도시검색에서 도시가 적어도 스크롤 생김
* ion-scroll의 child인 div에 정의된 margin-top에 의해 margin-top 만큼 아래로 위치되어 스크롤이 발생함
* margin-top을 0으로 변경
=> #546 도시검색에서 도시가 적어도 스크롤 생김

server/controllers/controllerManager.js
aws key가 없는 경우, request 종료하는데 2분정도 소요되어 임시로 막아둠.
데이터 갱신시에 clear해주도록 변경 필요함.
=> #568 cloudfront cache clear

client/config.xml, client/package.json, client/www/js/controllers.js
backend - fsn(식중독), ultrv(자외선)지수 적용 3월부터 제공
backend - current, shortest 업데이트 타임을 35분으로 변경하고 한 번에 가지고 오는 데이터 수를 늘려 속도 개선.
frontend - disable FadeSplashScreen
frontend - 처음 일별 날씨 화면 짤리는 문제 해결
backend - To avoid calling convertGetcode again over again.
frontend - 도시 검색에서 시도, 시구명으로도 추가 가능하게 개선
frontend - 도시리스트에서 도시가 적어도 스크롤 생기는 문제 수정
=> release version 0.7.4

client/package.json
plugin name com.XXX로 시작 하는 부분들 대처된 이름이나, github에서 가지고 오도록 변경.
=> fixed #632 cordova 6.0 호환성 문제

server/controllers/controllerTown.js, server/controllers/controllerTown24h.js, server/controllers/midRssKmaController.js, server/lib/collectTownForecast.js, server/test/testControllerTown.js, server/test/testKmaTimeLib.js
#650 현재 날씨, 바람 소수점까지 표기하기.
provider로부터 데이터를 가지고 올때 정수가 아닌 실수 형태로 저장.
short 에 들어가는 tmn, tmx, t3h는 반올림함.
getCurrent에서 마지막에 t1h를 반올림함.
#557 과거 기입시에 currentList중에 8일이전꺼는 삭제
getPastMid에서 currentList를 필요한 날짜로 필터링 추가.
#168 current로 short생성시에 온도는 평균값이 아닌 해당시간 사용하도록 변경.
etc
shortList에서 현재 request day가 없는 경우에 대하여 예외처리.
과거 데이터 사용할때 overwrite 오류를 해결하기 위해 _createOrGetDaySummaryList 에서 기본값 없애고, taMax taMin는 사용전에 추가하도록 변경.
current, short, mid  merge시에 invalid data에 대하여 제외처리 강화.
=> Fixed #557 Fixed #650 #168

server/controllers/controllerManager.js, server/lib/kecoRequester.js, server/lib/lifeIndexKmaRequester.js, server/lib/midRssKmaRequester.js, server/routes/v000001/routeGather.js
#661 kma에서 생활지수 가지고 오는데 너무 오래 걸리는 문제
areaIndex 제거하고, 오류 발생시에 areaIndex에서 다시 실행하는 것이 아니라, 에러 발생하는 지역을 모아서 retry하게 변경함.
데이터 요청하기 전에, db에 저장된 데이터가 최신인지 확인함.
etc
cbMainProcess의 동일한 이름을 cbKecoProcess, cbKmaIndexProcess, cbMidRssProcess 로 변경.
town load 확인후에 controllManager.task 실행되게 수정.
=> Fixed #661 retry max 30회까지 시도하게 변경.

server/lib/lifeIndexKmaRequester.js
lifeindex 가지고 올때, 자주 끊어지는 문제때문에 30초로 연장
업데이트 타임 안 맞는 경우가 보여, 관련 코드 추가.
=> #205 get lifeindex

client/www/js/app.js, client/www/js/services.js, server/controllers/controllerManager.js, server/controllers/controllerTown.js, server/controllers/kecoController.js, server/controllers/lifeIndexKmaController.js, server/routes/v000705/routeTownForecast.js
frontend
chart에서 현재 포인트 시간을 currentWeather에서 가지고 오게 수정.
엊그제 추가 - 에러 방지용.
makeSummary(), convertKmaPtyToStr(), convertKmaRxxToStr(), convertKmaWsdToStr() 서버로 이동.
parseCurrent, parseShort, parseMid에서 보정하던 code 제거.
parsePreShort 제거.
backend
controllerTown.getSummary, controllerTown.insertStrForData 추가. -> client 부분 넘어옴.
shortest 3일치 저장하게 수정. -> current  데이터 없는 경우 보정용.
short내의 tmx,tmn을 소수점 1자리로 제한.
gathering time 단일화. 1, 20, 35
related issue #379
=> Fixed #266 move making summary, making string info to backend

server/controllers/controllerTown.js, server/controllers/kecoController.js
#250
getArpLtnInfo의 첫 parameter를 townObject 변경.(gCoord 포함)
arpltn를 못가지고 오는 경우에, _makeArpltnStr에서 죽는 문제 수정.
stationName이 없어서 arpltn을 못가지고 오는 경우 배열에서 제외 in _getArpLtnList
=> towns에 없는 지역 요청시에 죽는 문제.

server/controllers/controllerManager.js, server/lib/kecoRequester.js
#702
keco update는 2분 마지막, 20분, 35분 마지막  task에 배치함.
다수 배치에 따른 속도 문제 개선을 위해, db save, call url 을 동시에 하게 변경함.
=> keco is updated 3times every hour

server/controllers/controllerTown.js
#678
미만,이상 대신에 ~를 사용함.
mobile에서 공간부족 해소 및 언어 대신 기호 대처.
추후 mm,cm단위 제거 할 예정.
=> _convertKmaRxxToStr

server/controllers/controllerTown.js, server/controllers/controllerTown24h.js
#741
sendResult를 overriding하고 v000001에서는 midData.pubDate를 생성해주어 기존 버전 호환성유지.
#575
weather info가 필요한 만큼 넘어가도, 그외에 체크하는 데이터들은 모두 보내주어야 한다.
=> widget을 위해서, midData에 기본 property 추가

server/controllers/controllerManager.js
#754
정각이 지나면 데이터 갱신 없이 기상실황표 시간만 변경됨.
aws update는 5분에 함.
=> gather aws data at 5mins

client/www/js/app.js
#619 즐겨찾기된 도시로 바로 이동가능한 url path 설정
* ios(chrome의 iphone)에서 "tab/forecast?fav=0"로 페이지 이동 시 배경이 검은색으로 표시되는 문제 수정
- ionic.css에 nav-view-transition이 ios이고 nav-view-direction가 forward/back인 경우에 background를 검은색으로 처리하는 부분이 있음
- view transition 시 animation style을 android로 항상 처리되도록 함
=> #619 즐겨찾기된 도시로 바로 이동가능한 url path 설정

server/controllers/controllerKmaStnWeather.js, server/controllers/controllerManager.js, server/controllers/controllerTown.js
#754 #796
routing시에 시간 비교하는 부분 code out
routing시에 매시간 5분이전에는 한시간 전시간 데이터로 가지고 오는 부분 codeout
3,6,9분에 kmaStnHourly data가져옴.
=> kma stn hourly data 한개만 저장하는 것에 대한 에러 수정.

client/bower.json, client/package.json, client/www/index.html, client/www/js/app.js, client/www/js/controllers.js, client/www/js/services.js
#489 사용자 사용패턴 분석할 수 있는 토대 마련.
* GALocalStorage로 추가한 코드 제거
* cordova-plugin-google-analytics 추가
* android와 ios의 실제 단말에서만 동작하고 크롬의 경우에는 $window.analytics가 없어 동작하지 않음
* Util을 통해 $window.analytics가 있는지 확인한 후 $cordovaGoogleAnalytics의 함수들을 호출하도록 함
* android와 ios의 ga key를 다르게 입력하도록 처리
=> #489 사용자 사용패턴 분석할 수 있는 토대 마련.

client/config.xml, client/ionic.project
#524 #605 #147
crosswalk에서 inapp purchase가 동작하지 않아
android sdk와 상관없이 제거함
=> remove crosswalk

client/www/js/app.js
#857
광고가 있는 경우와 없는 경우 margin동작 오류로 일단 true로 변경함.
이 변경으로 ios에서 날씨와 설정 탭에서 상태바 컬러가 나오지 않음. - 추후 계선 예정.
=> set overlay web view of status bar to true

server/controllers/controllerTown.js
#869
current data가 invalid한 경우 undefined로 설정하여 getKmaStnHourlyWeather()에서 overwrite할 수 있게 한다.
=> current data가 invalid한 경우 undefined로 설정

server/controllers/controllerKmaStnWeather.js, server/controllers/controllerTown.js, server/lib/kmaScraper.js
#872
t1h, vec, wsd, vec1 모두가 0이면 오류로 보고 저장안함.
getCityWeather에서 stnId 생성하도록 개선.
aws와 city weather를 merge할때, stnId로 비교하게 수정.
aws에 city weather가 없는 경우 추가해도록 개선.
저장된 aws weather info는 한 시간 전까지 사용하도록 변경.
=> aws 데이터의 오류 체크

client/www/js/services.js
#798 daum api가 에러나서, google에 geolocation을 요청하면 무조건 에러가 발생
* 재현되지 않아 코드 상 오류만 수정
* promise reject 후에 return 문 추가하여 resolve 처리되지 않도록 함
=> #798 daum api가 에러나서, google에 geolocation을 요청하면 무조건 에러가 발생

server/controllers/midRssKmaController.js, server/lib/midRssKmaRequester.js
#909
_updateTimeTable 오류 수정.
mid의 rssPubdate가 landPubdate와 tempPubdate보다 최신인경우에만 업데이트하게 수정.
=> 과거 중기예보 RSS로 데이터가 덮어써지는 문제. #909

server/controllers/controllerTown.js
#930
12시 전후로 pty, sky, lgt를 분리하여 계산함.
실황의 경우 당일 데이터는 부족할 수 있으나, 단기예보로 overwrite함.
=> 실황, 단기 예보로 중기예보 오전, 오후 날씨 만들기.

server/controllers/controllerKmaStnWeather.js, server/controllers/controllerShortRss.js, server/controllers/controllerTown.js, server/controllers/kecoController.js, server/controllers/lifeIndexKmaController.js, server/controllers/midRssKmaController.js, server/routes/v000705/routeTownForecast.js, server/routes/v000803/index.js, server/routes/v000803/routeTownForecast.js
#256 #777
short의 r06, s06, t3h, tmn, tmx, current의 t1h, wsd, mid의 taMax, taMin 은 정수형이 아니라 실수 소수점한자리까지 전달함.
지수 계산용 insertData 추가
client 이전 버전 호환용 dataToFixed 추가
체감온도를 기존 계산식 + 열지수 하여 여름에도 사용하게 변경.
getStnHourly
KMA AWS 적용은 0.3(약 30km)이내에 있는 경우에만 적용.
_getArpLtnList
_id값 넘어가는것 수정.
_appendFromDb
생활지수 0.3(약 30km)이내의 경우에만 사용하게 수정.
=> 지수 계산 한곳으로 합치고, 숫자데이터는 소수점 한자리로 통일, 체감온도 개선

server/controllers/controllerTown.js
#949
시간 체크 코드가 날짜 체크 코드 밖에 있어서 발생한 문제로 안으로 넣음.
=> getKmaStnHourlyWeather에 의해 받은 온도를 short에 잘 못 overwrite되는 문제.

client/www/js/services.js
#965
html5 표준인 navigator먼저 접근하고 실패하는 경우에만 native사용하게 변경.
=> crosswalk on android 6.x에서 native geolocation 동작 안하는 문제

server/controllers/controllerKmaStnWeather.js, server/controllers/controllerTown.js
#977
산간에 있는 측정소 등이 근접하면 발생하는 문제.
다음 측정소보다 온도차가 더 크면 사용하지 않음
단 도시별날씨의 측정소의 경우 조건없이 적용.
=> AWS 온도가 너무 차이나는 케이스

client/www/js/services.js
#1003 도시검색하여 시간별날씨로 넘어올때, 데이터 요청이 두번 됨.
* 도시 추가 시에 현재 시간으로 loadTime을 설정하여 시간별날씨로 이동 시에 재요청되지 않도록 함
=> #1003 도시검색하여 시간별날씨로 넘어올때, 데이터 요청이 두번 됨.

client/www/js/controllers.js, client/www/js/services.js
#982 앱 시작시에 도시목록의 데이터를 모두 받아야 로딩이 끝나는 방법 개선.
* 앱 시작 시에 도시 목록의 데이터를 모두 업데이트 하는 코드 제거
- WeatherInfo의 run 시에 updateCities 호출하지 않음
- 사용되지 않는 updateCities, isLoadComplete, loadCompleteEvent 제거
* ForecastCtrl 실행 시에 현재 도시에 대한 데이터를 요청하여 업데이트됨
* SearchCtrl 실행 시에 도시 목록을 모두 업데이트 요청함
- 검색 화면인 경우에는 도시 목록의 날씨 정보 업데이트 처리
- 업데이트 중에 도시 목록이 변경될 수 있으므로 현재 도시 목록에서 도시를 찾아서 업데이트함
=> #982 앱 시작시에 도시목록의 데이터를 모두 받아야 로딩이 끝나는 방법 개선. 

client/www/js/app.js
#926 설정에 가이드 가는 경우, 현재위치 선택창 제거.
* 재현 경로 : 처음 설치 시에 guide 페이지 show(guideVersion = null) -> close(localStorage에 저장) -> 설정에서 다시 guide 페이지 show 하면 cache되어 있어 init 함수가 호출되지 않음(guideVersion = null)
* guide 페이지는 cache 하지 않도록 설정 변경
=> #926 설정에 가이드 가는 경우, 현재위치 선택창 제거.

client/www/js/services.js
#786 #957
#957 에서 데이터 자체가 과거이므로 앞영역으로 변경하였으나.
데이터는 데이터이고 사용자가 생각하는 시간적 흐름상 뒤에게 맞고,
측정소를 활용한 실시간 날씨 정도의 경우, 정각 이후에는 넘어가야 하므로, 뒤로 보냄.
=> 3,6,9에서 현재위치를 뒤 영역으로 표시되게 수정.

client/config.xml, client/package.json, client/www/js/services.js
0.9.4
자정부터 3시까지 발생하는 차트 오류 수정.
0.9.3
일부폰에서 미세먼지 정보를 스크롤하지 않고 볼 수 있게 개선.
앱실행시에 날씨정보 갱신 안되는 문제 수정.
습도 100% 오류 수정.
설정에 가이드 가는 경우 간헐적으로 선택창뜨는 문제 수정.
도시가 하나밖에 없는 경우 좌우 버튼 나오지 않게 개선.
즐겨찾기된 도시가 많은 경우 앱 실행시 오래 걸리는 문제 개선.
도시 검색하여 시간별날씨로 넘어올때 날씨 정보 다시 받는 문제 수정.
초미세먼지 정보가 없는 경우 -1로 나오는 문제 수정.
일별날씨는 이틀전부터 표시되게 수정.
일부 안드로이드 폰에서 현재위치 정보 못 가지고 오는 문제 개선.
시간별,일별날씨정보 차트 일체화 시켜 UI개선 - iphone4에서 차트랑 날씨정보 칸 안맞는 문제 수정.
=> release version 0.9.4

client/www/js/app.js, server/app.js, server/controllers/controllerKmaStnWeather.js, server/controllers/controllerManager.js, server/controllers/controllerTown.js, server/lib/kmaScraper.js, server/lib/kmaTimeLib.js, server/lib/lifeIndexKmaRequester.js, server/models/modelKmaStnInfo.js, server/models/modelKmaStnMinute.js, server/routes/v000001/routeGather.js, server/routes/v000705/routeTownForecast.js, server/routes/v000803/routeTownForecast.js, server/test/testControllerKmaStnWeather.js, server/test/testKmaScraper.js, server/test/testKmaTimeLib.js, server/test/testLifeIndexKmaRequester.js
#653 #997
**frontend**
pubdate에 분단위 정보가 들어오면, 실시간 날씨로 구분하고, 6단계로 구분한다.
**backend**
new getStnMinute, getKmaStnMinuteWeather
분단위 데이터는 가지고와서 적용한다. 
강수의 경우 측정소에서 대략 20분내에 강수로 표시가 한번이라도 발생하면 비옴으로 간주한다.
측정소에 대하여 강수 신뢰도를 두고 50프로 이상인 경우에만 사용한다.
new updateRnsHitRates
새로운 current가 들어오면 측정소의 주소로 current정보를 가지고 와서 측정소의 강수 신뢰도를 계산한다.
new getStnMinuteWeather
30초마다 측정소의 기상정보를 가지고 오는데, 시간이 뒤집어 들어오는 경우도 있고, 건너 뛰는 경우도 있음.
new addStnAddressToTown
stnInfo에 있는 addr에 따라 towns에 새로운 정보를 추가함.
new resetRnsHitRates
측정소의 강수 신뢰도는 초기화하는데 사전 조사에서 강수가 표시 되지 않는 지역 정보에 따라 rate를 0으로 만듬.
=> 653 997 kma aws minute

client/www/js/app.js, server/app.js, server/controllers/controllerKmaStnWeather.js, server/controllers/controllerManager.js, server/lib/kmaScraper.js, server/lib/lifeIndexKmaRequester.js, server/models/modelKmaStnInfo.js, server/package.json, server/routes/v000001/routeGather.js, server/test/testKmaScraper.js
#653 #977 
**frontEnd**
현재위치 포인트 크기 조건문 수정.
글자색에 대한 조건문 수정.
정각일때 오류 나는 문제 수정.
**backEnd**
scrape mode를 추가하고, gather server에서 scrape mode 개별 프로세스로 동작함. 
성능문제로 scrape mode 에서는 2분당데이터만 수집함.
측정소 날씨를 범위 0.3에서 0.2로 조정.
측정소의 isMountain 이 true인 경우 사용에서 제외함.(산으로 보고 제외함)
실시간 날씨 수집이 2분데이터로 하기 때문에 그에 맞추어 rns사용여부와 rnsHitRate관련 조건문 수정.
new resetMoutainInfo
etc
life index request count 출력하는 로그 레벨 수정.
past gather에 대한 실행문 수정.
=> 실시간 날씨 반영 및 운영 방법 수정.

client/www/js/controllers.js
#1016 시간별 날씨에서 차트 스크롤 안되는 경우
* 재현 경로
- 현재 위치가 아닌 도시가 추가된 상태에서 app 실행 시 차트의 가로 스크롤이 동작하지 않음(Note3, Android 5.0)
- 현재 위치가 last index인 경우에는 재현되지 않음
* applyWeatherData에서 scrollTo 호출 시에 animation을 끄면 정상 동작함
* ios에서만 animation을 지원하도록 조건문 추가
=> #1016 시간별 날씨에서 차트 스크롤 안되는 경우

server/controllers/controllerTown24h.js
#1052
rss의 경우 api보다 데이터 양이 적기 때문에 뒷분의 데이터가 부족한 경우가 발생함.
invalid상태를 reh가 아니라, t3h로 변경.
=> 뒷부분의 t3h가 -50로 표시 되는 문제

client/scss/ionic.app.scss, client/www/js/app.js, client/www/js/controllers.js, client/www/js/service.twads.js, client/www/templates/tab-setting.html, client/www/templates/tabs-android.html
#1042
tabs 분리. tab icon android용으로 구분.
settins에서 android의 경우 arrow 표시 안함.
tabs-dark 제거.
=> update ui for android

client/www/js/controllers.js, client/www/js/services.js
#1082
reloadEvent를 resume과, tab으로 분리
resume일 경우에는 retry popup이 있는 경우 loadWeatherData를 호출하지 않음.
popup window가 없는 경우 confirmPopup 변수를 항상 undefined로 유지해야 함.
=> android에서 location permission 주지 않는 경우, 무한 reloading 문제.

client/ionic.project, client/www/js/app.js, client/www/js/controller.purchase.js, client/www/js/controllers.js, client/www/js/service.push.js, client/www/js/services.js
#1130
splashscreen을 빠르게 닫기 위해 event 분리
run에서 실해아하는 모든 것을 deviceready 이후로 변경.
ionicLoading은 loadWeatherData로 한정함.
remove crosswalk browser info in ionic.project
=> device ready 이후 js 실행.

client/scss/ionic.app.scss, client/www/index.html, client/www/js/controllers.js, client/www/js/service.twads.js
#1217 “TodayWeather@Wizardfactory” -> “광고없는 프리미엄 사용하기”
* ‘TodayWeather@WizardFactory’를 ‘광고없는 프리미엄 사용하기’으로 문구 변경
* ‘광고없는 프리미엄 사용하기’ 클릭 시 Purchase 페이지로 이동
- 클릭 이벤트를 받지 못하는 문제 : ion-nav-view의 z-index가 3이라서 앞에 위치하도록 z-index 스타일 추가
- TwAds에서 rootScope에 함수를 추가하여 ng-click에서 호출 : admob.setOptions가 실패한 경우 Purchase 페이지로 이동되지 않는 문제 처리
- Purchase 페이지에서 ‘광고없는 프리미엄 사용하기’가 계속 보이는 문제 : viewAdsBanner를 TwAds의 enableAds 대신 setShowAds 함수의 show와 동기화 처리(ready되지 않은 상태에서도 설정되어야 함) & 프리미엄 사용자가 아닌 경우에 보이도록 true로 초기화
- admob.setOptions가 실패한 경우 탭이 보이지 않는 문제 : TwAds.enableAds가 undefined 상태인 경우 TwAds.setLayout를 true로 설정
- purchase의 하단에 1px 다른 색으로 표시되는 문제 : css의 purchase-content에서 width, height 제거
=> #1217 “TodayWeather@Wizardfactory” -> “광고없는 프리미엄 사용하기”

client/www/templates/tab-forecast.html
#1128 시간별날씨 차트에서 어제, 오늘 라인의 라벨 표시 추가
* 사용자 리뷰에서 기온 차트인지 인지하지 못하는 경우가 있어 문구를 ‘전일 기온/당일 기온’으로 변경
=> #1128 시간별날씨 차트에서 어제, 오늘 라인의 라벨 표시 추가

client/www/js/controllers.js
#1229 안드로이드에서 HistoryBack 기능 제거
* Search, Setting 탭 전환 시 History Clear
* Setting 탭에서 Purchase, Guide 페이지 이동 시에는 History Back으로 다시 Setting으로 이동 가능함
=> #1229 안드로이드에서 HistoryBack 기능 제거

client/scss/ionic.app.scss
#1255 guide에서 못 나가는 문제
* 닫기 버튼 위치에 의해 가이드 타이틀 글자 위치가 왼쪽으로 치우치는 문제 수정
- float 대신 position 속성으로 대체
=> #1255 guide에서 못 나가는 문제

server/controllers/controllerKmaStnWeather.js, server/controllers/controllerTown.js, server/lib/kmaTimeLib.js, server/routes/v000705/dailySummary.js, server/routes/v000705/routeTownForecast.js, server/routes/v000803/routeTownForecast.js
#1294
동네예보의 정보를 가지고 AWS의 동일한 시간에 데이터와 갭이 많이 나지 않는 경우에만 데이터를 사용.
t1h, rain 두개로 분리
t1h의 측정소에서 wsd, reh값이 크게 벗어나지 않으면 사용.
적정 범위내의 데이터가 없으면 측정소의 값음 버림.
=> AWS의 측정값에 대하여 오류 체크 강화하기.

server/app.js, server/controllers/controllerTown.js, server/lib/collectTownForecast.js, server/models/modelShortest.js, server/routes/v000705/routeTownForecast.js, server/routes/v000803/routeTownForecast.js
#1312
update modelShortest (new t1h, reh, uuu, vvv, vec, wsd)
current에 shortest를 적용하고, AWS데이터 적용함.
fixed
과거 데이터가 없는 경우, KMA로부터 데이터를 가지고 오면 전일 동일 시간의 한시간 후 부터 데이터가 있음
=> update kma shortest forecast

server/controllers/controllerTown.js, server/routes/v000705/dailySummary.js, server/routes/v000705/routeTownForecast.js, server/routes/v000803/routeTownForecast.js
#823
예보시간 변경으로 다가올 shotest는 30분 발표가 아니라, 1시간 30분전 발표 내용이라 제외함.
=> unused mergeCurrentByShortest

server/app.js, server/controllers/controllerKmaStnWeather.js, server/controllers/controllerTown.js, server/lib/collectTownForecast.js
#1328
업데이트 늦은 경우에는 무시함 - 시간이 오래 걸리고, 기존 데이터와 머지해야 함.
#1294
current가 없는 경우 측정소 정보로 current를 생성함.
AWS STN의 분단위 데이터가 없는 경우 시단위 데이터라도 넘김.
AWS STN 데이터는 current의 pubdate보다 최신인 경우에만 사용.
etc
local에서는 push 동작안함.
ETIMEOUT의 경우 debug로 loglevel 조정.
data 없는 경우도 loglevel 조정.
=> 데이터 업데이트는 늦는 경우 무시, current가 없는 경우 고려.

client/package.json, client/www/js/controllers.js, client/www/js/services.js
#1085 권한이 없는 경우와 위치 정보를 못 가지고 오는 경우 분리.
* cordova.plugins.diagnostic 플러그인 추가
* 시간별날씨/일별날씨에서 현재 위치 찾기
- 위치 서비스 On 상태
+ 위치 접근 권한 있는 경우 : 현재 위치 찾기(찾은 경우에는 날씨 정보 요청)
+ 위치 접근 권한 설정이 되어 있지 않은 경우 : 권한 요청 팝업 표시
+ 위치 접근 권한이 거부되어 있는 경우 : 저장된 위치가 없으면 에러 팝업 표시 / 저장된 위치가 있으면 저장된 위치로 날씨 정보 업데이트
- 위치 서비스 Off 상태 : 저장된 위치가 없으면 에러 팝업 표시 / 저장된 위치가 있으면 저장된 위치로 날씨 정보 업데이트
* 즐겨찾기의 현재 위치 찾기
- 위치 서비스 On 상태
+ 위치 접근 권한 있는 경우 : 현재 위치 찾기
+ 위치 접근 권한 설정이 되어 있지 않은 경우 : 권한 요청 팝업 표시
+ 위치 접근 권한이 거부되어 있는 경우 : 에러 팝업 표시
- 위치 서비스 Off 상태 : 에러 팝업 표시
* 즐겨찾는 지역 목록에 표시되는 현재 위치 날씨 정보는 저장된 위치를 기준으로 날씨 데이터를 업데이트함(저장된 위치가 없으면 표시 안함)
=> #1085 권한이 없는 경우와 위치 정보를 못 가지고 오는 경우 분리.

client/config-androidsdk14.xml, client/config-androidsdk19.xml, client/config.xml, client/gulpfile.js, client/package.json
android-targetSdkVersion=24
fixed version of inapppurchase to 1.0.0
0.9.26
inapppurchase version downgrade
0.9.25
적설량 단위 오류 수정
안드로이드 위젯 현재온도 소수점 한자리까지 지원(세계날씨용 위젯 적용)
위치정보에 대하여 권한이 없는 경우와 못 가지고 오는 경우에 대한 에러 세분화
위치정보가 꺼져 있는 경우 날씨정보만 갱신
광고제거 페이지 오류 수정
=> release 0.9.26

server/app.js, server/controllers/worldWeather/controllerCollector.js, server/controllers/worldWeather/controllerWorldWeather.js
#1290
turn on world weather API
getTime()에서 timeZone이 고려되어 있으므로, 모든 값을 UTC로 초기화하고, date와 hours만 조정함.
ISOString()로 나오는 시간 값에 timeOffset를 더 했을때, 지역에서 원하는 시간이 나오면 됨.
getLocalTimezone 에서 callback 위치 오류 수정.
find().lean()을 사용하여 데이터 최적화
=> timeZone 계산 수정

server/controllers/controllerKmaStnWeather.js, server/controllers/controllerTown.js
#1372
liveTime이 존재하는 경우, current.date와 current.time을 stnDateTime에 맞춤.
#1278
'얼음싸라기' 추가.
weather에 '끝'이 들어가면 pty는 0으로 설정, '얼음'은 눈으로 간주.
sky, pty, lgt, rn1을 도시별날씨와 AWS정보를 우선하게 수정.
=> 현재날씨 시간 오류 수정, 날씨를 도시별날씨+AWS우선으로 변경함.

client/bower.json, client/package.json, client/www/js/controllers.js
#1257
ios에서도 scrollTo 사용시에 animation 적용하지 않음.
Fix cordova-uglify version
Update ionic-bower to 1.3.2
=> 처음실행시 좌우 scroll 안되는 문제

server/controllers/controllerKmaStnWeather.js
#1438
특정 도시별날씨가 업데이트 되지 않은 경우 다음 가까운 도시별날씨를 사용하게 수정.
갯수를 늘려도, filter하는 곳에서 한개만 추출함.
=> 도시별날씨가 업데이트 되지 않은 경우 고려

client/www/js/app.js, client/www/js/controllers.js, client/www/templates/tab-dailyforecast.html, client/www/templates/tab-forecast.html, client/www/templates/tab-search.html, client/www/templates/tab-setting.html
#1043 Play store, App store featured 도전
* 하단 탐색바는 화면 스크롤링 시 동적으로 나타나고 사라져야 함
- "tabs-shrink" directive 추가
+ 아래로 스크롤 되면 tab의 top을 높이만큼 내려주고, 위로 스크롤 되면 다시 올려줌
- contentHeight() 함수 추가
+ 아래로 내려간 tabsTop 만큼 content의 bottom도 아래로 내려가야 함
+ contentBottom에서 tabsTop을 뺀 값을 content의 bottom으로 계산
- tab의 스크롤 되는 ion-content에 tabs-shrink 추가 및 bottom을 contentBottom 대신 contentHeight() 함수로 binding
- 즐겨찾기 tab에서 도시 갯수에 따라 아래로 스크롤이 되어 탐색바가 사라졌지만 스크롤되지 않는 상태라 다시 보여지지 않는 문제가 발생
+ 임시로 하단에 공백 추가하여 스크롤 되도록 함(화면 크기에 따라 동일 문제 발생할 수 있음)
=> #1043 Play store, App store featured 도전

client/package.json, client/www/js/controller.forecastctrl.js, client/www/js/controller.searchctrl.js, client/www/js/controller.tabctrl.js, client/www/js/service.util.js
#1490 #1085
location permission 요청을 denied한 경우 popup보여줌.
gLocationAuthorizationStatus, confirmPopup, showRetryConfirm을 tabCtrl 로 옮김.
search에서는 닫기버튼으로 보여주고, forecast에서는 검색 버튼만 보여줌.
locationServices가 disabled되어 있으면 locationAccuracy.request호출함.
search에서는 권한 수정에 따른 재시도를 위해 'searchCurrentPositionEvent' 추가
new cordova-plugin-request-location-accuracy
etc
debut mode 일때, trackEvent, trackException parameter 출력
=> location auth에 대한 개선

ios/widget/TodayViewController.m
#1521
[iOS][widget] 통합대기 Label이 사라지는 경우 발생
* PROBABILITY_OF_PRECIPITATION label hidden value
=> * PROBABILITY_OF_PRECIPITATION label 조정

ios/Base.lproj/InfoPlist.strings, ios/de.lproj/InfoPlist.strings, ios/ja.lproj/InfoPlist.strings, ios/ko.lproj/InfoPlist.strings, ios/zh-Hans.lproj/InfoPlist.strings, ios/zh-Hant.lproj/InfoPlist.strings
* 다국어 지원을 위한 InfoPlist.strings 추가 
#1322
+ iOS Native 부분 다국어 지원
- 빌드 에러 fix
- ja, zh-Hans, zh-Hant CFBundleDisplayName 수정
=> 1322 2 support global language

ios/widget/zh-Hant.lproj/InfoPlist.strings
=> * [iOS][widget] 지역명 / 위젯타이틀 다국어 에러 #1636

client/www/js/controller.forecastctrl.js, client/www/js/service.weatherinfo.js
#1672 해외를 국내로 인식하는 문제
[재현 경로]
현재 위치가 국내로 설정되어 있고 Push가 켜져 있을 때 해외에서 현재 위치가 업데이트 된 경우 Push 서버에서 Source를 "KMA"로 요청하는 문제임
1. 현재 위치가 국내일 때 WeatherInfo.cities[0] 의 source는 "KMA"로 설정되어 있음
2. WeatherUtil.getGeoInfoFromGeolocation()로 가져온 위치를 WeatherInfo.cities[0]에 업데이트
- updateCity()에서 name, country, address, location 업데이트되고 Push 정보 업데이트(source = "KMA")
3. WeatherUtil.getWorldWeatherInfo()에서 가져온 날씨 정보를 WeatherInfo.cities[0]에 업데이트
- updateCity()에서 currentWeather, timeTable, timeChart, dayTable, dayChart 업데이트되고 Push 정보 업데이트(source = "KMA") 된 이후에 source가 "DSF"으로 업데이트됨
[수정 내용]
1. source는 현재 위치를 가져온 시점에서는 업데이트 되지 않고 날씨 정보를 가져와서 parsing할 때 설정되는 문제
- 현재 위치를 가져온 후에 country를 보고 source도 설정하도록 함(세계날씨 지원하는 source가 여러 가지가 생기면 실제로 요청할 source로 설정해야 함)
2. source 업데이트 이전에 Push 업데이트를 먼저 하는 문제
- updateCity()에서 …
=> #1672 해외를 국내로 인식하는 문제

client/www/index.html, client/www/js/app.js, client/www/js/controller.settingctrl.js, client/www/locales/de.json, client/www/locales/en.json, client/www/locales/ja.json, client/www/locales/ko.json, client/www/locales/zh-CN.json, client/www/locales/zh-TW.json
#1787 시작 화면 설정 기능
* "시작 페이지" 설정 추가
- 시간별날씨, 일별날씨, 즐겨찾기 중에서 선택 가능
- Default는 시간별날씨
* 설정 변경 시에 LocalStorage에 저장
* 앱 시작 시에 LocalStorage에 저장된 시작 페이지로 로드
=> #1787 시작 화면 설정 기능

server/config/config.js, server/controllers/controllerManager.js, server/controllers/controllerTown24h.js, server/controllers/geo.controller.js, server/controllers/kecoController.js, server/controllers/worldWeather/controllerWorldWeather.js, server/lib/kecoRequester.js, server/routes/v000803/index.js, server/routes/v000803/route.geo.js, server/routes/v000803/routeTownForecast.js, server/test/testGeoController.js, server/test/testKecoRequester.js, server/utils/convertGeocode.js, server/utils/getGeoCodeFromDaum.js, server/utils/updateAreaNo.js
#1646
geo api로 요청이 오면, get query에서 사용할 정도를 사용하고 없는 정보를 daum, google통해 취득 후 국가별로 routerList를 사용함.
sendResult와 makeResult를 분리해서 route.geo에서는 sendResult를 사용하지 않음
daum_key를 array형태로 변경함
=> new geo location api

client/www/js/service.twads.js
#1210 #1799
iOS에서 BANNER 좌우에 흰색여백이 생겨서 SMART_BANNER로 변경함
android에서는 SMART_BANNER가 너무 켜서 기존 유지
=> use SMART_BANNER on iOS

client/www/js/controller.forecastctrl.js, client/www/js/controller.tabctrl.js, client/www/templates/tab-dailyforecast.html, client/www/templates/tab-forecast.html
#1777
Timing issue로 광고 영역에 대한 수정후 더 빈번히 발생함
overflow-scroll 제거 -> ion-content를 ion native scroll사용하게 변경
chart current postion으로 set하는 timing 조정
loading indicator는 실제로 데이터 업데이트시에만 표시
현재위치 업데이트 시에는 loading indicator 표시 하지 않음
데이터 업데이트 이후에 500ms 후에 loading indicator 제거 (너무 빨리 제거되지 않게 보완)
etc
applyWeatherData는 loadWeatherData 시작시에만 호출
tab click이 중복 발생하여 gap time 체크후 reload event 생성
reload event sender 모두 셋업
=> ion-content, ion-scroll이 안나오거나, scroll이 동작하지 않는 문제

client/www/js/controller.air.js, client/www/js/controller.units.js, server/controllers/airkorea.dust.image.controller.js, server/controllers/controllerTown.js, server/controllers/controllerTown24h.js, server/controllers/kecoController.js, server/controllers/worldWeather/controller.ww.units.js, server/controllers/worldWeather/controllerCollector.js, server/controllers/worldWeather/controllerWorldWeather.js, server/lib/aqi.converter.js, server/lib/kmaTimeLib.js, server/lib/unitConverter.js, server/models/modelPush.js, server/routes/v000901/route.dsf.coord.js, server/routes/v000901/route.kma.addr.js, server/test/test.aqi.converter.js, server/test/testKecoController.js
#2082
- aircn -> aqicn으로 통일(aqicn.org에서 가져온 이름임)
- client도 조정함
- aqiUnit, airUnit -> airUnit으로 통일
- air_forecast -> airInfo
- last라고 가장 최근 측정값 추가
- pollutants에 오염물질별 hourly(과거,예보), daily(예보) 정보 추가
- 오염물질의 예보 val은 간격값 중에 큰값임
- daily는 범위값을 가짐
- 일별예보도 airUnit에 따라 변환함
- new aqi.converter.js
- aqi 관련 수치, 변환함수는 여기로 정리
- khaValue(aqiValue)가 없는 경우 계산 시도함
=> air_forecast -> airInfo

server/controllers/kecoController.js, server/lib/kecoRequester.js, server/routes/v000803/route.nation.js, server/test/testKecoRequester.js
#739 #1896 #2066
new getSidoArpltn func in KecoController
new saveAvgSidoArpltn func in KecoRequester
시군구별 대기정보의 평균으로는 시도별 평균이랑 동일하지 않아서,
real time data로 따로 생성함.
=> 시도별 대기정정보 평균 구하기 수정, nation api에 air 추가

server/.jshintrc, server/controllers/controllerTown.js, server/controllers/controllerTown24h.js, server/controllers/worldWeather/controllerWorldWeather.js, server/lib/aqi.converter.js, server/lib/unitConverter.js
#2082 #2092
- airGrade2Str에 airUnit받아서 분리하게 수정
- add fromToday, dayOfWeek to airInfo.pollutants[pm25|pm10|o3|aqi].daily
- min값은 이전 breakpoint + 1point(0.1 or 0.01 or 0.001)하여 이전 grade에 포함되지 않게 수정
- server/.jshintrc
- es6지원으로 변경
=> airinfo string 변환 오류 수정

client/www/js/controller.air.js
#2116
- airnow의 o3,no2,so2 값을 ppm으로 변경
- airnow, aqicn의 green color값 조정
- 사용하지 않는 dayForecastStandard 제거
=> 대기정보 기준값 테이블에서 airnow부분 업데이트

server/controllers/controllerManager.js, server/controllers/controllerTown.js, server/controllers/lifeIndexKmaController.js, server/lib/lifeIndexKmaRequester.js, server/models/kma/kma.lifeindex.model.js, server/test/e2e_local/test.e2e.lifeindex.kma.requester.js, server/test/testLifeIndexKmaRequester.js
#1511
- appendData2 추가
- client에 데이터 전달할때, LifeIndexKma2에 데이터가 없으면 기존 collections에서 전달
- taskLifeIndex2 생성
- kma.lifeindex.model 생성
- area no 없이 쿼리
- _appendLifeIndexToCurrent
- 데이터 찾으면 for문 정지
=> kma life index 개선

client/scss/ionic.app.scss, client/www/js/controller.forecastctrl.js, client/www/js/controller.tabctrl.js, client/www/templates/tab-air.html, client/www/templates/tab-dailyforecast.html, client/www/templates/tab-forecast.html
#2121
- spinner 추가
- forecast-header, dailyforecast-header 내에서 vertical-align을 middle에 맞춤
- $ionicLoading을 사용하지 않고, 로딩중에는 ion-spinner만 표시
#1846
- $scope.currentPosition, isLocationEnabled을 forecastrCtrl -> tabCtrl
- tablCtrl.init시에 realod event 생성
- scroll에 대한 css 차일드 전달되는 문제 수정
=> 데이터나 현재위치 업데이트 중에는 도시명 옆에 spinner 표시

client/www/img/weather_old/moon_lightning.png, client/www/img/weather_old/moon_rain.png, client/www/img/weather_old/moon_rain_lightning.png, client/www/img/weather_old/moon_rainsnow.png, client/www/img/weather_old/moon_rainsnow_lightning.png, client/www/img/weather_old/moon_snow.png, client/www/img/weather_old/moon_snow_lightning.png, client/www/img/weather_old/sun_lightning.png, client/www/img/weather_old/sun_rain.png, client/www/img/weather_old/sun_rain_lightning.png, client/www/img/weather_old/sun_rainsnow.png, client/www/img/weather_old/sun_rainsnow_lightning.png, client/www/img/weather_old/sun_snow.png, client/www/img/weather_old/sun_snow_lightning.png
#1425 가독성 위해 색 조정(배경색 흰색적용)
* weatherIcon2-color -> weather_old로 폴더명 변경 시 link로 걸려있는 이미지의 link가 깨져 에러 발생하는 문제
- link로 생성된 이미지 제거
=> #1425 가독성 위해 색 조정(배경색 흰색적용)

server/controllers/alert.push.controller.js, server/controllers/controllerPush.js, server/models/alert.push.model.js, server/models/modelPush.js, server/routes/v000705/routePushNotification.js, server/routes/v000902/route.push.update.list.js, server/test/e2e_local/test.e2e.alert.push.controller.js, server/test/e2e_local/test.e2e.controller.push.js, server/test/e2e_local/test.e2e.route.push.update.list.js, server/test/test.alert.push.controller.js, server/test/testControllerPush.js
#1701 #2130
- modelPush
- new id, enable
- rename dayOfWeek, 요일별 boolean 으로 변경
- alert.push.model
- new id, enable
- rename dayOfWeek, 요일별 boolean 으로 변경
- alert.push.controller
- check enable when db.find
- controllerPush
- id가 없는 경우 cityIndex에서 가져오고, update시 기준을 cityIndex->id로 변경
- find 시 enable 처리
- enable 없는 경우에도 true
- sendPush process 오류 수정
- push language 오류
- 중국어(간체,번체)는 zh-TW, zh-CN 유지
- 한국어, 영어, 일본어, 독일어는 shorten name으로 저장
- registrationId, type이 없거나, 빈문자열이면 403 에러 처리
=> push alarm, push alert 수정

server/controllers/worldWeather/controllerCollector.js
Delete past DSF data which is stored more than 1hour before
: If there is no valid DSF data in the DB, it should clear current
geocode’s DSF DB data before getting DSF data.
#2008
=> Delete past DSF data which is stored more than 1hour before 

client/www/js/controller.air.js
#2118 [0.9.78] crosswalk에서 대기정보페이지 내 스크롤이 동작하지 않음.
* 대기정보페이지에서 back버튼으로 앱이 종료되도록 clearHistory 처리 추가
* clearHistory 추가로 스크롤이 되지 않는 문제도 수정됨
=> #2118 [0.9.78] crosswalk에서 대기정보페이지 내 스크롤이 동작하지 않음.

server/controllers/airkorea.dust.image.controller.js, server/controllers/airkorea.hourly.forecast.controller.js, server/lib/kecoRequester.js
#2152 #2139 #2114
- airkorea.hourly.forecast.controller
- waterfall에서 callback을 param 없이 넘기면, 받는 곳에서 func이 첫 파람으로 옴
- map으로 하는 경우 local에서 락걸리는 경우가 있어 mapSeries로 변경
- image 못 가지고 오거나, 중간에 에러나는 경우 재시도하게 수정
- airkorea.dust.image.controller
- log level 조정
=> pm10 hourly foreacst 수집중에 map이 종료되지 않고 멈춰 있는 문제

client/scss/ionic.app.scss, client/www/js/controller.forecastctrl.js, client/www/templates/tab-air.html, client/www/templates/tab-dailyforecast.html, client/www/templates/tab-forecast.html
TW-139 [0.9.81] 4:3 화면비에서 겹치는 문제 #2220
* md-page-header의 height을 controller에서 계산해서 설정하는데 summary가 길어지거나 화면 크기가 작은 경우 header 영역을 벗어나는 문제가 발생함
- controller에서 계산한 headerHeight를 min-height으로 설정하여 최소 높이만 보장하고 하위 child 크기 만큼 커질 수 있도록 함
* md-page-header와 chart 사이에 여백 추가
=> TW-139 [0.9.81] 4:3 화면비에서 겹치는 문제 #2220

client/scss/ionic.app.scss, client/www/templates/tab-forecast.html
TW-129 하단 탭과 광고 영역 구분 필요 #2196
* <ion-side-menu-content> 하위의 <ion-nav-view>의 하단 border 추가하여 모든 page의 하단에 표시됨
* .tabs로 설정된 background-image: linear-gradient(0deg, #b2b2b2, #b2b2b2 50%, transparent 70%);으로 tabs의 상단 border 표시되고 있음
=> TW-129 하단 탭과 광고 영역 구분 필요 #2196

server/lib/kecoRequester.js
- 주소가 없는 경우 skip
- 주소에서 이동차량 문자열 제거
- getGeoInfo 실패시에도 callback으로 err 넘기지 않음
=> TW-149 일반적이지 않은 msrstn 주소 때문에 오류 발생

ios/widget/MainInterface.storyboard
+ [iOS][widget] 더보기를 눌렀을 시에 더보기 뷰가 아래로 내려올때 살짝 겹쳐지는 느낌이 안나오게 수정
- #TW-143 storyboard의 showmoreview의 autoresizing을 수정
=> TW-143 storyboard의 showmoreview의 autoresizing을 수정

client/scss/ionic.app.scss, client/www/js/app.js, client/www/js/controller.air.js, client/www/templates/tab-air.html
TW-95 미세먼지 페이지에서 시간별 예보 표시 #1849
* 상세대기정보에서 통합대기를 맨 앞에 표시
* 시간별대기예보를 차트로 표시하도록 지원
- airInfo.pollutant.hourly 중에서 과거 11개 + 현재 + 미래 12개의 데이터로 표시
- 예보 데이터가 없는 경우에는 미래 12개의 데이터를 none 값으로 처리
- min과 max의 중간값이 차트 높이의 중간에 위치하도록 보정
- 현재 데이터의 경우 다른 시간 데이터와 구분하기 위해 opacity를 1로 설정해서 진하게 표시
=> TW-95 미세먼지 페이지에서 시간별 예보 표시 #1849

server/config/config.js, server/controllers/airkorea.hourly.forecast.controller.js, server/controllers/controllerManager.js, server/controllers/controllerTown.js, server/controllers/controllerTown24h.js, server/controllers/img.hourly.forecast.controller.js, server/controllers/kaq.dust.image.controller.js, server/controllers/kaq.hourly.forecast.controller.js, server/models/kaq.hourly.forecast.model.js, server/routes/v000901/route.kma.addr.js, server/routes/v000902/route.kma.v000902.js, server/s3/controller.s3.js, server/test/e2e_local/test.e2e.kaq.hourly.forecast.controller.js
- AirkoreaHourlyForecastController
- ImgHourlyForecastController라는 부모 클래스 생성하고, Kaq와 같이 사용
- controllerManager
- 사용하지 않는 checkTimeAndPushTask 제거
- _requestApi에서 결과 응답을 받지 못하여 KaqHourlyForecast를 direct call하게 구현
- controllerTown, controllerTown24
- request query에 airForecastSource 값에 따라 airkorea, kaq 사용하게 구현
- KecoController.getDustFrcst를 airForecastSource query에 따라 사용되게 변경
- 시간별 예보는 24시간만 전달
- pollutant.daily에 val(평균값) 추가
- rename AirkoreaForecast -> AirForecast
- KaqDustImageController
- value max 조정
=> TW-174 K Image data를 DB에 저장 및 추출

client/www/js/controller.air.js, client/www/templates/tab-air.html, client/www/templates/tab-forecast.html
TW-163 대기정보가 없는 경우 페이지 개선
* cityData.airInfo.last, cityData.currentWeather.arpltn가 비어있거나, cityData.airInfo.pollutants가 정의되어 있지 않은 경우 예외처리 추가
- 대기정보 페이지에서는 측정값이 없는 상태로 표시, 측정소 정보 숨김 처리
- 시간별날씨 페이지에서는 현재 대기정보, 상세 대기정보 숨김 처리
=> TW-163 대기정보가 없는 경우 페이지 개선

ios/widget/TodayViewController.m
+ 	#TW-178 iOS Widget "로드할 수 없음"으로 표시됨
- loadWeatherData에서 Dictionary 출력시 너무 많은 데이터는 buffer overflow를 유발함
=> TW178-- loadWeatherData에서 NSLog disable

client/www/js/controller.air.js, client/www/templates/tab-forecast.html
#2274
- current.arpltn의 validation 체크를 date에서 dataTime으로 변경
- 원래 dataTime으로 했어야 함
- 오염물질 측정치가 0인경우 '-'로 표시되는 문제 수정
- ||가 아니라 undefined로 체크
=> TW-95 뉴욕지역 시간별날씨에서 대기정보 안보이는 문제, 대기오염물질이 0인경우 오류

client/scss/ionic.app.scss
TW-202 설정 화면에서 메뉴 리스트의 크기가 다른 문제
* 다음 depth가 있는 경우와 없는 경우 구분하지 않고 동일한 스타일로 변경
- scss 파일 수정
=> TW-202 설정 화면에서 메뉴 리스트의 크기가 다른 문제

server/controllers/kaq.hourly.forecast.controller.js, server/models/kaq.hourly.forecast.model.js, server/models/kaq.map.case.model.js, server/test/e2e_local/test.e2e.kaq.hourly.forecast.controller.js
- new kaq.map.case.model
- kaq 에서 현재 사용하는 map case 정보를 받아옴
- kaq.hourly.forecast.model
- new mapCase
- getForecast 시에 저장된 mapCase나 없는 경우 CASE4를 사용하게 적용
=> TW-197 4의 model에 대하여 DB에 저장하고, model별로 사용

server/controllers/kma/kma.town.current.controller.js, server/controllers/kma/kma.town.mid.controller.js, server/controllers/kma/kma.town.short.controller.js, server/controllers/kma/kma.town.short.rss.controller.js, server/controllers/kma/kma.town.shortest.controller.js, server/lib/PastConditionGather.js, server/lib/collectTownForecast.js
- kma.town.current.controller
- 삭제시 기준을 fcsDate로 변경
- collectTownForecast
- network에 나올 수 있는 오류는 로그 레벨 낮게 조정
- PastGather
- db 2.0에 맞게 빠진 데이터 찾는 _checkBaseTimeByCoord2 만듬
=> TW-212 current data가 소실되면서 "Fail to parse sky=-1"가 발생하는 문제

server/controllers/controllerKmaStnWeather.js
- 원인 : rns에 의해 강수가 결정되면 발생
- weatherType을 0으로 설정하여 pty에 따라 변경되게 함
=> TW-214 비오는데 "weather type is undefined" 인 경우

server/controllers/controllerTown24h.js, server/controllers/kaq.hourly.forecast.controller.js
- controllerTown24h
- 최종 측정 시간보다 늦을 날짜 데이터는 제외
- 마지막 일별 데이터도 제외(24개가 안됨)
- kaq.hourly.forecast
- 오늘날짜 예보를 완성하기위해 하루전부터 데이터를 꺼냄
=> TW-216 과거 일별 대기 정보 안 나오게 변경

server/lib/midRssKmaRequester.js
- 잘못된 파라미터 전달로 불필요한 error log 출력
=> TW-211 fix wrong param of callback

client/www/js/controller.tabctrl.js, client/www/locales/de.json, client/www/locales/en.json, client/www/locales/ja.json, client/www/locales/ko.json, client/www/locales/zh-CN.json, client/www/locales/zh-TW.json
* 안드로이드일 때 즐겨찾기, 시간별날씨, 일별날씨, 대기정보, 날씨 페이지에서 back 버튼을 누르면 '종료하시겠습니까?' 팝업을 띄우도록 처리
- 앱 실행 후 터치없이 back 버튼을 누른 경우 바로 종료됨(이벤트가 발생하지 않음)
=> TW-217 페이지 히스토리 없이 종료에 대한 개선 요청

client/scss/ionic.app.scss, client/www/data/theme.js, client/www/index.html, client/www/js/app.js, client/www/js/controller.forecastctrl.js, client/www/js/controller.searchctrl.js, client/www/js/controller.setting.radio.js, client/www/js/controller.settingctrl.js, client/www/js/controller.tabctrl.js, client/www/js/service.storage.js, client/www/js/service.weatherinfo.js, client/www/locales/de.json, client/www/locales/en.json, client/www/locales/ja.json, client/www/locales/ko.json, client/www/locales/zh-CN.json, client/www/locales/zh-TW.json, client/www/templates/tab-air.html, client/www/templates/tab-dailyforecast.html, client/www/templates/tab-forecast.html
1. ios에서 body 위치가 header bar 아래에 있는 문제 수정
1. ios에서 main-content의 top이 0으로 설정되지 않아 !important 속성 추가
2. ios의 경우 header bar에 status bar도 포함되어 있으므로 md-page-header의 padding-top을 64px로 설정
2. 날씨 사진 표시 설정 대신 테마 설정으로 변경
1. 날씨 사진 표시 off는 밝은 테마로, on은 날씨 사진 테마로 처리
2. theme.js에 각 테마별로 default icons, weather 경로 설정
3. app.run 호출 시, 테마가 변경되면 icons, weather의 imgPath 설정
4. md-page-header의 .photo, no-photo class 제거
5. theme-apply directive 추가, forecast, dailyforecast의 ion-content에 추가
1. ion-content가 로드될 때 photo class 추가
2. stateChangeStart 이벤트가 발생하면 photo class 제거
3. SettingCtrl 대신 TwStorage의 init에서 settingsInfo 초기값 설정 및 $rootScope.settingsInfo 값 설정 처리
1. TwStorage의 init에서 $rootScope.settingsInfo에 초기값 설정
2. 저장된 settingsInfo 값이 없으면 $rootScope.settingsInfo를 TwStorage에 저장
3. 저장된 settingsInfo 값이 있으면 그 값을 …
=> TW-145 날씨 사진 테마 지원 #1855

server/package.json
- mongoose update이후 db query 추적이 안됨, 버전업해도 안되는듯하지만 현재 버전이 오래되어 업그레이드 진행
=> TW-242 upgrade new relic agent

client/www/index.html, client/www/js/app.js, client/www/js/service.storage.js
* 이전 상태와 같이 상태바를 bar-dark로 변경함
- ios의 경우 상태바가 body의 배경색으로 표시되도록 overlay 처리되어 있어 배경색 테마 작업 시 정상적으로 처리되도록 수정할 예정
* 날씨 사진 테마 대신 밝은 테마를 기본으로 변경
- 첫 로딩 시 사진이 늦게 표시되는 문제 수정이 되면 기본 테마를 날씨 사진 테마로 변경할 예정
=> TW-284 [iOS] 상태바 컬러 조정

client/www/js/app.js, client/www/js/controller.forecastctrl.js, client/www/js/controller.searchctrl.js, client/www/js/service.weatherinfo.js
* 앱 실행 시 날씨 사진을 가져오지 못한 경우, network 연결이 되거나 날씨 정보가 업데이트될 때 날씨 사진을 재로드 처리
* WeatherUtil.findWeatherPhoto()에서 tag 검색되지 않는 문제
- currentWeather.skyIcon의 기본값을 'Sun' 대신 'sun'으로 변경
* chart scroll의 console.error 주석 처리
- 시간별날씨, 일별날씨에서는 하나만 있기 때문에 항상 에러로 표시되어 주석 처리함
=> TW-323 초기 인터넷이 안된 경우 날씨 사진이 표시 안됨

server/controllers/worldWeather/controllerWorldWeather.js, server/controllers/worldWeather/dsf.controller.js
- no adding thistime data if it’s already existed.
- Use data’s own timeOffset to prevent changing timeoffset from time to
time.
=> TW-58 fixed timeOffset

server/routes/v000803/route.nation.js
=> TW-384 airUnit=aircn으로 전국날씨 요청시에 서버 죽는 문제

client/scss/ionic.app.scss, client/www/js/app.js, client/www/js/controller.forecastctrl.js, client/www/js/controller.tabctrl.js, client/www/templates/ta-tab-weather.html, client/www/templates/tab-forecast.html
TW-97 시간별 습도, 풍향, 풍속 정보 표시 #1852
* 시간별 차트 하단에 펴기/접기 버튼 표시
- 초기값은 펴기 버튼 상태
* 펴기/접기 버튼 클릭 시 풍향/풍속/습도를 표시
- 풍향은 wind_direction.png 이미지를 회전시켜 처리
* TodayAir의 날씨 페이지에도 동일하게 적용, 테마 지원
=> TW-97 시간별 습도, 풍향, 풍속 정보 표시 #1852

client/scss/ionic.app.scss, client/www/js/controller.forecastctrl.js, client/www/js/controller.tabctrl.js, client/www/templates/ta-tab-weather.html, client/www/templates/tab-air.html, client/www/templates/tab-dailyforecast.html, client/www/templates/tab-forecast.html
TW-409 화면 사이즈에 따라 TopBox, 차트의 사이즈를 비율로 계산하는 코드 정리
* material design에서 정의된 해상도에 따른 column의 수에 맞게 bodyHeight를 분할하는 비율을 변경하여 TopBox의 높이 설정
- 최소 크기를 기준으로 계산된 TopBox 최소 높이 보장 처리
- TopBox에 표시되는 큰 이미지와 큰 글자 크기도 비율에 맞게 계산
- 시간별 날씨 차트의 작은 이미지 크기는 column width에 따라 계산
- 사용하지 않는 크기값 제거
- 일별 차트의 경우 가로보기 화면에서 가로 전체가 채워지게 column width 설정
* 각 차트의 높이는 실제 텍스트 + 이미지 + 마진 크기로 계산되도록 함
=> TW-409 화면 사이즈에 따라 TopBox, 차트의 사이즈를 비율로 계산하는 코드 정리

server/controllers/timezone.controller.js
- Added workaround code which swap string from "Asia/Tokyo" to "Tokyo".
: In case of Japan, the server would use "Asia/Tokyo" string as TimezoneID and query it via Google API in order to get present geocode for Japan. But Google API would return Chicago's geocode
=> TW-422 wrong timeoffset for tokyo
